### PR TITLE
cleanup: remove unused file

### PR DESCRIPTION
**Pull request by sebpop**

### CODE REVIEW

**Comment by mtl1979** [comment]
This is bad...

**Comment by sebpop** [comment]
@mtl1979 could you please be more specific about what you mean?
Is the commit bad?
Or is it bad because we have a file that is unused?

**Comment by mtl1979** [comment]
For both reasons... Obviously the file was meant to be used to quickly find out what intrinsic functions are available on specific compiler versions but rationale for including it was never documented.

**Comment by Dead2** [comment]
No, it finds what intrinsics are referenced from source files, making it easier to figure out what SSE/AVX etc versions are required by different source files.
In its current form, it likely has little value, but in a more developed form, it could possibly be helpful for code reviews (in any kind of code, not just zlib-ng).
I do not object to its removal.

**Pull request merged**
