### PR TITLE
Add ARM cross build and validation

### PR DESCRIPTION
**Pull request by JunHe77**
Update configure and test scripts to cross compile
and validate arm build-outs on x86 by using qemu

Change-Id: I183d003ebafcf686de26fd1705704ded4b344580
Signed-off-by: Jun He <jun.he@arm.com>

### CODE REVIEW

**Comment by mtl1979** [comment]
This is bad. Does not actually test qemu supports running non-native binaries.

**Comment by JunHe77** [comment]
Hi, @mtl1979 , may I know why qemu cannot be used for testing non-native binaries? I can try to solve them if possible. 😃 

As for this patch, enabling cross compile will help build test coverage for people without actual hw.
And as the built-out binaries are all working in user mode, qemu-* should be enough to validate if these binaries are basicaly working.
FYR, an sample output can be found at: https://travis-ci.org/JunHe77/zlib-ng/builds/368500583

Pls let me know how I can improve this patch, cause I think it is really matters to verify zlib-ng for non x86 platforms in CI. Thanks.

**Comment by mtl1979** [comment]
Obviously it should test that the QEMU_RUN executable actually exists as it can fail if someone tries to configure outside Travis.

**Comment by JunHe77** [comment]
If someone doesn't have QEMU installed, the whole build process still goes well. It only fails when the user runs "make test" or "make check", output as following:
`/bin/sh: 2: /bin/sh: 2: qemu-aarch64: not foundqemu-aarch64: not found`
This error message is pretty straightforward to know what is missing and test is stopped without creating any misleading/wrong result. I'll say this behavior is acceptable. 😁 

If you prefer to give user more/direct information on this failure, is following way OK?
`builder@06d6c1a2f66a:~/zlib-ng$ make -C test`
`make: Entering directory '/home/builder/zlib-ng/test'`
`Makefile:24: *** "You need QEMU to run tests on non-native platform".  Stop.`
`make: Leaving directory '/home/builder/zlib-ng/test`

**Comment by mtl1979** [comment]
I think human readable error message is better...

**Comment by JunHe77** [comment]
Patch is updated. If no qemu-* installed, user will see following error message:
`Makefile:24: *** "You need QEMU to run tests on non-native platform". Stop.`

**Comment by mtl1979** [comment]
Just a minor style issue remaining in the patch... in "configure" you removed two empty lines outside the patched section... Generally those kind of changes should not be bundled with code changes. It's easier for git to track changes, when the patch is as short as possible.

**Comment by JunHe77** [comment]
Thanks for pointing it out. I've updated it. Pls review.

**Comment by JunHe77** [comment]
Ping, @mtl1979 . Is there any other issues need to be fixed? Thanks.

**Comment by mtl1979** [comment]
@JunHe77 I'm waiting for @Dead2 to give his opinion... I don't have commit rights...

**Comment by Dead2** [comment]
Looks great, thanks

**Comment by JunHe77** [comment]
Thank you, @mtl1979, for patient review and help. Thank you, @Dead2 for merge this. 😄

**Pull request merged**
