### PR TITLE
Sync adler32 calc for short buffer lengths

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
MacOS GCC failing who knows why.. maybe rerun CI?

**Comment by mtl1979** [comment]
@nmoinvaz I can't see any reason in the current pull request that should cause failure only in MacOS builds...

**Comment by nmoinvaz** [comment]
The CI run in my fork had passed: https://github.com/nmoinvaz/zlib-ng/actions/runs/609080957. Maybe it is hardware failure.

**Comment by nmoinvaz** [comment]
Rebased.

**Pull request merged**
