### PR TITLE
Fixed cmake formatting

### PR DESCRIPTION
**Pull request by nmoinvaz**
- Unify most of the option() and add_feature_info() statements to the top.
- Updated comments to all begin with proper casing.
- Convert tabs to spaces.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
In order to unify the option() and add_feature_info() some blocks had to be moved down. 
Also remove stuff like `else(NOT NATIVEFLAG)` because it is too easy to confuse with an actual if statement such as `elseif(NOT NATIVEFLAG)`.

**Comment by Dead2** [comment]
Please go through your remaining PRs and check that they are still mergeable, and rebase the ones that need it (unless they depend on another open PR, then there is no reason to do so yet). :)

Some of the remaining ones might need to more reviewing, testing and/or time to bake though.

**Comment by nmoinvaz** [comment]
Ok, the rebasing is complete.

**Comment by Dead2** [comment]
There are still two conflicting blocks in this PR.
When I compare zlib-ng:develop's commit log with the commit log one used in this PR, I see several missing commits. It looks to me like you did not run a `git rebase`, and I am worried that this might cause unintended reverts of changes from the commits you are missing. In this case, the DFLTCC conflict contains such a revert. Running a proper rebase would make git request manual merging of the conflicts, so that such errors will be more easily spotted.
Hope you can go through this one again, and fix the conflicts. :)

**Comment by nmoinvaz** [comment]
I figured out the rebase. Should be good to go now.

**Comment by Dead2** [comment]
Looks good, thanks!

**Pull request merged**
