### PR TITLE
Support aligned alloc/free functions for Windows

### PR DESCRIPTION
**Pull request by nmoinvaz**
I have also moved the malloc.h include after `MY_ZCALLOC` incase it is defined then the include is not necessary. This essentially allows you to compile with `-DUNALIGNED_OK=OFF` on Windows.

### CODE REVIEW

**Comment by Dead2** [comment]
Rebase needed

**Comment by Dead2** [comment]
Looks good to me, but I'd like to see another review of this in case I missed something.

**Comment by mtl1979** [comment]
My compiler doesn't define ```WINDOWS```, but does define ```_WIN32```...

**Comment by nmoinvaz** [comment]
`WINDOWS` is defined in zconf.h

**Comment by Dead2** [comment]
Hmm, WIN32 could potentially be set without WINDOWS being set, does that ever happen in real life?
```c
#if defined(_WINDOWS) && !defined(WINDOWS)
#  define WINDOWS
#endif
#if defined(_WIN32) || defined(__WIN32__)
#  ifndef WIN32
#    define WIN32
#  endif
#endif
```

**Comment by nmoinvaz** [comment]
Yeah I don't know if that is necessary anymore.

**Comment by nmoinvaz** [comment]
Rebase done and changed to `_WIN32`.

**Comment by Dead2** [comment]
@mtl1979 Does this look good to you now?

**Comment by mtl1979** [comment]
I'm not really fan of changing ```#ifndef``` to ```#if !defined``` when there is only one condition... It makes the patch longer than necessary and essentially mixes style changes with code changes.

**Comment by nmoinvaz** [comment]
Fixed.

**Pull request merged**
