### PR TITLE
Make DYNAMIC_CRC_TABLE configurable in CMake

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Actually it looks like this `DYNAMIC_CRC_TABLE` define no longer works correctly.

**Comment by Dead2** [comment]
I am not sure that is something we want to support either, is there any reason to except for saving flash space in embedded?

**Comment by nmoinvaz** [comment]
We used to use it at work to keep down executable size. But there are some benefits to not using it, namely you don't have to worry about calling initialization function to create the tables. I would be in favor of removing what is left of it (since it is broken now). Also having a separate tool that generates the crc tables  (makecrct) makes for nice separation of code.

**Comment by Dead2** [comment]
Yeah, lets remove it. The code is complex enough without having complexity that is not really needed.

**Pull request closed without merging**
