### PR TITLE
abicheck.sh: update reference versions

### PR DESCRIPTION
**Pull request by dankegel**
Can't land this until the differences against zlib's new version's function signatures are dealt with somehow.

### CODE REVIEW

**Comment by mtl1979** [comment]
As Windows (maybe also other non-ELF operating systems) doesn't support symbol versions, in my opinion we should just drop the old versions but in the end it's @Dead2 who makes the final call.

**Comment by dankegel** [comment]
I think this didn't find the new functions mentioned in https://github.com/zlib-ng/zlib-ng/pull/1229, so I should look at that...

**Comment by nmoinvaz** [comment]
Well those functions were already being exported in the .map file.

It was just in the win32 .def files mostly where they weren't being exported.

**Comment by nmoinvaz** [comment]
I'm not sure if the check scripts that you have take into account win32 or not.

**Comment by Dead2** [comment]
I am sorry, I have lost track a bit, but afaik this should pass tests after a rebase, right?

**Comment by nmoinvaz** [comment]
I think we are going to want this for #1268.

**Comment by mtl1979** [comment]
@nmoinvaz Kind of chicken and egg problem... Would need to be sure that merging both separately results in no CI failures...

**Comment by nmoinvaz** [comment]
@dankegel are you able to rebase this? Thanks.

**Comment by nmoinvaz** [comment]
Requires #1268.

**Comment by Dead2** [comment]
I guess #1163 should also go in before this.

**Comment by nmoinvaz** [comment]
Merged in as #1276.

**Pull request closed without merging**
