### PR TITLE
Improve dual link testing

### PR DESCRIPTION
**Pull request by nmoinvaz**
- Added a `gtest` test that compiles against the zlib that we are using for dual link testing.
- Moved dual linking test into its own GHA workflow
- In new CI, it tests compiling and linking `madler/zlib:develop` against zlib-ng native api
- In new CI, it tests compiling and linking zlib-ng compat api against zlib-ng native api 
  - #1279

### CODE REVIEW

**Comment by Dead2** [comment]
@nmoinvaz Test supposed to fail linking currently?

**Comment by nmoinvaz** [comment]
Yes it is suppose to fail until we actually fix those issues. I could try and do it in this PR or another.. I would just go the macro route..

**Review by Dead2 — APPROVED** [review]

**Comment by mtl1979** [comment]
I'd rather see the fix in either separate commit in this PR or merged before this PR... This way we can verify that the fix is complete and doesn't cause any unacceptable regressions. The reasoning is pretty much same as was for the fix and tests for deflateBound/compressBound.

**Comment by nmoinvaz** [comment]
I am not so sure that the ordering really matters. There is a way to verify that the tests pass either way.

**Pull request merged**
