### PR TITLE
Add VPCLMULQDQ crc32 tests to Google benchmarks

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Review by Dead2 — APPROVED** [review]
LGTM 👍

**Comment by nmoinvaz** [comment]
Strange, it seems this potentially discovered a crash on GCC benchmark with VPCLMULQDQ. @KungFuJesus maybe you can take a look?

**Comment by Dead2** [comment]
> Strange, it seems this potentially discovered a crash on GCC benchmark with VPCLMULQDQ.

The test machine doesn't have AVX512, so it shouldn't try to use VPCLMULQDQ at all. So looks like the cpu check is possibly at fault somehow.

**Comment by nmoinvaz** [comment]
Good observation I didn't think about that possibility.

**Comment by nmoinvaz** [comment]
I think I missed some of the logic for the benchmark condition. I found existing logic elsewhere and just copied it.

**Comment by nmoinvaz** [comment]
That doesn't seem to have fixed it. So maybe there is a bug in CPU runtime detection..

**Comment by nmoinvaz** [comment]
For example, here is what running the same crc32 tests on my desktop (without AVX512) using MSVC shows:
image

**Comment by nmoinvaz** [comment]
Looks like that fixed it.

**Comment by nmoinvaz** [comment]
I'm not sure why the code coverage would be less... 
image
Seems ok?

**Comment by mtl1979** [comment]
> I'm not sure why the code coverage would be less... image Seems ok?

There is a lot of partial coverage on the lines with preprocessor macros... This suggests that some of the expanded code is not reached.

**Comment by nmoinvaz** [comment]
Ah yea those Google testing/benchmark macros have a lot of boilerplate.

**Pull request merged**
