### PR TITLE
Stable release 2.0.0

### PR DESCRIPTION
**Pull request by Dead2**
Time for the big release, last chance to find any remaining important issues before release.

PS: This depends on the readme/manpage PR #865.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Hi.  I'd be happy to test zlib-ng inside [c-blosc2](https://github.com/Blosc/c-blosc2).  One of the decisions we have made there is that we must be able to vendor the different codecs that c-blosc2 uses, so we typically put them in a dedicated directory inside the c-blosc2 dir structure.  Right now, we are using [miniz](https://github.com/Blosc/c-blosc2/tree/master/internal-complibs/miniz-2.0.8), and I have tried the next patch for compiling with zlib-ng instead:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7930e5b..9c3df43 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -153,12 +153,12 @@ if(NOT DEACTIVATE_ZLIB)
         set(ZLIB_ROOT $ENV{ZLIB_ROOT})
         find_package(ZLIB)
         if(NOT ZLIB_FOUND)
-            message(STATUS "No ZLIB found.  Using MINIZ internal sources.")
-            set(HAVE_MINIZ TRUE)
+            message(STATUS "No ZLIB found.  Using ZLIB-NG internal sources.")
+            set(HAVE_ZLIB TRUE)
         endif()
     else()
-        message(STATUS "Using MINIZ internal sources for ZLIB support.")
-        set(HAVE_MINIZ TRUE)
+        message(STATUS "Using ZLIB-NG internal sources for ZLIB support.")
+        set(HAVE_ZLIB TRUE)
     endif()
     # HAVE_ZLIB will be set to true because even if the library is not found,
     # we will use the included sources for it
@@ -356,6 +356,9 @@ endif()

 # subdirectories
 add_subdirectory(blosc)
+set(ZLIB_COMPAT TRUE)
+add_subdirectory(internal-complibs/zlib-ng-2.0.0-RC2)
+

 if(BUILD_TESTS)
     enable_testing()
diff --git a/blosc/CMakeLists.txt b/blosc/CMakeLists.txt
index 21ead9e..6c67b7c 100644
--- a/blosc/CMakeLists.txt
+++ b/blosc/CMakeLists.txt
@@ -32,7 +32,7 @@ if(NOT DEACTIVATE_ZLIB)
     if(ZLIB_FOUND)
         set(BLOSC_INCLUDE_DIRS ${BLOSC_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIR})
     else()
-        set(ZLIB_LOCAL_DIR ${INTERNAL_LIBS}/miniz-2.0.8)
+        set(ZLIB_LOCAL_DIR ${INTERNAL_LIBS}/zlib-ng-2.0.0-RC2)
         set(BLOSC_INCLUDE_DIRS ${BLOSC_INCLUDE_DIRS} ${ZLIB_LOCAL_DIR})
     endif()
 endif()
```

After that, the cmake output for c-blosc2 looks pretty good:

```
$ cmake ..
<snip>
-- Using CMake version 3.19.2
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 2.0.0-RC2
-- Arch detected: 'aarch64'
-- Basearch of 'aarch64' has been detected as: 'arm'
<snip>
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Release (selected)
 * WITH_GZFILEOP, Compile with support for gzFile related functions
 * ZLIB_COMPAT, Compile with zlib compatible API
 * ZLIB_ENABLE_TESTS, Build test binaries
<snip>
-- Generating done
-- Build files have been written to: /Users/faltet/blosc/c-blosc2/build
```

but during the make step, I run into issues:

```
$ make
Scanning dependencies of target blosc2_static
[  0%] Building C object blosc/CMakeFiles/blosc2_static.dir/blosc2.c.o
In file included from /Users/faltet/blosc/c-blosc2/blosc/blosc2.c:50:
/Users/faltet/blosc/c-blosc2/internal-complibs/zlib-ng-2.0.0-RC2/zlib.h:218:1: error: unknown type name 'Z_EXTERN'
Z_EXTERN const char * Z_EXPORT zlibVersion(void);
^
/Users/faltet/blosc/c-blosc2/internal-complibs/zlib-ng-2.0.0-RC2/zlib.h:218:31: error: expected ';' after top level declarator
Z_EXTERN const char * Z_EXPORT zlibVersion(void);
                              ^
<snip>
```

Could you shed some light on what I am missing?  Thanks in advance.

**Comment by mtl1979** [comment]
```Build files have been written to: /Users/faltet/blosc/c-blosc2/build```

This line shows what the binary directory for the project is... But it is not the same that ```add_subdirectory``` expects... you need to pass binary directory as second parameter for ```add_subdirectory``` if any files are generated so the directory is added to include path.

**Comment by FrancescAlted** [comment]
> `Build files have been written to: /Users/faltet/blosc/c-blosc2/build`
> 
> This line shows what the binary directory for the project is... But it is not the same that `add_subdirectory` expects... you need to pass binary directory as second parameter for `add_subdirectory` if any files are generated so the directory is added to include path.

It turns out that the solution for our needs required a larger hack than this: https://github.com/Blosc/c-blosc2/pull/260.  Thanks anyway.

**Comment by Dead2** [comment]
Planned release tomorrow, Monday March 15th, unless we find any new blockers.

**Comment by past-due** [comment]
EDIT: Whoops - got ahead of myself.

@Dead2: Thank you for all of your fantastic work!

**Comment by Dead2** [comment]
I will postpone the release for PR #875, since it could cause silent corruption.

**Pull request merged**
