### PR TITLE
Cleanup old legacy makefiles and scripts

### PR DESCRIPTION
**Pull request by nmoinvaz**
I found out that the issue on Windows (see #338) was due to missing files from the repository. In that even though it was using cmake, it still required the use of "zconf.in" and from there the "zconf.in.cmakein" was built. With these changes I have removed all the unix makefiles and scripts and now there only exists "cmakein" files. 

In addition I've cleaned up the support text files and moved some of their contents into README.md and make it so that the most important information for developers is available right there to start.

I also moved the CVE tests to use the cmake test apparatus. I had to use a python script (cross-platform) in order to evaluate a different exit code other than 1 which was necessary for the old tests.

### CODE REVIEW

**Comment by mtl1979** [comment]
```
-- Renaming
--     /home/travis/build/zlib-ng/zlib-ng/zconf-ng.h.cmakein
-- to 'zconf-ng.h.cmakeincluded' because this file is included with zlib
-- but CMake generates it automatically in the build directory.
CMake Error: File /home/travis/build/zlib-ng/build/zconf-ng.h.cmakein does not exist.
CMake Error at CMakeLists.txt:653 (configure_file):
  configure_file Problem configuring file
```

**Comment by nmoinvaz** [comment]
I have to still take a look at the CI and try and see what I can do to fix all the environments.

**Comment by mtl1979** [comment]
Now Travis is failing because cross-compiler detection is not implemented correctly in CMakeLists.txt ...

**Comment by nmoinvaz** [comment]
Will reopen when I got it working.

**Comment by mtl1979** [comment]
The problem is that ```MAKE``` is special variable that many commands depend on, so it can't have any parameters specified... you need to use another variable to pass any required build parameters.

**Pull request closed without merging**
