### PR TITLE
Rename Z defines for consistency

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Rebased

**Comment by Dead2** [comment]
Does this cause problems with stock `zlib.h` compatibility in any way?

I also wonder whether we should be using the WINAPIV call type for all functions in zlib-ng native. I suspect the WINAPI version was chosen at an early point before WINAPIV existed (or was needed), and they couldn't break that compatibility once chosen.

Using the same call method everywhere might be a good thing IMO, should we change the default for our native builds?

**Comment by mtl1979** [comment]
@Dead2 Only benefit for using WINAPIV is that it supports variadic parameters, otherwise the two are the same feature-wise.

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by nmoinvaz** [comment]
@Dead2 I have kept some few references to `ZLIB_INTERNAL` for zlib.h compatibility.

**Pull request merged**
