### PR TITLE
Improve the swizzle of the memory magazine fed in a chunk copy for neon

### PR DESCRIPTION
**Pull request by KungFuJesus**
Like the x86 variant, we can leverage the same tables to load a vector
register worth of values. This shows a vast improvement in places where
very large run length encodes can be found in the lz runs.

### CODE REVIEW

**Comment by KungFuJesus** [comment]
Improvement for both the Cortex-A73 and Cortex-A53:
```
A73:

Comparing png_decode/ (from ./benchmark_zlib_apps_reference) to png_decode/ (from ./benchmark_zlib_apps)
Benchmark                                                                            Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_pvalue                 0.1212          0.1212      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_mean                  +0.0033         +0.0033          3767          3779          3761          3773
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_median                +0.0023         +0.0023          3757          3766          3751          3760
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_stddev                +0.0066         +0.0038            24            25            24            25
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_cv                    +0.0032         +0.0005             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_pvalue                 0.1620          0.1620      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_mean                  +0.0016         +0.0016          2934          2938          2929          2934
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_median                +0.0025         +0.0025          2957          2964          2952          2960
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_stddev                +0.0170         +0.0126            37            37            37            37
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_cv                    +0.0153         +0.0110             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_pvalue                 0.3847          0.3847      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_mean                  +0.0009         +0.0009          2976          2979          2972          2974
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_median                +0.0010         +0.0010          2994          2997          2989          2992
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_stddev                +0.0173         +0.0184            27            28            27            27
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_cv                    +0.0163         +0.0175             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_pvalue                 0.0890          0.0890      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_mean                  -0.0054         -0.0053          2999          2983          2995          2979
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_median                -0.0060         -0.0060          3013          2995          3008          2990
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_stddev                -0.1222         -0.1201            22            19            22            20
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_cv                    -0.1175         -0.1153             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_pvalue                 0.1212          0.1212      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_mean                  +0.0039         +0.0039          2919          2930          2914          2926
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_median                +0.0041         +0.0041          2939          2951          2934          2946
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_stddev                +0.0300         +0.0292            34            35            34            34
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_cv                    +0.0260         +0.0252             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_mean                  -0.0197         -0.0197          3071          3010          3066          3005
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_median                -0.0205         -0.0205          3078          3015          3073          3010
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_stddev                -0.1171         -0.1142            20            18            20            18
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_cv                    -0.0994         -0.0964             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_pvalue                 0.9698          0.9698      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_mean                  +0.0000         +0.0000          2965          2965          2960          2960
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_median                +0.0002         +0.0003          2987          2988          2982          2983
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_stddev                +0.0081         +0.0112            35            35            34            35
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_cv                    +0.0081         +0.0112             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_mean                  -0.2271         -0.2270          3859          2983          3853          2978
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_median                -0.2257         -0.2257          3869          2996          3863          2991
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_stddev                -0.6226         -0.6221            47            18            47            18
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_cv                    -0.5117         -0.5111             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_mean                  -0.1595         -0.1596          3535          2971          3529          2966
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_median                -0.1579         -0.1579          3541          2982          3536          2977
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_stddev                +0.4533         +0.4506            15            22            15            22
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_cv                    +0.7292         +0.7259             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_mean                  -0.1596         -0.1596          3535          2971          3529          2966
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_median                -0.1580         -0.1580          3541          2982          3536          2977
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_stddev                +0.4448         +0.4458            15            22            15            22
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_cv                    +0.7192         +0.7204             0             0             0             0
OVERALL_GEOMEAN                                                                   -0.0602         -0.0602             0             0             0             0

A53:

Comparing png_decode/ (from ./benchmark_zlib_apps_reference) to png_decode/ (from ./benchmark_zlib_apps)
Benchmark                                                                            Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_pvalue                 0.0022          0.0022      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_mean                  -0.0025         -0.0026          6009          5994          5990          5975
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_median                -0.0019         -0.0019          6002          5991          5984          5972
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_stddev                -0.0557         -0.0501            14            13            14            13
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]0_cv                    -0.0533         -0.0477             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_pvalue                 0.1405          0.1620      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_mean                  -0.0013         -0.0013          4291          4285          4277          4271
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_median                -0.0014         -0.0013          4291          4285          4276          4271
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_stddev                -0.1774         -0.1671             8             6             8             6
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]1_cv                    -0.1763         -0.1660             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_pvalue                 0.4274          0.5205      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_mean                  -0.0011         -0.0011          4343          4339          4329          4324
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_median                -0.0013         -0.0012          4343          4338          4329          4324
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_stddev                +0.4617         +0.4743             6             9             6             9
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]2_cv                    +0.4633         +0.4759             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_mean                  -0.0121         -0.0121          4362          4309          4348          4295
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_median                -0.0121         -0.0120          4363          4310          4348          4296
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_stddev                +0.5782         +0.5721             6             9             6             9
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]3_cv                    +0.5976         +0.5914             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_pvalue                 0.3847          0.4274      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_mean                  -0.0006         -0.0006          4181          4178          4167          4164
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_median                -0.0001         -0.0000          4179          4179          4165          4165
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_stddev                -0.1768         -0.1950             7             6             7             6
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]4_cv                    -0.1763         -0.1945             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_mean                  -0.0225         -0.0225          4416          4317          4402          4303
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_median                -0.0223         -0.0223          4415          4317          4401          4303
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_stddev                +0.1259         +0.1598             3             3             3             3
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]5_cv                    +0.1518         +0.1864             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_pvalue                 0.0211          0.0211      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_mean                  -0.0036         -0.0036          4226          4211          4212          4197
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_median                -0.0047         -0.0047          4226          4206          4212          4192
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_stddev                +1.4248         +1.4739             5            12             5            12
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]6_cv                    +1.4336         +1.4828             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_mean                  -0.2148         -0.2148          5865          4605          5846          4590
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_median                -0.2147         -0.2147          5863          4604          5844          4589
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_stddev                -0.3524         -0.3295             5             3             5             4
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]7_cv                    -0.1753         -0.1460             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_mean                  -0.2030         -0.2030          5636          4491          5617          4477
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_median                -0.2027         -0.2027          5634          4492          5616          4478
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_stddev                -0.2188         -0.2062             6             4             6             5
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]8_cv                    -0.0198         -0.0039             0             0             0             0
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_mean                  -0.2028         -0.2028          5634          4491          5616          4477
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_median                -0.2026         -0.2026          5632          4491          5614          4476
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_stddev                +0.7465         +0.7333             4             6             4             6
[png_decode/ vs. png_decode/][png_decode/ vs. png_decode/]9_cv                    +1.1907         +1.1742             0             0             0             0
OVERALL_GEOMEAN                                                                   -0.0713         -0.0713             0             0             0             0
```

**Comment by KungFuJesus** [comment]
Ah crap, apparently that instruction is A64 only.  Do we have a portable way such as a compiler macro to determine if we're compiling on A32 versus A64?

**Comment by KungFuJesus** [comment]
Ok, I believe that fixed it.  Now all the API compatibility checks are failing due to the merged PR with the braid tables.  Is there something we can do to fix those CIs?

**Comment by nmoinvaz** [comment]
Yes it is already fixed in #1276.

**Comment by KungFuJesus** [comment]
> Yes it is already fixed in #1276.

Ok cool. Is it expected that only a few of those tests fail the abicheck and not all of them?

**Comment by nmoinvaz** [comment]
It looks like only the Ubuntu tests fail. On macOS we don't do a certain check which is why it doesn't fail. If you were to rebase on top of that PR it should light up all green or you could just wait until it is merged. 😊

**Comment by KungFuJesus** [comment]
Rebased on top of develop for the sake of CI, hopefully this'll be basically all green soon.

**Comment by KungFuJesus** [comment]
Hmm, looks like the one failing check is due to a failing upload to codecov.  We can probably ignore that one for now.

**Review by Dead2 — APPROVED** [review]
LGTM

**Review by mtl1979 — APPROVED** [review]
LGTM

**Pull request merged**
