### PR TITLE
CI updates for codecov & wine

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by Dead2** [comment]
Huh, what happened to codecov? None of the recent PRs have codecov reports (Neither comment or the "CI" check enties)..

**Comment by mtl1979** [comment]
@Dead2 It got rate-limited... Too many PRs and commits in too short time...

**Review by mtl1979 — APPROVED** [review]
LGTM... Might shorten execution time for specific jobs.

**Comment by nmoinvaz** [comment]
My last commit makes it so it doesn't install codecov package when unsuccessful build... it waits for success to install it.

**Comment by nmoinvaz** [comment]
@Dead2 I think @mtl1979 is right because I am still seeing code coverage files being uploaded to Codecov in the CI. We may at some point need to upgrade to use codecov's new node uploader.

**Comment by nmoinvaz** [comment]
After this PR is merged, I will create another one with changes for upgrading to using Codecov's GitHub Actions action which uses the new codecov uploader. From my basic tests it is pretty fast.

**Review by Dead2 — APPROVED** [review]
LGTM

**Comment by Dead2** [comment]
I rather think codecov is broken, again.
All the PR statistics are still available from the codecov website, just no comments or CI checks are added.

**Comment by mtl1979** [comment]
It doesn't really matter if codecov is broken or not. We can't fix stupid, we can only work around any limitations.

**Pull request merged**
