### PR TITLE
Minor CMake and benchmark fixes

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by KungFuJesus** [comment]
Well if this gets merged first my rebase makes the benchmark fix for my arm improvement get eliminated entirely, hah.

**Comment by nmoinvaz** [comment]
I thought I had seen that fix somewhere else. But when I didn't see anything change after rebasing I figured it still needed to be fixed.

**Review by Dead2 — APPROVED** [review]
LGTM

**Review by mtl1979 — APPROVED** [review]
LGTM.

**Comment by Dead2** [comment]
Still LGTM

**Comment by nmoinvaz** [comment]
I'm ready. If I have more stuff I can just open another PR.

**Review by mtl1979 — APPROVED** [review]
Still LGTM.

**Pull request merged**
