### PR TITLE
Separate slide_hash_c similar to insert_string_c.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Review by Dead2 — APPROVED** [review]
LGTM, needs a rebase though

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by mtl1979** [comment]
Fails CI, most likely needs rebase again. Otherwise looks good to me...

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by Dead2** [comment]
Not sure whether CI fails because of this PR or something else, but there are 2 different types of failures
```
In file included from /home/runner/work/zlib-ng/zlib-ng/functable.h:9,
                 from /home/runner/work/zlib-ng/zlib-ng/adler32.c:8:
/home/runner/work/zlib-ng/zlib-ng/deflate.h:68: error: "HASH_SIZE" redefined [-Werror]
   68 | #define HASH_SIZE 65536u           /* number of elements in hash table */
```

Also pkgcheck fails with what appears to me like a different base memory address than before.

**Comment by nmoinvaz** [comment]
I think that is from the old rebase. I can rebase again.

**Comment by nmoinvaz** [comment]
Rebased.

**Review by mtl1979 — APPROVED** [review]
LGTM

**Pull request merged**
