### PR TITLE
Rename x86 source files with instruction set version.

### PR DESCRIPTION
**Pull request by nmoinvaz**
This should make things a bit clearer when reviewing build scripts.

I fully expect to rebase if other PRs are merged ahead of this one.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Rebased.

**Review by Dead2 — APPROVED** [review]
LGTM

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by nmoinvaz** [comment]
@Dead2 any chance on getting this merged soon?

**Pull request merged**
