### PR TITLE
ENH: Transition to Ubuntu 18.04 in `GitHub` actions workflows

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transition to Ubuntu 18.04 in `GitHub` actions workflows.

Fixes:
```
Ubuntu 16.04 Clang
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.

Ubuntu 16.04 GCC
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```

reported for example at:
https://github.com/zlib-ng/zlib-ng/actions/runs/1326434358

Official `GitHub` notice related to the removal of the 16.04 virtual
environments:
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Cross-referencing https://github.com/zlib-ng/zlib-ng/pull/1048#issuecomment-942302273.

**Comment by jhlegarreta** [comment]
The targeted tests are passing; `macOS` failures are unrelated:
```
Error: Could not find Xcode version that satisfied version spec: '12.1.1'
```

e.g.
https://github.com/zlib-ng/zlib-ng/pull/1051/checks?check_run_id=3883700644#step:5:16

**Review by mtl1979 — APPROVED** [review]
LGTM

**Review by dzenanz — APPROVED** [review]
Thanks for fixing this Jon!

**Comment by Dead2** [comment]
Thanks :)

**Pull request merged**
