### PR TITLE
Fixed running fuzzers with cmake on arm.

### PR DESCRIPTION
**Pull request by nmoinvaz**
See #426.

### CODE REVIEW

**Comment by Dead2** [comment]
Looks great!  Crossing fingers that this fixes them all :)

**Comment by Dead2** [comment]
It failed, since it needed the `configure_test_executable(${FUZZER}_fuzzer)`, but don't worry, I put that into my PR.

**Comment by nmoinvaz** [comment]
I must have mistakenly taken that out. Thanks.

**Comment by nmoinvaz** [comment]
But it looks like it didn't get into the `develop` merge: https://github.com/zlib-ng/zlib-ng/commit/852dad9de9c77251d6623785ed9e1974a3e79e8f

**Comment by nmoinvaz** [comment]
Ah nevermind I reread you put it into your PR. I am not a good reader.

**Pull request merged**
