### PR TITLE
longest_match: avoid using negative indices

### LINKED ISSUE #364: Segfault in longest_match after switching compression levels
This is the issue for the finding described in https://github.com/zlib-ng/zlib-ng/pull/340#issuecomment-498637739.

Proposed solution is described in https://github.com/zlib-ng/zlib-ng/pull/340#issuecomment-498640486 - it could not be fully regtested back then due to https://github.com/zlib-ng/zlib-ng/issues/361.

I plan to create a separate testcase (I think that hitting it in the slightly modified `test/example.c` was a coincidence and should not be relied on) and send a pull request.

### PR DESCRIPTION
**Pull request by iii-i**
Fixes #364

### CODE REVIEW

**Comment by mtl1979** [comment]
Path to libz.a in rule for switchlevels is incorrect...

**Comment by iii-i** [comment]
I've parameterized the test `Makefile.in` with `LIBNAME`, so that it's now compatible with both zlib and zlib-ng.

**Comment by iii-i** [comment]
The Travis build has failed due to initialization timeouts and network connectivity problems. I've pushed a no-op change to retrigger the build.

**Comment by iii-i** [comment]
Fixed a sign-compare warning.

**Comment by iii-i** [comment]
Rebased.

**Comment by Dead2** [comment]
Looks good, thanks :)

**Pull request merged**
