### PR TITLE
Improve sse41 adler32 performance

### PR DESCRIPTION
**Pull request by KungFuJesus**
Rather than doing opportunistic aligned loads, we can do scalar
unaligned loads into our two halves of the checksum until we hit
alignment.  Then, we can subtract from the max number of sums for the
first run through the loop.

This allows us to force aligned loads for unaligned buffers (likely a
common case for arbitrary runs of memory). This is not meaningful after
Nehalem but pre-Nehalem architectures it makes a substantial difference
to performance and is more foolproof than hoping for an aligned buffer.

### CODE REVIEW

**Comment by KungFuJesus** [comment]
This makes zero difference for the aligned buffers used in the benchmark, however if we alter the alignment to be unaligned with the worst possible alignment (modulo 15), here's the timing differences:

```
Comparing adler32/sse41 (from ./benchmark_zlib_old) to adler32/sse41 (from ./benchmark_zlib)
Benchmark                                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3534         -0.3535           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3530         -0.3531           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3531         -0.3533           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3532         -0.3532           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3531         -0.3532           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3532         -0.3532           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3528         -0.3530           438           284           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3525         -0.3527           438           284           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3530         -0.3531           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048                          -0.3528         -0.3530           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/2048_mean                     -0.3530         -0.3531           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048_median                   -0.3531         -0.3532           438           283           438           283
[adler32/sse41 vs. adler32/sse41]/2048_stddev                   +2.4114         +2.3335             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/2048_cv                       +4.2727         +4.1532             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4069         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4071         -0.4072           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4071         -0.4072           906           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096                          -0.4071         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/4096_mean                     -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096_median                   -0.4070         -0.4071           905           537           905           537
[adler32/sse41 vs. adler32/sse41]/4096_stddev                   -0.3869         -0.4729             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/4096_cv                       +0.0339         -0.1110             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4214         -0.4215          7228          4182          7225          4179
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4215         -0.4215          7227          4181          7225          4179
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4209         -0.4212          7227          4185          7225          4182
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4209         -0.4212          7227          4185          7224          4181
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4196         -0.4200          7221          4191          7219          4187
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4211         -0.4212          7223          4181          7220          4179
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4210         -0.4212          7223          4182          7221          4180
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4211         -0.4212          7223          4182          7221          4180
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4210         -0.4211          7223          4182          7220          4180
[adler32/sse41 vs. adler32/sse41]/32768                         -0.4210         -0.4211          7223          4182          7220          4180
[adler32/sse41 vs. adler32/sse41]/32768_pvalue                   0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/32768_mean                    -0.4210         -0.4211          7225          4183          7222          4181
[adler32/sse41 vs. adler32/sse41]/32768_median                  -0.4211         -0.4212          7223          4182          7221          4180
[adler32/sse41 vs. adler32/sse41]/32768_stddev                  +0.2961         +0.0142             2             3             2             2
[adler32/sse41 vs. adler32/sse41]/32768_cv                      +1.2384         +0.7521             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4243         -0.4244         58082         33439         58063         33420
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4243         -0.4244         58079         33437         58061         33419
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4243         -0.4244         58087         33440         58064         33419
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4243         -0.4244         58078         33438         58058         33420
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4240         -0.4242         58066         33444         58046         33424
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4243         -0.4244         58079         33437         58060         33420
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4241         -0.4242         58061         33437         58042         33420
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4242         -0.4244         58079         33441         58059         33421
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4244         -0.4245         58089         33436         58068         33419
[adler32/sse41 vs. adler32/sse41]/262144                        -0.4244         -0.4245         58081         33434         58064         33418
[adler32/sse41 vs. adler32/sse41]/262144_pvalue                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/262144_mean                   -0.4243         -0.4244         58078         33438         58059         33420
[adler32/sse41 vs. adler32/sse41]/262144_median                 -0.4243         -0.4244         58079         33438         58060         33420
[adler32/sse41 vs. adler32/sse41]/262144_stddev                 -0.6837         -0.7735             9             3             8             2
[adler32/sse41 vs. adler32/sse41]/262144_cv                     -0.4507         -0.6065             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4211         -0.4212        464328        268788        464170        268661
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4209         -0.4210        464199        268818        464030        268664
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4214         -0.4215        464477        268724        464272        268593
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4219         -0.4216        464278        268399        464040        268397
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4221         -0.4218        464380        268365        464119        268363
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4222         -0.4219        464477        268368        464241        268366
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4223         -0.4220        464516        268364        464273        268363
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4222         -0.4219        464494        268379        464229        268377
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4224         -0.4220        464598        268369        464305        268368
[adler32/sse41 vs. adler32/sse41]/2097152                       -0.4213         -0.4213        463757        268359        463747        268357
[adler32/sse41 vs. adler32/sse41]/2097152_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/2097152_mean                  -0.4218         -0.4216        464350        268493        464142        268451
[adler32/sse41 vs. adler32/sse41]/2097152_median                -0.4221         -0.4219        464428        268374        464199        268372
[adler32/sse41 vs. adler32/sse41]/2097152_stddev                -0.1826         -0.2224           241           197           170           132
[adler32/sse41 vs. adler32/sse41]/2097152_cv                    +0.4137         +0.3445             0             0             0             0
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4223         -0.4223        926693        535317        926682        535308
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4232         -0.4228        927986        535300        927338        535287
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4230         -0.4228        927853        535349        927522        535346
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4232         -0.4230        927840        535206        927532        535201
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4231         -0.4229        927775        535201        927427        535197
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4232         -0.4230        927938        535256        927575        535253
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4234         -0.4231        928184        535186        927693        535183
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4233         -0.4230        928053        535232        927550        535228
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4233         -0.4230        928016        535221        927530        535217
[adler32/sse41 vs. adler32/sse41]/4194304                       -0.4232         -0.4229        927947        535286        927459        535282
[adler32/sse41 vs. adler32/sse41]/4194304_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/sse41 vs. adler32/sse41]/4194304_mean                  -0.4231         -0.4229        927829        535255        927431        535250
[adler32/sse41 vs. adler32/sse41]/4194304_median                -0.4232         -0.4229        927942        535244        927526        535241
[adler32/sse41 vs. adler32/sse41]/4194304_stddev                -0.8671         -0.8066           416            55           279            54
[adler32/sse41 vs. adler32/sse41]/4194304_cv                    -0.7695         -0.6649             0             0             0             0
OVERALL_GEOMEAN                                                 -0.4090         -0.4089             0             0             0             0
```

**Comment by KungFuJesus** [comment]
Oh duh, I see the issue here, hah. Should have a fix shortly.

**Comment by KungFuJesus** [comment]
Sorry for all the whitespace changes - I fixed that while we were there.  Though, my last force push doesn't seem to have triggered CI...

**Comment by nmoinvaz** [comment]
GitHub Actions has been having degraded performance which is why your CI has not been running. https://www.githubstatus.com/history

**Comment by KungFuJesus** [comment]
Hmm, wonder why LGTM check is using a stricter dialect of C than the defaults.  Usually you can jump to a label as long as you don't jump over a declaration.  Oh well, I can declare the variables prior to the jump, I guess.

**Comment by Dead2** [comment]
Xeon E5-2650, x86-64, GCC 4.8
 
## Baseline ab6665b1bee170c27d229899ed23e6053ebd900b GCC4.8 SSE2, SSSE3, SSE4 and PCLMULQDQ
```
 Tool: minideflate Levels: 0-9
 Runs: 40         Trim worst: 20

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.003/0.014/0.018/0.004        0.003/0.016/0.020/0.005       15,738,731
 1     54.159%      0.243/0.253/0.261/0.005        0.105/0.125/0.130/0.006        8,522,662
 2     43.870%      0.444/0.461/0.466/0.005        0.120/0.127/0.133/0.004        6,903,597
 3     42.387%      0.574/0.582/0.591/0.005        0.117/0.125/0.130/0.004        6,670,087
 4     41.647%      0.624/0.641/0.649/0.008        0.105/0.121/0.128/0.005        6,553,711
 5     41.226%      0.694/0.702/0.709/0.005        0.107/0.120/0.124/0.005        6,487,406
 6     41.044%      0.775/0.789/0.798/0.007        0.103/0.115/0.122/0.005        6,458,769
 7     40.778%      0.976/1.001/1.009/0.008        0.107/0.115/0.121/0.004        6,416,907
 8     40.703%      1.207/1.219/1.229/0.005        0.101/0.118/0.124/0.006        6,405,232
 9     40.409%      1.398/1.413/1.421/0.007        0.112/0.123/0.127/0.004        6,358,939

 avg1  48.624%                        0.707                          0.110
 avg2  54.026%                        0.786                          0.123
 tot                                141.499                         22.090       76,516,041

   text    data     bss     dec     hex filename
 125031    1456      48  126535   1ee47 libz-ng.so.2
 ```
 
## PR #1157 946a0afe5adc0bb32b350484aef640487c36e13d GCC4.8 SSE2, SSSE3, SSE4 and PCLMULQDQ
```
 Tool: minideflate Levels: 0-9
 Runs: 40         Trim worst: 20

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.007/0.012/0.014/0.002        0.006/0.016/0.021/0.004       15,738,731
 1     54.159%      0.248/0.257/0.263/0.005        0.111/0.123/0.130/0.005        8,522,662
 2     43.870%      0.450/0.463/0.471/0.006        0.115/0.128/0.134/0.005        6,903,597
 3     42.387%      0.581/0.589/0.597/0.005        0.115/0.127/0.131/0.005        6,670,087
 4     41.647%      0.632/0.642/0.650/0.005        0.106/0.122/0.126/0.005        6,553,711
 5     41.226%      0.685/0.702/0.709/0.006        0.105/0.120/0.128/0.006        6,487,406
 6     41.044%      0.759/0.784/0.793/0.009        0.107/0.117/0.123/0.005        6,458,769
 7     40.778%      0.979/0.999/1.010/0.010        0.100/0.117/0.122/0.006        6,416,907
 8     40.703%      1.195/1.213/1.223/0.008        0.105/0.118/0.125/0.005        6,405,232
 9     40.409%      1.402/1.418/1.426/0.006        0.110/0.121/0.126/0.005        6,358,939

 avg1  48.624%                        0.708                          0.111
 avg2  54.026%                        0.787                          0.123
 tot                                141.586                         22.169       76,516,041

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.003/0.014/0.017/0.003        0.013/0.017/0.021/0.003       15,738,731
 1     54.159%      0.237/0.254/0.264/0.008        0.110/0.125/0.130/0.005        8,522,662
 2     43.870%      0.455/0.463/0.470/0.004        0.117/0.127/0.134/0.005        6,903,597
 3     42.387%      0.578/0.588/0.594/0.004        0.114/0.125/0.131/0.005        6,670,087
 4     41.647%      0.626/0.640/0.647/0.006        0.105/0.123/0.129/0.006        6,553,711
 5     41.226%      0.686/0.697/0.703/0.005        0.104/0.122/0.128/0.007        6,487,406
 6     41.044%      0.779/0.786/0.793/0.004        0.101/0.118/0.123/0.004        6,458,769
 7     40.778%      0.985/1.002/1.012/0.008        0.101/0.115/0.122/0.006        6,416,907
 8     40.703%      1.194/1.206/1.219/0.007        0.105/0.116/0.121/0.004        6,405,232
 9     40.409%      1.399/1.415/1.423/0.006        0.116/0.122/0.126/0.004        6,358,939

 avg1  48.624%                        0.707                          0.111
 avg2  54.026%                        0.785                          0.123
 tot                                141.308                         22.216       76,516,041

   text    data     bss     dec     hex filename
 124967    1456      48  126471   1ee07 libz-ng.so.2
```

No significant changes in performance detected.
Slight decrease in text size 👍

**Review by Dead2 — APPROVED** [review]

**Comment by KungFuJesus** [comment]
@Dead2 just pushed another optimization onto this in a separate commit, feel free to check it out.

**Comment by Dead2** [comment]
Xeon E5-2650, x86-64, GCC 4.8
Only SSE2, SSSE3, SSE4 and PCLMULQDQ enabled
 
## Baseline 321028cde93dac9f47b9b92ad186c4cbffb77cf2
```
 Tool: minideflate Levels: 0-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.006/0.012/0.017/0.003        0.007/0.016/0.020/0.003       15,738,731
 1     54.159%      0.231/0.250/0.257/0.006        0.113/0.123/0.129/0.004        8,522,662
 2     43.870%      0.442/0.456/0.461/0.005        0.110/0.126/0.133/0.007        6,903,597
 3     42.387%      0.555/0.570/0.577/0.005        0.111/0.124/0.130/0.006        6,670,087
 4     41.647%      0.607/0.623/0.630/0.006        0.102/0.120/0.125/0.005        6,553,711
 5     41.226%      0.682/0.691/0.698/0.005        0.100/0.116/0.124/0.005        6,487,406
 6     41.044%      0.762/0.776/0.782/0.004        0.108/0.117/0.122/0.004        6,458,769
 7     40.778%      0.983/1.009/1.019/0.008        0.108/0.115/0.119/0.003        6,416,907
 8     40.703%      1.204/1.222/1.229/0.006        0.101/0.115/0.121/0.005        6,405,232
 9     40.409%      1.332/1.354/1.363/0.008        0.108/0.121/0.126/0.004        6,358,939

 avg1  48.624%                        0.696                          0.109
 avg2  54.026%                        0.774                          0.121
 tot                                208.920                         32.774       76,516,041

   text    data     bss     dec     hex filename
 125287    1456      48  126791   1ef47 libz-ng.so.2

------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
adler32/c/2048                       828 ns          828 ns       845490
adler32/c/4096                      1651 ns         1651 ns       423839
adler32/c/32768                    13178 ns        13178 ns        53042
adler32/c/262144                  105602 ns       105603 ns         6633
adler32/c/2097152                 848679 ns       848593 ns          826
adler32/c/4194304                1698822 ns      1698592 ns          412
adler32/ssse3/2048                   354 ns          354 ns      1974996
adler32/ssse3/4096                   649 ns          649 ns      1078249
adler32/ssse3/32768                 4899 ns         4899 ns       142852
adler32/ssse3/262144               39103 ns        39100 ns        17904
adler32/ssse3/2097152             316144 ns       316111 ns         2215
adler32/ssse3/4194304             635702 ns       635629 ns         1100
adler32/sse41/2048                   255 ns          255 ns      2745638
adler32/sse41/4096                   488 ns          488 ns      1434681
adler32/sse41/32768                 3842 ns         3842 ns       182188
adler32/sse41/262144               30927 ns        30925 ns        22634
adler32/sse41/2097152             251083 ns       251068 ns         2787
adler32/sse41/4194304             505690 ns       505635 ns         1384
```

## PR #1157 3ad0a3513112ca4faa857177e5ba578400578ef9 (first commit)
```
 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.003/0.012/0.016/0.003        0.006/0.017/0.021/0.003       15,738,731
 1     54.159%      0.238/0.251/0.256/0.005        0.114/0.121/0.127/0.004        8,522,662
 2     43.870%      0.440/0.456/0.461/0.004        0.120/0.127/0.134/0.004        6,903,597
 3     42.387%      0.547/0.568/0.576/0.007        0.114/0.127/0.131/0.005        6,670,087
 4     41.647%      0.603/0.625/0.633/0.007        0.110/0.120/0.126/0.004        6,553,711
 5     41.226%      0.669/0.682/0.690/0.006        0.091/0.118/0.125/0.007        6,487,406
 6     41.044%      0.758/0.767/0.773/0.004        0.110/0.117/0.123/0.003        6,458,769
 7     40.778%      0.980/1.010/1.019/0.008        0.106/0.116/0.121/0.005        6,416,907
 8     40.703%      1.189/1.220/1.228/0.007        0.104/0.115/0.121/0.005        6,405,232
 9     40.409%      1.332/1.350/1.361/0.008        0.106/0.120/0.125/0.004        6,358,939

 avg1  48.624%                        0.694                          0.110
 avg2  54.026%                        0.771                          0.122
 tot                                208.219                         32.905       76,516,041

   text    data     bss     dec     hex filename
 125223    1456      48  126727   1ef07 libz-ng.so.2

------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
adler32/sse41/2048                   279 ns          279 ns      2505649
adler32/sse41/4096                   530 ns          530 ns      1320799
adler32/sse41/32768                 4210 ns         4210 ns       166404
adler32/sse41/262144               33884 ns        33882 ns        20652
adler32/sse41/2097152             273605 ns       273586 ns         2558
adler32/sse41/4194304             550793 ns       550746 ns         1270
```

## PR #1157 09bb6ff18da764c3f4d0c1acc7ce20c33282aa90 (first+second commit)
```
 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.015%      0.006/0.013/0.016/0.002        0.003/0.013/0.019/0.003       15,738,731
 1     54.159%      0.233/0.249/0.255/0.005        0.109/0.123/0.128/0.004        8,522,662
 2     43.870%      0.440/0.454/0.460/0.005        0.113/0.126/0.133/0.006        6,903,597
 3     42.387%      0.543/0.569/0.577/0.007        0.102/0.123/0.128/0.006        6,670,087
 4     41.647%      0.610/0.624/0.631/0.006        0.108/0.120/0.125/0.004        6,553,711
 5     41.226%      0.681/0.691/0.698/0.005        0.107/0.119/0.124/0.005        6,487,406
 6     41.044%      0.767/0.781/0.789/0.006        0.105/0.116/0.124/0.006        6,458,769
 7     40.778%      0.992/1.007/1.013/0.005        0.105/0.115/0.120/0.003        6,416,907
 8     40.703%      1.203/1.223/1.230/0.006        0.100/0.114/0.119/0.005        6,405,232
 9     40.409%      1.341/1.356/1.364/0.007        0.105/0.119/0.125/0.006        6,358,939

 avg1  48.624%                        0.697                          0.109
 avg2  54.026%                        0.774                          0.121
 tot                                208.989                         32.658       76,516,041

   text    data     bss     dec     hex filename
 125415    1456      48  126919   1efc7 libz-ng.so.2

------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
adler32/sse41/2048                   200 ns          200 ns      3503432
adler32/sse41/4096                   374 ns          374 ns      1870807
adler32/sse41/32768                 2943 ns         2943 ns       237816
adler32/sse41/262144               24464 ns        24462 ns        28617
adler32/sse41/2097152             199723 ns       199704 ns         3503
adler32/sse41/4194304             403131 ns       403082 ns         1737
```

The first commit is not doing so well. The second commit seems to do a lot better.

Compiled code size is up a tiny bit.
Compression time is too close to tell either way.
Decompression time seems a little faster, especially noticeable in level 0.
adler32 benchmark looks a lot better with the last commit, seems to be about 20% faster than develop on this cpu+compiler.

**Comment by nmoinvaz** [comment]
It's unlikely you'd see any performance improvement in minigzip because gzip uses crc32. While the zlib format uses adler32, so you can use minideflate with `-w -15`.

**Comment by Dead2** [comment]
@nmoinvaz the above post says I used minideflate for the benchmarks, am I missing something?

**Comment by nmoinvaz** [comment]
My bad. I think it only mentioned it in the first results, so I looked at the other two commit results and assumed it was minigzip.

**Comment by nmoinvaz** [comment]
Did you use `-w -15` argument? Perhaps deflatebench should also print out what arguments were used with the testtool. Or we could make minideflate default to use zlib algorithm.

**Comment by Dead2** [comment]
@nmoinvaz I thought minideflate always used adler, doesn't it? Or is it outputting raw deflate stream perhaps.. I didn't consider that.

Maybe add an option to minideflate to easily switch between them? Default to zlib and ´--raw-deflate´ or something to output just the raw stream?

**Comment by KungFuJesus** [comment]
It's worth noting that adler checksums are a pretty small portion of the deflate process, especially on a smaller dataset.  I believe the adler checksum is run on the pre-compressed and post-decompressed data, so a smaller sample will be affected less by this than a larger one.

If you try a larger canonical dataset you'll probably measure a bigger gain.  Though, I believe the gain is likely to be pretty uniform across the board for all compression levels.  In theory larger chunks at a time run through the checksum will do better.  So, you might see marginally better gains with something that tried to run larger windows of the data into the function at once.

**Comment by nmoinvaz** [comment]
No it doesn't by default. You have to specify the correct window_bits. Values greater than 0 are gzip and values less than 0 are zlib. It used 15 by default so gzip.

I think if we default it to use zlib it will be better because we already have a tool (minigzip) that defaults to gzip.

Not sure about adding those additional flags - they would just be shortcuts. Let me think about it.

Sorry man. :( At least this explains why we are not seeing improvements in those results.

**Comment by KungFuJesus** [comment]
Oh and PNG encoding and decode are _definitely_ affected by this and for sure turn on the adler checksums.  See #1170

**Comment by KungFuJesus** [comment]
> Compiled code size is up a tiny bit.

Hah, I have a change pending I can probably put in another PR to remedy that.  Essentially, the SSE41 method actually only uses SSSE3 instructions.  I had been confusing the sum of absolute difference instruction with a weirder sum of absolute difference instruction that was introduced in SSE41 (MPSADBW).

Definitely belongs in a different PR, but we can replace the SSSE3 method entirely with this one.

**Comment by Dead2** [comment]
@nmoinvaz Hmm, if I set window-bits to -15, I get an error -5 (Z_BUF_ERROR) on inflation. Is minideflate not able to inflate zlib streams or is something else wrong here?

**Comment by nmoinvaz** [comment]
@Dead2 something else might be going on.

**Comment by Dead2** [comment]
I did this, am I missing something?
```
# ./minideflate -w -15 testfil -c > testfil.z
# ./minideflate -d testfil.z
inflate error: -5

Also tried:
# ./minideflate -w 15 -d testfil.z
inflate error: -5
```

I get the same result on both aarch64 and x86-64, so seems to be quite consistent at least.

**Comment by nmoinvaz** [comment]
See PR #1175.

**Pull request merged**
