### PR TITLE
[PowerPC] Default CPU to 7400 to enable VMX support in qemu-ppc

### PR DESCRIPTION
**Pull request by mtl1979**
Increases coverage of arch/power/adler32_vmx.c from 0% to 88%...

### CODE REVIEW

**Comment by mtl1979** [comment]
@nmoinvaz @KungFuJesus @Dead2

**Comment by KungFuJesus** [comment]
Hah, fantastic.  I definitely thought I remembered them having altivec support.  @nmoinvaz does this have any affect on the google test stuff?

**Comment by mtl1979** [comment]
@KungFuJesus Should make reviewing future pull requests much easier as now we can see if some code paths don't get executed... I don't know why qemu-ppc defaults to CPU without VMX.

**Review by nmoinvaz — APPROVED** [review]

**Comment by nmoinvaz** [comment]
@mtl1979 where are the argument values documented for qemu-ppc on the internet? I am having a hard time seeing what cpu7400 is equal to.

**Comment by mtl1979** [comment]
@nmoinvaz I couldn't find any online documentation for qemu-ppc, so I did just run `qemu-ppc -cpu help`.

**Comment by KungFuJesus** [comment]
The 7400 and 7450s were models of apple G4s. I think the 7450 was used in newer powerbooks.

**Comment by mtl1979** [comment]
PowerPC 7400 series was the first that introduced VMX and in my opinion as such good candidate when testing VMX on qemu.

**Pull request merged**
