### PR TITLE
Add 'diffoscope' for MacOS in pkgcheck.yml

### PR DESCRIPTION
**Pull request by mtl1979**
Add missing brew package on MacOS for 'diffoscope'.
Disable ABI check for MacOS as the runner doesn't contain abigail.

### CODE REVIEW

**Comment by mtl1979** [comment]
Seems like we should disable abicheck for MacOS as there is no abigail for MacOS...

**Comment by nmoinvaz** [comment]
I'm ok with just testing it on just one platform. @dankegel thoughts?

**Comment by dankegel** [comment]
Well, this is kind of an argument for splitting it out into its own yml; you could also skip abicheck on mac with a conditional.

It would make me uncomfortable to not run pkgcheck.sh on mac...

**Comment by mtl1979** [comment]
I'm not sure if we should or shouldn't make another pull request to fix the issue with abicheck. I already did split this to two pull requests just for pkgcheck.

**Comment by nmoinvaz** [comment]
Add if statement to yaml to check for macOS.
```
- name: Check ABI
   # macOS does not contain abigail
   if: runner.os != 'macOS'
...
- name: Check ABI (compat)
   # macOS does not contain abigail
   if: runner.os != 'macOS'
```

**Comment by mtl1979** [comment]
@nmoinvaz Done...

**Comment by nmoinvaz** [comment]
Perhaps in the future we can change ABI check to use this project: https://github.com/lvc/abi-compliance-checker which supports macOS, Windows, and Linux. @dankegel

**Comment by dankegel** [comment]
Why would you want to switch away from libabigail?

Looks like gnutls switched *to* libabigail recently:
https://gitlab.com/gnutls/gnutls/-/merge_requests/972

**Comment by mtl1979** [comment]
@dankegel obviously because the MacOS runner in GitHub doesn't have abigail.

**Comment by dankegel** [comment]
Guess I wasn't paying attention.  Sure, should be easy to switch (or maybe use the other tool on the other platforms).

**Comment by mtl1979** [comment]
@dankegel I guess I can leave that for another pull request, now pkgcheck at least works on MacOS.

**Comment by mtl1979** [comment]
codecov seems stuck, but I think this is ready for merging when @dead2 has time...

**Pull request merged**
