### PR TITLE
cmake: CPack enable

### PR DESCRIPTION
**Pull request by scivision**
CPack only works with relative install() paths.
This ignores the absolute paths in cache.

It may be that the absolute paths aren't needed anymore since this is built into CMake, unless custom install methods are needed (different absolute prefix for different artifacts).

With CPack, source and binary archives are easily generated from the build directory:

```sh
cpack
```

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Should this be incorporated into `release.yaml`?

**Comment by scivision** [comment]
Yes I think CPack would simplify the release.yml. The yaml would just upload the single .zip file (or other archive formats) CPack would create.

**Comment by Dead2** [comment]
Unfortunately this would break for example rpm spec files that already specify *_INSTALL_DIR, for example `BIN_INSTALL_DIR`. Especially redhat and derivatives use this in its macros, and the current names were chosen to be compatible. Maybe add some parsing of the possible input variables as well?

**Comment by mtl1979** [comment]
> Unfortunately this would break for example rpm spec files that already specify *_INSTALL_DIR, for example `BIN_INSTALL_DIR`. Especially redhat and derivatives use this in its macros, and the current names were chosen to be compatible. Maybe add some parsing of the possible input variables as well?

We could easily enable CPack only if `LIB_INSTALL_DIR` isn't defined... We don't really need to check for other variables as library directory is most likely have a custom/different prefix. Other option would be to check for number of common path components at start of each install directory, but I'm not sure if there is such function in CMake, and then strip the common part.

**Comment by Dead2** [comment]
Merged similar PR #1556

**Pull request closed without merging**
