### PR TITLE
Correct inflate_fast function signature

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
That was done on purpose to prevent having to include zlib.h in functable.h. See the CI build failures for the error. Perhaps you know a better way?

**Comment by pps83** [comment]
I did check that, and I think `zbuild.h` is needed, which is included by deflate.h -> zutil.h -> zbuild.h (as PREFIX3 is defined by zbuild.h). Is there any other header that this depends on?

**Comment by pps83** [comment]
Ah, ok, I see that, `stream` itself needs to be fwd declared. I'll update the PR.

**Comment by pps83** [comment]
image

@nmoinvaz I can update these fwd declarations `#ifdef ZLIB_COMPAT`

**Comment by nmoinvaz** [comment]
That should work.

**Comment by nmoinvaz** [comment]
I wonder if we can do the same with deflate_struct..

**Comment by pps83** [comment]
> deflate_struct

sure we can:

`typedef struct internal_state deflate_state;` 

then, all three includes could be removed, only zbuild.h and stdint would be needed.
but that would be kind of unrelated to the PR, as this one attempts to fix invalid signature.

**Comment by nmoinvaz** [comment]
> but that would be kind of unrelated to the PR

Yes you are right, I gather it might end up being more involved.

**Comment by nmoinvaz** [comment]
Build failures again.
```c
/home/actions-runner/_work/zlib-ng/zlib-ng/zbuild.h:85:22: error: unknown type name 'z_stream'
   85 | #  define PREFIX3(x) z_ ## x
      |                      ^~
/home/actions-runner/_work/zlib-ng/zlib-ng/cpu_features.h:98:28: note: in expansion of macro 'PREFIX3'
   98 | extern void inflate_fast_c(PREFIX3(stream) *strm, uint32_t start);
```
I think you will need to reference either `zng_stream` or `z_stream` instead of `PREFIX3(stream)...`.

It might be better as you say to use `#ifdef ZLIB_COMPAT` in both places and just hard code `zng_stream` or `z_stream` in inflate_fast declaration.

**Comment by pps83** [comment]
similar update is needed in cpu_features.h, I'll update

**Review by nmoinvaz — APPROVED** [review]
LGTM

**Comment by pps83** [comment]
@Dead2 ^^

**Review by Dead2 — APPROVED** [review]
LGTM

**Pull request merged**
