### PR TITLE
Remove misleading manpage and update README.md.

### PR DESCRIPTION
**Pull request by Dead2**
- Remove misleading manpage.
- Added a related projects section at the end.
- Added blank line after header where missing.
- Added extra blank line before header to make them easier to spot in plain-text mode.
- Changed line-length for Contributing section, to make it more readable as plain-text.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Pkgcheck CI is failing...
Need to remove this from CMakeLists.txt
```
if(NOT SKIP_INSTALL_FILES AND NOT SKIP_INSTALL_ALL)
    install(FILES zlib.3 DESTINATION "${MAN_INSTALL_DIR}/man3" RENAME zlib${SUFFIX}.3)
endif()
```

**Comment by Dead2** [comment]
@nmoinvaz Thanks, completely forgot to add that to the commit.

**Comment by nmoinvaz** [comment]
Configure nows seems to be failing as well..

**Comment by nmoinvaz** [comment]
Makefile.in.. just search for ".3" and you will see all the references.

**Comment by nmoinvaz** [comment]
Also need to remove zlib.3 from INDEX.md.

**Comment by Dead2** [comment]
Configure:
```
# Cleanup these files if building outside source tree
    @if [ ! -f zlib.3 ]; then rm -f zlib.3.pdf Makefile; fi
```
I assume this checks for zlib.3 not existing to mean it is outside the source tree. We'll need a different file to check against, ideas? Maybe just check for `deflate.c` , or perhaps `README.md`?

**Comment by nmoinvaz** [comment]
I think `README.md` would work as a good check.

**Comment by mtl1979** [comment]
The point of the filename is that it only exists in root of zlib source tree, not in any other source tree or build directory.

**Pull request merged**
