### PR TITLE
Fix block_open handling in deflate_quick()

### PR DESCRIPTION
**Pull request by iii-i**
While tracking down #869, I stumbled upon another deflate_quick issue :-(

---

The attached test fails with "inflate() failed", because the deflate
stream that it produces ends up being corrupted. Bisect points to the
commit e7bb6db09a18 ("Replace hash_bits, hash_size and hash_mask with
defines."), but it's most likely a coincidence.

In any case, the reason is that if we happen to simultaneously exhaust
all the buffers (in, out and bi), we return finish_started without
writing the end of block symbol, which will never happen afterwards.

Fix by adding another check to the tricky condition: if we are in the
middle of a block, return need_more instead of finish_started.

### CODE REVIEW

**Comment by Dead2** [comment]
@iii-i Great work on finding this, I'll release a hotfix for this.

Do you have a scripted fuzzing setup that finds these? If so, is it something you can/want to share?
Getting a local fuzzing rig set up has been on my todo ever since we got oss-fuzz in CI, but I have never had the time to read up on it.

**Comment by iii-i** [comment]
Yeah, that's essentially https://github.com/zlib-ng/zlib-ng/commit/08274c765af9d038d5e692dc4024eeaea8313bf6 + some new modifications. I should probably open source the full repo where I develop this, and then we can think whether it would make sense to integrate this into zlib-ng.

**Comment by Dead2** [comment]
@iii-i That looks nice indeed, but as I said I have no experience with fuzzing, so I would not know how to build or run that thing 😄

Getting it into zlib-ng/zlib-ng or perhaps better, a separate zlib-ng/fuzzing (or similar) repo would be great, and would make it easier for everyone to contribute both code and testing.

**Comment by nmoinvaz** [comment]
I am getting these compiler warnings now on `MSVC`:
```
  deflate_quick_block_open.c
C:\Users\Nathan\Source\zlib-ng\test\deflate_quick_block_open.c(62,69): warning C4244: '=': conversion from '__int64' to
 'uint32_t', possible loss of data [C:\Users\Nathan\Source\zlib-ng\deflate_quick_block_open.vcxproj]
C:\Users\Nathan\Source\zlib-ng\test\deflate_quick_block_open.c(73,1): warning C4244: 'initializing': conversion from '_
_int64' to 'uint32_t', possible loss of data [C:\Users\Nathan\Source\zlib-ng\deflate_quick_block_open.vcxproj]
```

**Comment by iii-i** [comment]
Weird that clang and/or gcc didn't catch it. There indeed are a few casts missing in this test. I'll send a PR tomorrow.

**Pull request merged**
