### PR TITLE
Improve Z_NULL compatibility with zlib

### LINKED ISSUE #1733: `Z_NULL` isn't fully compatible with zlib
In zlib, `Z_NULL` is defined as `0` where in zlib-ng it is defined as `NULL`. This can cause type errors.

### PR DESCRIPTION
**Pull request by phprus**
Fix #1733

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]

**Review by mtl1979 — APPROVED** [review]
LGTM... NULL was originally defined only for C++, but later got added to C too... Later C++ compilers use `nullptr` instead, so there is no "compatibility" reason to keep this defined as `NULL`.

**Comment by ac000** [comment]
Of course this is now triggered by `-Wzero-as-null-pointer-constant` (enabled for C in GCC 15, not enabled by either of Wall or Wextra... [_yet_](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117059)).

```
src/http/modules/ngx_http_gunzip_filter_module.c:307:26: error: zero as null pointer constant [-Werror=zero-as-null-pointer-constant]
  307 |     ctx->zstream.next_in = Z_NULL;
      |                          ^
```

**Comment by phprus** [comment]
zlib also declare ``Z_NULL`` macro as ``0``:

https://github.com/madler/zlib/blob/5a82f71ed1dfc0bec044d9702463dbdf84ea3b71/zlib.h#L216

This macro is only for compatibility with zlib.

Use ``NULL`` instead of ``Z_NULL``.

**Comment by ac000** [comment]
I'm thinking of the case where you have a code base that was developed against zlib but may now build with either zlib or zlib-ng-comat as Linux distributions are now switching to...

No biggie... just an unfortunate legacy decision...

**Comment by phprus** [comment]
This change was made because defining the ``Z_NULL`` macro as ``NULL`` broke other legacy code bases :(

There is no reason to use the ``Z_NULL`` macro in the code now. This is zlib-compatibility macro.

**Pull request merged**
