### PR TITLE
Added regression test for zng_deflateEnd -3

### PR DESCRIPTION
**Pull request by nmoinvaz**
This issue adds regression test for zng_deflateEnd -3 return code mention in #382.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Looks like a lot of failures. I recommend merging in #382 first and then reruning travis. The failures are due to -3 in some cases. In other cases it can't find the file. I could change cmake to copy the files it needs after building when `BUILD_TESTS` is enabled. However, I have no plans to change configure script because it is evil.

**Comment by nmoinvaz** [comment]
@cielavenir, it appears that deflateEnd still returns -3 in some instances. I was able to reproduce it with my test file.

**Comment by nmoinvaz** [comment]
Possible fix might be don't emit end block during look ahead check.

```
        if (s->lookahead < MIN_LOOKAHEAD) {
            fill_window_sse(s);
            if (s->lookahead < MIN_LOOKAHEAD && flush == Z_NO_FLUSH) {
                //static_emit_end_block(s, 0);
                return need_more;
            }
            if (s->lookahead == 0)
                break;
        }
```

deflate_fast, deflate_slow, & deflate_medium don't emit any codes in this conditional branch. This still requires @cielavenir's fix.

**Comment by nmoinvaz** [comment]
I spotted an issue with my test i have to take a look at.

**Comment by nmoinvaz** [comment]
I'm not having any luck with deflate using small buffers when using Z_PARTIAL_FLUSH, the output _compr_ buffer fills up and _deflateEnd_ always returns -3. I don't have the same problem with Z_FINISH. However, using test_burn() with Z_FINISH fails. I have committed my changes to example.c if anybody wants to take a look.

**Comment by Dead2** [comment]
But it only fails when using deflate_quick, right?
I suspect someone will have to do a gdb-dive into that code to get this solved.

As a side note; I think that perhaps we should make it more visible what tests fail and what tests succeed in example.c, and let it continue until all tests have run before exiting with an error code. That can let us get more data when it fails, ex: does only one test fail or multiple?
Would also be great to have a way to select/exclude tests, but that is likely a lot more involved.

**Comment by nmoinvaz** [comment]
Yes, it only fails using deflate_quick. I agree that changing the test functions to return an error code would be a good idea to allow further tests to be run.

**Comment by nmoinvaz** [comment]
I think I have run into an issue with _inflate_ using small buffers where the function returns Z_BUF_ERROR when there is no more input, yet there is still output. Here is what I changed:

```
if (((in == 0 && out == 0) || flush == Z_FINISH) && ret == Z_OK)
    return Z_BUF_ERROR;
```

To

```
if (((in == 0 && out == 0) || (out == 0 && flush == Z_FINISH)) && ret == Z_OK)
    return Z_BUF_ERROR;
```
And it only returns Z_BUF_ERROR now if it is Z_FINISH and nothing was output. It would be good to get somebody to review this by itself.

**Comment by Dead2** [comment]
@nmoinvaz That does look a bit strange. Have you check what stock zlib does there? If they do the same, perhaps it is worth opening a PR there and letting madler decide whether the behavior needs to change.

**Comment by nmoinvaz** [comment]
Stock zlib does the same as zlib-ng. I will put together a PR for madler/zlib with sample code and sample input when I have some more time.

**Comment by nmoinvaz** [comment]
See madler/zlib#446

**Comment by nmoinvaz** [comment]
> I'm not having any luck with deflate using small buffers when using Z_PARTIAL_FLUSH, the output compr buffer fills up and deflateEnd always returns -3. I don't have the same problem with Z_FINISH. 

I believe this is normal behavior and maybe my understanding of the different flush modes was incomplete. In my latest test code I am no longer seeing deflateEnd return -3 with quick deflate.

**Comment by nmoinvaz** [comment]
It would be good to get some feedback on example.c changes. Ignore `test_burn()` which I don't plan to include in my final commit but it is very useful.

**Comment by nmoinvaz** [comment]
Sample output from example.c:

```
zlib version 1.9.9 = 0x1990, compile flags = 0x155
compress(): OK
uncompress(): OK
gzread: OK (hello, hello!)
gzgets after gzseek: OK ( hello!)
deflate() hello: OK
inflate() hello: OK (hello, hello!)
deflate() small hello: OK
inflate() small hello: OK (hello, hello!)
large_deflate() 0: OK
large_inflate(): OK
large_deflate() 1: OK
large_inflate(): OK
deflate() full flush: OK
inflateSync(): OK (hello, hello!)
deflate() preset dictionary: OK
inflate() preset dictionary: OK (hello, hello!)
deflateBound(): OK
deflateCopy(): OK
deflateGetDictionary: OK (hello, hello!)
deflateSetHeader(): OK
deflateTune(): OK
deflatePending(): OK
deflatePrime(): OK
inflate() test/data/infbuferr.dat: OK
inflate() test/data/infbuferr.dat small: OK
deflate() test/data/defneg3.dat level 1 mem 1: OK
deflate() test/data/defneg3.dat small level 1 mem 1: OK
inflate() test/data/defneg3.dat: OK
inflate() test/data/defneg3.dat small: OK
deflate() test/data/lcet10.txt level 1 mem 1: OK
deflate() test/data/lcet10.txt small level 1 mem 1: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 1: OK
deflate() test/data/lcet10.txt small level -1 mem 1: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 1: OK
deflate() test/data/lcet10.txt small level 9 mem 1: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 2: OK
deflate() test/data/lcet10.txt small level 1 mem 2: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 2: OK
deflate() test/data/lcet10.txt small level -1 mem 2: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 2: OK
deflate() test/data/lcet10.txt small level 9 mem 2: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 3: OK
deflate() test/data/lcet10.txt small level 1 mem 3: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 3: OK
deflate() test/data/lcet10.txt small level -1 mem 3: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 3: OK
deflate() test/data/lcet10.txt small level 9 mem 3: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 4: OK
deflate() test/data/lcet10.txt small level 1 mem 4: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 4: OK
deflate() test/data/lcet10.txt small level -1 mem 4: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 4: OK
deflate() test/data/lcet10.txt small level 9 mem 4: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 5: OK
deflate() test/data/lcet10.txt small level 1 mem 5: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 5: OK
deflate() test/data/lcet10.txt small level -1 mem 5: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 5: OK
deflate() test/data/lcet10.txt small level 9 mem 5: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 6: OK
deflate() test/data/lcet10.txt small level 1 mem 6: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 6: OK
deflate() test/data/lcet10.txt small level -1 mem 6: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 6: OK
deflate() test/data/lcet10.txt small level 9 mem 6: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 7: OK
deflate() test/data/lcet10.txt small level 1 mem 7: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 7: OK
deflate() test/data/lcet10.txt small level -1 mem 7: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 7: OK
deflate() test/data/lcet10.txt small level 9 mem 7: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 8: OK
deflate() test/data/lcet10.txt small level 1 mem 8: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 8: OK
deflate() test/data/lcet10.txt small level -1 mem 8: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 8: OK
deflate() test/data/lcet10.txt small level 9 mem 8: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 1 mem 9: OK
deflate() test/data/lcet10.txt small level 1 mem 9: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level -1 mem 9: OK
deflate() test/data/lcet10.txt small level -1 mem 9: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
deflate() test/data/lcet10.txt level 9 mem 9: OK
deflate() test/data/lcet10.txt small level 9 mem 9: OK
inflate() test/data/lcet10.txt: OK
inflate() test/data/lcet10.txt small: OK
```

**Comment by nmoinvaz** [comment]
Ok I have made those changes. It looks like GitHub doesn't like showing the change comparison for example.c. Maybe it is a bug in GitHub.

**Comment by Dead2** [comment]
This PR probably needs a bit of a cleanup now.
At least I don't think it was meant to modify inffast.c inflate.c memcopy.h.

The makefile.in changes might be worth making a separate PR for, so it can be pulled before we merge this test (since this test is currently being blocked by the problem not being solved yet).

**Comment by nmoinvaz** [comment]
All the cmake builds are succeeding. Here is a summary of the changes:

- Added test for deflateEnd -3 error code with 2 test artifacts/data
- Converted all tests to return int
- All tests are now run even if one fails
- Changed test printf formatting to be consistent
- Added test functions for deflate/inflate with params (allowing specifying memLevel and others)
- Added test functions for testing deflate/inflate against files

For configure/makefile the example executables will need to be run from the source directory as the working directory. This is so that example and example64 know where to locate the test/data files. Perhaps somebody with more knowledge of makefiles can suggest or make that change.

**Comment by nmoinvaz** [comment]
I decided to go another way with this and break it out into its own test app.

**Pull request closed without merging**
