### PR TITLE
Implement scan-build test inside travis-CI

### PR DESCRIPTION
**Pull request by gdevenyi**
Also upgrades travis to Xenial to get access to LLVM natively in travis.

### CODE REVIEW

**Comment by Dead2** [comment]
I see you are still putting the MAKE="make" at the front instead of last in each line. I think it is much more logical to have it at the end, after configure, since that is after all the order that it gets executed in.

**Comment by gdevenyi** [comment]
Makes sense, will refactor

**Comment by gdevenyi** [comment]
Refactored to put the make command override at the end of line.

**Comment by gdevenyi** [comment]
Any other comments here? Is this a reasonable change?

**Comment by mtl1979** [comment]
I'm not sure it's the best way to define MAKE="make" separately in each target, it should be set as global default and overridden only when necessary...

**Comment by gdevenyi** [comment]
Okay. I can refactor again.

**Comment by gdevenyi** [comment]
Refactor complete.

**Comment by Dead2** [comment]
Looks good to me.
The current travis build shows no bug reports, so what happens if there is a bug?

**Comment by gdevenyi** [comment]
Travis will throw an error on build, and you'll get lines like this:
https://github.com/zlib-ng/zlib-ng/pull/188#issue-208722186

**Comment by Dead2** [comment]
Tanks :)

**Pull request merged**
