### PR TITLE
COMP: Fix data loss warning

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix data loss warning.

Fixes:
```
itkzlib-ng/inflate.c(1209,24): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data
itkzlib-ng/inflate.c(1210,26): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data
```

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Local system: Windows 10
Compiler: MSVC 2019 version 19.29.30133.0

Found when building ITK: https://github.com/InsightSoftwareConsortium/ITK

**Comment by mtl1979** [comment]
Using `unsigned long` instead of `size_t` can cause unwanted truncation as we declare `total_in` and `total_out` as `size_t` in non-compat header. `unsigned long` is only 32 bits under 64-bit Windows, but `size_t` can be either 32 or 64 bits depending on compiler version.

We might want to use explicit cast to `z_size_t` instead on those two lines.

**Comment by jhlegarreta** [comment]
Thanks for the review @mtl1979 .

> We might want to use explicit cast to z_size_t instead on those two lines.

Let me know if you want me to amend the commit that way.

**Comment by mtl1979** [comment]
@jhlegarreta I think using cast is better than changing the type of the temporary variables as that avoids all issues when building the non-compat version, which should be the default version for most developers compiling from sources... "Compat" version still truncates, but that is something we can't fix to stay compatible with stock zlib.

**Comment by jhlegarreta** [comment]
> @jhlegarreta I think using cast is better than changing the type of the temporary variables as that avoids all issues when building the non-compat version, which should be the default version for most developers compiling from sources... "Compat" version still truncates, but that is something we can't fix to stay compatible with stock zlib.

Changed in ad6171d.

**Comment by mtl1979** [comment]
Cast to `unsigned long` is still wrong, it will truncate on non-compat version.

**Comment by jhlegarreta** [comment]
> Cast to unsigned long is still wrong, it will truncate on non-compat version.

My bad; 977a2e5 casts to `z_size_t`. Sorry.

**Review by Dead2 — APPROVED** [review]

**Comment by jhlegarreta** [comment]
Build failures seem unrelated:
```
Error: Could not find Xcode version that satisfied version spec: '12.1.1'
```

https://github.com/zlib-ng/zlib-ng/actions/runs/1326434359

e.g.
https://github.com/zlib-ng/zlib-ng/pull/1048/checks?check_run_id=3870178563#step:5:16

**Comment by Dead2** [comment]
@jhlegarreta Yes, the 3 remaining Ubuntu 16.04 checks are also going to fail after maaany hours of waiting. That seems to be a bug in Github Actions regarding that specific distro version, not sure how that works but it has been like that for weeks now.

I have not seen the xcode errors before, but they probably just mean we need to update our CI scripts.

So I am ignoring those checks 😉

**Comment by jhlegarreta** [comment]
> @jhlegarreta Yes, the 3 remaining Ubuntu 16.04 checks are also going to fail after maaany hours of waiting. That seems to be a bug in Github Actions regarding that specific distro version, not sure how that works but it has been like that for weeks now.

@Dead2 Does this have to do with the above?
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

Should those builds transition to 18.04 as the minimum version?

**Comment by Dead2** [comment]
@jhlegarreta Yep, that is the reason. IMO, Github Actions should have failed quickly instead of spending lots of hours in queue before failing though.

**Pull request merged**
