### PR TITLE
Add back unaligned access support to longest_match variants

### PR DESCRIPTION
**Pull request by nmoinvaz**
For previous discussion see #508.

Changed `longest_match` and `insert_string` to use unaligned access instead of `memcmp` or `memcpy` for architectures where unaligned access is supported - these variants are intended for architectures where unaligned access is acceptable. If an architecture does not support unaligned access, then `UNALIGNED_OK` should not be defined. Added some comments to indicate that unaligned access is expected in certain places. These changes may have been made to fix sanitizers, however the alignment sanitizer should not be run on architectures that support unaligned access or when `UNALIGNED_OK` is defined.

Revert "Prefer memcpy and memcmp over direct memory read/comparisons. (#135)"
This reverts commit 72214719ca8db882ab49d31872528b8b456362aa.

Revert "fix all ASan errors on arm/aarch64"
This reverts commit bee695a6415bbf37087be132a3c40e2e761658c0.

### CODE REVIEW

**Comment by gdevenyi** [comment]
> Revert "Prefer memcpy and memcmp over direct memory read/comparisons. (#135)"
> This reverts commit 7221471.
> 
> Revert "fix all ASan errors on arm/aarch64"
> This reverts commit bee695a.

I think you can do an actual proper revert of these commits, and then apply your changes on top, if you want a cleaner history.

**Comment by nmoinvaz** [comment]
@gdevenyi, I have redone the PR to preserve the history when reverting.

**Comment by Dead2** [comment]
Needs a little rebase.

Looks great, but lets give the original authors of the reverted commits a chance to test and comment first too.
@ioquatix @sebpop do you see and issues with these changes?

**Comment by nmoinvaz** [comment]
Rebase done.

**Comment by Dead2** [comment]
On my Linux x86-64 skylake, this gives ~0.2-0.35% speedup in compression.
Would love to see some ARM bechmarks too.

**Comment by nmoinvaz** [comment]
Rebased again.

**Comment by nmoinvaz** [comment]
#522 should be merged first, then after that I can rebase.

**Comment by nmoinvaz** [comment]
I have removed one of the commits, so a rebase is not needed.

**Comment by nmoinvaz** [comment]
#544 should be performance tested first to see if it is better.

**Comment by ioquatix** [comment]
This issue reminds me of this video:

https://www.youtube.com/watch?v=r-TLSBdHe1A

There is some tooling to help evaluate whether changes like this are actually a practical improvement or not.

**Comment by nmoinvaz** [comment]
That is a good video thanks for sharing.

**Pull request closed without merging**
