### PR TITLE
Remove ZLIB_DUAL_LINK option in favor of detecting ZLIB_LIBRARIES.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by mtl1979** [comment]
It would make more sense to check for presence of `ZLIB_ROOT` as it's the primary define for zlib detection. All other defines are optional due to using `find_package()`.

**Comment by nmoinvaz** [comment]
Hmm.. We aren't passing in ZLIB_ROOT in cmake for the Link workflow..

**Comment by nmoinvaz** [comment]
ZLIB_ROOT is probably only used for ZLIB installations, where in our case in the GHA workflows, we are building them from scratch.

**Comment by nmoinvaz** [comment]
I improved the commit message.

**Comment by mtl1979** [comment]
I still think the new version causes even more confusion than the original. Why use `find_package()` when the paths are supposed to always be hard-coded... This is pretty much counter-intuitive with depending on `ZLIB_LIBRARIES` being correctly defined.

The original version might not have been the best choice, but replacing one bad choice with another bad choice isn't really a good idea....

The safest choice would be to check if either `ZLIB_ROOT` or `ZLIB_LIBRARIES` is defined, but that would increase complexity and pretty much duplicate the logic already inside `find_package()`.

**Comment by nmoinvaz** [comment]
I have removed `find_package()` so there isn't that ambiguity.

**Review by Dead2 — APPROVED** [review]
LGTM

**Pull request merged**
