### PR TITLE
Add -Weverything for maintainer builds on clang

### PR DESCRIPTION
**Pull request by gdevenyi**
Ref #595

### CODE REVIEW

**Comment by Dead2** [comment]
I am not quite sure I want this many warnings in CI, for one it makes it harder to spot any serious ones, and it also prevents us from enabling -Werror for CI builds. If all those warnings had been fixed first, that might help though.
-Weverything is a good exercise to do sometimes though, to see whether there are low-hanging code-quality improvements that can be done.

**Comment by gdevenyi** [comment]
How about a seperate CI config for -Weverything with my analyzer PR?

**Comment by nmoinvaz** [comment]
I think the level of warnings that the `WITH_MAINTAINER_WARNINGS` provides is sufficient in most cases. If there is a PR to actually fix the warnings that is more valuable, but I will likely never go into the CI job and search for warnings to fix.

**Comment by gdevenyi** [comment]
Okay no problem.

**Pull request closed without merging**
