### PR TITLE
Allow compilation with MSVC variant of clang (clang-cl)

### LINKED ISSUE #1181: Compile failure on MSVC-Clang with Compat and prefix
Using VS 2022 and CMake 3.21.4. Setting `CMAKE_GENERATOR_TOOLSET=ClangCL` (via GUI field for it),  `ZLIB_COMPAT=ON` and `ZLIB_SYMBOL_PREFIX=test_` results in build failures (log below). This is one of two causes for ITK to fail compilation with the same combination of options.

The build succeeds if I revert either `ZLIB_COMPAT` or `ZLIB_SYMBOL_PREFIX` to default values. Has anyone tried Visual Studio + Clang before? It is strange that it fails only for this combination of options.

```text
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: RelWithDebInfo x64 ------
1>Checking Build System
2>------ Build started: Project: zlibstatic, Configuration: RelWithDebInfo x64 ------
3>------ Build started: Project: zlib, Configuration: RelWithDebInfo x64 ------
4>------ Build started: Project: maketrees, Configuration: RelWithDebInfo x64 ------
5>------ Build started: Project: makefixed, Configuration: RelWithDebInfo x64 ------
6>------ Build started: Project: makecrct, Configuration: RelWithDebInfo x64 ------
7>------ Skipped Build: Project: RUN_TESTS, Configuration: RelWithDebInfo x64 ------
7>Project not selected to build for this solution configuration 
2>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
4>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
3>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
5>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
6>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
6>makecrct.vcxproj -> C:\Misc\zlib-ng-22\RelWithDebInfo\makecrct.exe
5>makefixed.vcxproj -> C:\Misc\zlib-ng-22\RelWithDebInfo\makefixed.exe
4>maketrees.vcxproj -> C:\Misc\zlib-ng-22\RelWithDebInfo\maketrees.exe
2>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
2>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(52,5): error : invalid instruction mnemonic 'test_crc32'
2>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
2><inline asm>(4,2): message : instantiated into assembly here
2>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
2>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(68,5): error : invalid instruction mnemonic 'test_crc32'
2>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
2><inline asm>(4,2): message : instantiated into assembly here
2>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
2>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(97,9): error : invalid instruction mnemonic 'test_crc32'
2>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
2><inline asm>(4,2): message : instantiated into assembly here
2>Done building project "zlibstatic.vcxproj" -- FAILED.
8>------ Build started: Project: minigzip, Configuration: RelWithDebInfo x64 ------
3>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
3>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(52,5): error : invalid instruction mnemonic 'test_crc32'
3>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
3><inline asm>(4,2): message : instantiated into assembly here
3>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
3>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(68,5): error : invalid instruction mnemonic 'test_crc32'
3>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
3><inline asm>(4,2): message : instantiated into assembly here
3>In file included from C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c:49:
3>C:\Misc\zlib-ng\arch\x86/../../insert_string_tpl.h(97,9): error : invalid instruction mnemonic 'test_crc32'
3>C:\Misc\zlib-ng\arch\x86\insert_string_sse42.c(26,9): message : expanded from macro 'HASH_CALC'
3><inline asm>(4,2): message : instantiated into assembly here
8>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
3>Done building project "zlib.vcxproj" -- FAILED.
9>------ Build started: Project: test_inflate_adler32, Configuration: RelWithDebInfo x64 ------
10>------ Build started: Project: test_hash_head_0, Configuration: RelWithDebInfo x64 ------
11>------ Build started: Project: test_deflate_quick_block_open, Configuration: RelWithDebInfo x64 ------
12>------ Build started: Project: test_deflate_quick_bi_valid, Configuration: RelWithDebInfo x64 ------
13>------ Build started: Project: test_crc32, Configuration: RelWithDebInfo x64 ------
14>------ Build started: Project: test_adler32, Configuration: RelWithDebInfo x64 ------
15>------ Build started: Project: switchlevels, Configuration: RelWithDebInfo x64 ------
16>------ Build started: Project: minideflate, Configuration: RelWithDebInfo x64 ------
17>------ Build started: Project: infcover, Configuration: RelWithDebInfo x64 ------
18>------ Build started: Project: example, Configuration: RelWithDebInfo x64 ------
14>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
15>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
13>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
16>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
17>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
18>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
10>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
9>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
11>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
12>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
13>C:\Misc\zlib-ng\test\test_crc32.c(25,6): error : conflicting types for 'test_crc32'
13>C:\Misc\zlib-ng-22\zlib.h(1701,33): message : previous declaration is here
13>C:\Misc\zlib-ng-22/zlib_name_mangling.h(26,31): message : expanded from macro 'crc32'
8>lld-link : error : undefined symbol: test_gzwrite
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:111
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_compress)
8>
8>lld-link : error : undefined symbol: test_gzerror
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:111
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_compress)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:166
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_uncompress)
8>
8>lld-link : error : undefined symbol: test_gzclose
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:115
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_compress)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:178
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_uncompress)
8>
8>lld-link : error : undefined symbol: test_gzread
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:163
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(gz_uncompress)
8>
8>lld-link : error : undefined symbol: test_gzopen
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:203
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(file_compress)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:241
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(file_uncompress)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:341
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(main)
8>
8>lld-link : error : undefined symbol: test_gzdopen
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:356
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(main)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:326
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(main)
8>>>> referenced by C:\Misc\zlib-ng\test\minigzip.c:330
8>>>>               minigzip.dir\RelWithDebInfo\minigzip.obj:(main)
8>Done building project "minigzip.vcxproj" -- FAILED.
13>C:\Misc\zlib-ng\test\test_crc32.c(194,62): error : too many arguments to function call, expected 3, have 5
13>C:\Misc\zlib-ng-22\zlib.h(1701,33): message : 'test_crc32' declared here
13>C:\Misc\zlib-ng-22/zlib_name_mangling.h(26,31): message : expanded from macro 'crc32'
13>Done building project "test_crc32.vcxproj" -- FAILED.
18>C:\Misc\zlib-ng\test\example.c(32,6): error : conflicting types for 'test_compress'
18>C:\Misc\zlib-ng-22\zlib.h(1211,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(22,33): message : expanded from macro 'compress'
18>C:\Misc\zlib-ng\test\example.c(34,6): error : conflicting types for 'test_deflate'
18>C:\Misc\zlib-ng-22\zlib.h(260,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(30,31): message : expanded from macro 'deflate'
18>C:\Misc\zlib-ng\test\example.c(35,6): error : conflicting types for 'test_inflate'
18>C:\Misc\zlib-ng-22\zlib.h(410,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(88,31): message : expanded from macro 'inflate'
18>C:\Misc\zlib-ng\test\example.c(69,6): error : conflicting types for 'test_compress'
18>C:\Misc\zlib-ng-22\zlib.h(1211,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(22,33): message : expanded from macro 'compress'
18>C:\Misc\zlib-ng\test\example.c(199,6): error : conflicting types for 'test_deflate'
18>C:\Misc\zlib-ng-22\zlib.h(260,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(30,31): message : expanded from macro 'deflate'
18>C:\Misc\zlib-ng\test\example.c(236,6): error : conflicting types for 'test_inflate'
18>C:\Misc\zlib-ng-22\zlib.h(410,23): message : previous declaration is here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(88,31): message : expanded from macro 'inflate'
18>C:\Misc\zlib-ng\test\example.c(979,26): warning : incompatible integer to pointer conversion passing 'unsigned long' to parameter of type 'unsigned long *'; take the address with & [-Wint-conversion]
18>C:\Misc\zlib-ng-22\zlib.h(1211,68): message : passing argument to parameter 'destLen' here
18>C:\Misc\zlib-ng\test\example.c(984,18): warning : incompatible pointer types passing 'unsigned char *' to parameter of type 'z_stream *' (aka 'struct z_stream_s *') [-Wincompatible-pointer-types]
18>C:\Misc\zlib-ng-22\zlib.h(260,41): message : passing argument to parameter 'strm' here
18>C:\Misc\zlib-ng\test\example.c(985,35): error : too many arguments to function call, expected 2, have 4
18>C:\Misc\zlib-ng-22\zlib.h(410,23): message : 'test_inflate' declared here
18>C:\Misc\zlib-ng-22/zlib_name_mangling.h(88,31): message : expanded from macro 'inflate'
18>Done building project "example.vcxproj" -- FAILED.
14>C:\Misc\zlib-ng\test\test_adler32.c(24,6): error : conflicting types for 'test_adler32'
14>C:\Misc\zlib-ng-22\zlib.h(1665,33): message : previous declaration is here
14>C:\Misc\zlib-ng-22/zlib_name_mangling.h(17,31): message : expanded from macro 'adler32'
14>C:\Misc\zlib-ng\test\test_adler32.c(359,66): error : too many arguments to function call, expected 3, have 5
14>C:\Misc\zlib-ng-22\zlib.h(1665,33): message : 'test_adler32' declared here
14>C:\Misc\zlib-ng-22/zlib_name_mangling.h(17,31): message : expanded from macro 'adler32'
16>lld-link : error : undefined symbol: test_deflateInit2_
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:68
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(deflate_params)
16>
16>lld-link : error : undefined symbol: test_deflate
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:82
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(deflate_params)
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:104
9>lld-link : error : undefined symbol: test_inflateInit2_
9>>>> referenced by C:\Misc\zlib-ng\test\test_inflate_adler32.c:30
9>>>>               test_inflate_adler32.dir\RelWithDebInfo\test_inflate_adler32.obj:(main)
9>
9>lld-link : error : undefined symbol: test_inflate
9>>>> referenced by C:\Misc\zlib-ng\test\test_inflate_adler32.c:41
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(deflate_params)
16>
16>lld-link : error : undefined symbol: test_deflateEnd
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:115
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(deflate_params)
16>
16>lld-link : error : undefined symbol: test_inflateInit2_
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:154
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(inflate_params)
16>
16>lld-link : error : undefined symbol: test_inflate
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:168
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(inflate_params)
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:190
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(inflate_params)
16>
16>lld-link : error : undefined symbol: test_inflateEnd
16>>>> referenced by C:\Misc\zlib-ng\test\minideflate.c:201
16>>>>               minideflate.dir\RelWithDebInfo\minideflate.obj:(inflate_params)
16>Done building project "minideflate.vcxproj" -- FAILED.
10>lld-link : error : undefined symbol: test_deflateInit2_
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:18
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_deflateParams
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:36
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:52
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_deflate
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:44
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:60
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:68
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_deflateEnd
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:75
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_inflateInit2_
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:82
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_inflate
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:94
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
10>
10>lld-link : error : undefined symbol: test_inflateEnd
10>>>> referenced by C:\Misc\zlib-ng\test\test_hash_head_0.c:100
10>>>>               test_hash_head_0.dir\RelWithDebInfo\test_hash_head_0.obj:(main)
9>>>>               test_inflate_adler32.dir\RelWithDebInfo\test_inflate_adler32.obj:(main)
9>
9>lld-link : error : undefined symbol: test_inflateEnd
9>>>> referenced by C:\Misc\zlib-ng\test\test_inflate_adler32.c:47
9>>>>               test_inflate_adler32.dir\RelWithDebInfo\test_inflate_adler32.obj:(main)
9>Done building project "test_inflate_adler32.vcxproj" -- FAILED.
14>Done building project "test_adler32.vcxproj" -- FAILED.
10>Done building project "test_hash_head_0.vcxproj" -- FAILED.
12>lld-link : error : undefined symbol: test_deflateInit2_
12>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_bi_valid.c:18
12>>>>               test_deflate_quick_bi_valid.dir\RelWithDebInfo\test_deflate_quick_bi_valid.obj:(main)
12>
12>lld-link : error : undefined symbol: test_deflate
12>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_bi_valid.c:66
12>>>>               test_deflate_quick_bi_valid.dir\RelWithDebInfo\test_deflate_quick_bi_valid.obj:(main)
12>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_bi_valid.c:74
12>>>>               test_deflate_quick_bi_valid.dir\RelWithDebInfo\test_deflate_quick_bi_valid.obj:(main)
12>
12>lld-link : error : undefined symbol: test_deflateEnd
12>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_bi_valid.c:80
12>>>>               test_deflate_quick_bi_valid.dir\RelWithDebInfo\test_deflate_quick_bi_valid.obj:(main)
12>Done building project "test_deflate_quick_bi_valid.vcxproj" -- FAILED.
11>lld-link : error : undefined symbol: test_deflateInit2_
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:18
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>
11>lld-link : error : undefined symbol: test_deflate
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:65
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>
15>lld-link : error : undefined symbol: test_deflateInit2_
15>>>> referenced by C:\Misc\zlib-ng\test\switchlevels.c:148
15>>>>               switchlevels.dir\RelWithDebInfo\switchlevels.obj:(main)
15>
15>lld-link : error : undefined symbol: test_deflateEnd
15>>>> referenced by C:\Misc\zlib-ng\test\switchlevels.c:164
15>>>>               switchlevels.dir\RelWithDebInfo\switchlevels.obj:(main)
15>
15>lld-link : error : undefined symbol: test_deflateBound
15>>>> referenced by C:\Misc\zlib-ng\test\switchlevels.c:67
11>lld-link : error : undefined symbol: test_deflateEnd
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:75
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>
11>lld-link : error : undefined symbol: test_inflateInit2_
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:82
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>
11>lld-link : error : undefined symbol: test_inflate
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:94
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>
11>lld-link : error : undefined symbol: test_inflateEnd
11>>>> referenced by C:\Misc\zlib-ng\test\test_deflate_quick_block_open.c:100
11>>>>               test_deflate_quick_block_open.dir\RelWithDebInfo\test_deflate_quick_block_open.obj:(main)
11>Done building project "test_deflate_quick_block_open.vcxproj" -- FAILED.
15>>>>               switchlevels.dir\RelWithDebInfo\switchlevels.obj:(compress_chunk)
15>
15>lld-link : error : undefined symbol: test_deflateParams
15>>>> referenced by C:\Misc\zlib-ng\test\switchlevels.c:83
15>>>>               switchlevels.dir\RelWithDebInfo\switchlevels.obj:(compress_chunk)
15>
15>lld-link : error : undefined symbol: test_deflate
15>>>> referenced by C:\Misc\zlib-ng\test\switchlevels.c:92
15>>>>               switchlevels.dir\RelWithDebInfo\switchlevels.obj:(compress_chunk)
15>Done building project "switchlevels.vcxproj" -- FAILED.
17>lld-link : error : undefined symbol: test_zlibVersion
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:664
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(main)
17>
17>lld-link : error : undefined symbol: test_inflateInit_
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:356
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:374
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:380
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>
17>lld-link : error : undefined symbol: test_inflatePrime
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:358
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:359
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:423
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>
17>lld-link : error : undefined symbol: test_inflateSetDictionary
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:360
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:420
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:324
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>>>> referenced 1 more times
17>
17>lld-link : error : undefined symbol: test_inflateEnd
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:362
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:381
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_support)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:393
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced 4 more times
17>
17>lld-link : error : undefined symbol: test_inflate
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:392
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:427
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:319
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>>>> referenced 2 more times
17>
17>lld-link : error : undefined symbol: test_inflateCopy
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:394
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:432
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:332
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>
17>lld-link : error : undefined symbol: test_inflateInit2_
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:414
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:292
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:294
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>>>> referenced 1 more times
17>
17>lld-link : error : undefined symbol: test_inflateSync
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:426
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:430
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>
17>lld-link : error : undefined symbol: test_inflateSyncPoint
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:431
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>
17>lld-link : error : undefined symbol: test_inflateUndermine
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:434
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>
17>lld-link : error : undefined symbol: test_inflateMark
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:440
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_wrap)
17>
17>lld-link : error : undefined symbol: test_inflateBackInit_
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:473
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:475
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:483
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced 2 more times
17>
17>lld-link : error : undefined symbol: test_inflateBack
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:477
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:487
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:492
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced 2 more times
17>
17>lld-link : error : undefined symbol: test_inflateBackEnd
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:479
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:497
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:502
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(cover_back)
17>>>> referenced 1 more times
17>
17>lld-link : error : undefined symbol: test_inflateGetHeader
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:307
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>
17>lld-link : error : undefined symbol: test_inflateReset2
17>>>> referenced by C:\Misc\zlib-ng\test\infcover.c:342
17>>>>               infcover.dir\RelWithDebInfo\infcover.obj:(inf)
17>Done building project "infcover.vcxproj" -- FAILED.
19>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
19>Building Custom Rule C:/Misc/zlib-ng/CMakeLists.txt
20>------ Skipped Build: Project: INSTALL, Configuration: RelWithDebInfo x64 ------
20>Project not selected to build for this solution configuration 
========== Build: 5 succeeded, 13 failed, 0 up-to-date, 2 skipped ==========
```

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #1181.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Seems like this might also be solved by moving the deflate.h include into insert_string_tpl.h..

**Comment by nmoinvaz** [comment]
Or I mean fixing the includes so the wrong one isn't included before hand..

**Comment by dzenanz** [comment]
That sounds like a cleaner solution. But adding `#include "deflate.h"` near the top of `insert_string_tpl.h` does not solve the build error.

**Comment by nmoinvaz** [comment]
This PR is no longer needed since it was an issue of CMakeCache needing to be regenerated after upgrading.

**Pull request closed without merging**
