### PR TITLE
Added gzip tests for all open modes and compression levels

### PR DESCRIPTION
**Pull request by nmoinvaz**
This PR adds some gzip tests for minigzip to improve code coverage. I have also added some testdata from Google's [snappy](https://github.com/google/snappy/tree/master/testdata) project which are used for the tests. In order to test all strategies/gzip-open-modes I had to modify/add some of the arguments to minigzip. But this change helps cover more code so I think it is worth it.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
This is what I get at least for my fork:
image
With the checksum commit I did the other day it should bring it above 70%.

**Comment by Dead2** [comment]
Hmm, I think we'd need to at least specify what license each of the the test data files are under, and a source for them would also be great.

**Comment by nmoinvaz** [comment]
I don't have that information. One of the text files is from the library of congress. fireworks.jpeg helps reproduce some issues that we have encountered in the past.

**Comment by nmoinvaz** [comment]
https://github.com/google/snappy/blob/19690d78e83f8963f497585031efa3d9ca66b807/COPYING

**Comment by Dead2** [comment]
@nmoinvaz The information from COPYING that relates to files used here should be in this PR as well, perhaps in a file like test/data/COPYING. We don't want to imply that these files are under the zlib license like the rest of the repo..

**Comment by nmoinvaz** [comment]
I have added the copying information to the README.md in test directory. If you rather have it in a separate file in data directory instead let me know.

**Comment by Dead2** [comment]
Looks good :)

**Comment by nmoinvaz** [comment]
Code coverage increased by 7%. Nice!

image

**Pull request merged**
