### PR TITLE
Remove unnecessary test for stdarg.h

### PR DESCRIPTION
**Pull request by mtl1979**
This style of test breaks if same test is done in project including zlib-ng.

zlib-ng doesn't include `stdarg.h` in any source files.

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]

**Comment by nmoinvaz** [comment]
I am seeing stdarg.h included in zconf.h & zlib.h & configure.. maybe those should be removed too?

**Comment by nmoinvaz** [comment]
Actually looks like va_list is only used in one function: gzvprintf.

**Comment by nmoinvaz** [comment]
Actually gzprintf too. But perhaps stdarg.h include can be moved to gzwrite.c instead of having it in zlib headers?

**Comment by mtl1979** [comment]
@nmoinvaz We basically don't support anything that doesn't have `stdarg.h`... It's considered standard header nowadays.

**Comment by nmoinvaz** [comment]
What do you think of removing it from zlib headers/config and moving it to gzwrite.c only where it is used?

**Comment by mtl1979** [comment]
@nmoinvaz Doesn't compile if I try to remove include for `stdarg.h` as `va_list` is used in the headers.

**Pull request merged**
