### PR TITLE
ARM Fixes...

### PR DESCRIPTION
**Pull request by mtl1979**
* Some optimizations for NEON to reduce code size
* Don't call chunkcopy() from inside chunkcopy_safe() as it might write past safe length if len is not multiple of chunk size.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
It looks like it passes the pigz CI test I added for aarch64 which is great! My only comment is that the commit messages could be a bit better and explain the changes. Other than that it LGTM.

**Comment by nmoinvaz** [comment]
Actually we may need benchmarks for x86 and aarch64.

**Comment by mtl1979** [comment]
@nmoinvaz It's 3 am here and I've been awake since Wednesday ;)

**Comment by nmoinvaz** [comment]
I can run some x86 benchmarks tonight.

**Comment by mtl1979** [comment]
I noticed my compiler can also do 32 byte chunks on AArch64... Dunno how much faster that is than using 16 byte chunks...

I know 48 byte chunks caused some issues because that is odd register count, not even.

**Comment by mtl1979** [comment]
I made the individual commit messages a little more descriptive... I guess @Dead2 wants to be the second one to give feedback as I know he likes to play with ARM devices ;)

**Comment by nmoinvaz** [comment]
## Corpora.tar

### ZLIB-NG https://github.com/zlib-ng/zlib-ng/commit/834e7d83eae9ff7bfb1b9769d9f311ea7ca8e746

```
 Tool: minigzip-ng-develop.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     44.809%      1.054/1.071/1.081/0.007        0.668/0.685/0.693/0.006      104,067,822
 2     35.391%      1.731/1.754/1.763/0.008        0.685/0.695/0.699/0.004       82,195,416
 3     33.698%      2.376/2.395/2.404/0.007        0.658/0.673/0.678/0.004       78,262,436
 4     32.989%      2.689/2.703/2.712/0.007        0.644/0.659/0.664/0.004       76,616,183
 5     32.483%      2.818/2.858/2.869/0.012        0.643/0.654/0.658/0.003       75,441,984
 6     32.318%      3.465/3.486/3.496/0.008        0.642/0.650/0.656/0.004       75,058,801
 7     32.061%      4.731/4.760/4.773/0.011        0.639/0.651/0.656/0.005       74,461,300
 8     31.978%      7.218/7.309/7.327/0.025        0.644/0.653/0.657/0.003       74,269,032
 9     31.961%      9.862/9.932/9.953/0.019        0.647/0.659/0.666/0.005       74,230,342

 avg1  34.188%                        4.030                          0.664
 tot                               1088.034                        179.321      714,603,316
```

### ZLIB-NG PR 1008 https://github.com/zlib-ng/zlib-ng/commit/0025f875e247ccfac1a04ccda8d434635cbf896b

```
 Tool: minigzip-ng-chunkset-neon.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     44.809%      1.057/1.067/1.075/0.006        0.674/0.681/0.686/0.003      104,067,822
 2     35.391%      1.727/1.747/1.757/0.008        0.681/0.691/0.695/0.003       82,195,416
 3     33.698%      2.360/2.395/2.409/0.011        0.656/0.665/0.672/0.004       78,262,436
 4     32.989%      2.667/2.699/2.710/0.009        0.642/0.654/0.659/0.004       76,616,183
 5     32.483%      2.839/2.861/2.871/0.009        0.637/0.650/0.654/0.004       75,441,984
 6     32.318%      3.454/3.486/3.496/0.009        0.636/0.645/0.650/0.003       75,058,801
 7     32.061%      4.723/4.767/4.782/0.012        0.639/0.650/0.654/0.003       74,461,300
 8     31.978%      7.233/7.305/7.329/0.025        0.636/0.648/0.652/0.004       74,269,032
 9     31.961%      9.808/9.915/9.945/0.036        0.642/0.653/0.660/0.005       74,230,342

 avg1  34.188%                        4.027                          0.660
 tot                               1087.268                        178.137      714,603,316
```

**Comment by mtl1979** [comment]
That's like 0.007% and 0.66% difference... lol...

**Comment by nmoinvaz** [comment]
Well it's not bad. I just wanted to make sure there wasn't a degradation of any kind.

**Comment by mtl1979** [comment]
@nmoinvaz Exactly... I was expecting some degradation... But I guess the optimizer works as I wanted, as in modifying `len` in every step doesn't slow it down.

**Review by nmoinvaz — APPROVED** [review]

**Comment by Dead2** [comment]
### Baseline 834e7d83eae9ff7bfb1b9769d9f311ea7ca8e746 aarch64
```
   text    data     bss     dec     hex filename
 105194    1576      16  106786   1a122 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.746/2.764/2.780/0.011        0.965/0.993/1.015/0.013       42,618,858
 2     43.879%      2.819/2.851/2.870/0.017        0.563/0.601/0.631/0.022       20,714,938
 3     42.383%      3.713/3.758/3.780/0.020        0.565/0.580/0.592/0.008       20,008,755
 4     41.660%      2.768/2.802/2.818/0.015        0.353/0.372/0.381/0.008       13,111,391
 5     41.216%      3.014/3.031/3.051/0.012        0.365/0.375/0.383/0.005       12,971,746
 6     41.039%      3.505/3.539/3.555/0.014        0.358/0.372/0.384/0.009       12,916,025
 7     40.778%      2.239/2.270/2.284/0.011        0.168/0.175/0.181/0.004        6,416,924
 8     40.704%      2.769/2.800/2.809/0.010        0.168/0.179/0.188/0.007        6,405,244
 9     40.696%      2.983/3.016/3.029/0.013        0.160/0.172/0.180/0.007        6,404,084

 avg1  42.947%                        2.981                          0.424
 tot                                402.450                         57.285      141,567,965
```

### PR #1008 858ec3eecc50bb6bb614a7b01ae17b99ee41f6a4 aarch64
```
   text    data     bss     dec     hex filename
 105194    1576      16  106786   1a122 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.739/2.769/2.803/0.017        0.979/0.997/1.010/0.009       42,618,858
 2     43.879%      2.838/2.857/2.871/0.011        0.584/0.612/0.625/0.013       20,714,938
 3     42.383%      3.733/3.754/3.780/0.016        0.551/0.582/0.597/0.015       20,008,755
 4     41.660%      2.765/2.800/2.815/0.014        0.353/0.375/0.387/0.011       13,111,391
 5     41.216%      3.003/3.026/3.042/0.012        0.352/0.372/0.381/0.008       12,971,746
 6     41.039%      3.513/3.533/3.540/0.007        0.351/0.364/0.378/0.008       12,916,025
 7     40.778%      2.247/2.271/2.283/0.009        0.156/0.179/0.188/0.009        6,416,924
 8     40.704%      2.772/2.804/2.817/0.011        0.161/0.177/0.184/0.007        6,405,244
 9     40.696%      2.988/3.024/3.039/0.013        0.156/0.177/0.188/0.008        6,404,084

 avg1  42.947%                        2.982                          0.426
 tot                                402.583                         57.530      141,567,965
```

**Pull request merged**
