### PR TITLE
Added CI configurations for MSVC ARM and ARM64

### PR DESCRIPTION
**Pull request by nmoinvaz**
This PR adds CI build checks for MSVC ARM and ARM64 for both nmake and cmake. 

It does not test the built output for those platforms, since I think we would need a Windows ARM machine to test them against. I have not found a way to emulate them like we normally would with cmake/qemu.

It should be rebased after #567 is merged, then we can see where it is failing after that.

### CODE REVIEW

**Comment by Dead2** [comment]
One of the new tests fails with `functable.c(124): error C2065: 'arm_cpu_has_neon': undeclared identifier`.

**Comment by nmoinvaz** [comment]
That should be resolved after #567 is merged.

**Comment by nmoinvaz** [comment]
Now I am getting an error when compiling MSVC ARM.

```
memcopy.h(53): error C3905: unaligned accesses are not supported for intrinsic type '__n128'
```
However on my machine it works without a problem when using the VS2015 x86 ARM Cross Tools Command Prompt. The easiest thing to do would be to disable `INFFAST_CHUNKSIZE` on `_M_ARM`.

@mtl1979 what do you think?

**Comment by mtl1979** [comment]
@nmoinvaz For some reason it is trying to compile ACLE-related files without ACLE support.

Also...

```
static inline void storechunk(unsigned char* d, inffast_chunk_t c) {
    memcpy((inffast_chunk_t *)d, &c, sizeof(c));
}
```

Visual C++ requires explicit cast with memcpy().

**Comment by nmoinvaz** [comment]
The error says the issue is with unaligned access. Are you saying `d` should be cast to `uint8_t*`?

**Comment by mtl1979** [comment]
@nmoinvaz Cast to ```uint8_t*``` will not work as VC++ is too smart. The error is misleading, because ```__n128``` is defined as a struct with maximum alignment, not minimum alignment... Essentially it is a compiler ambiguity that has existed from at least VS2017.

**Comment by nmoinvaz** [comment]
```
memcopy.h(53): error C3905: unaligned accesses are not supported for intrinsic type '__n128'
```
And..
```
functable.obj : error LNK2019: unresolved external symbol compare258_unaligned_16 referenced in function compare258_stub
functable.obj : error LNK2019: unresolved external symbol longest_match_unaligned_16 referenced in function longest_match_stub
```

**Comment by mtl1979** [comment]
That first error was already addressed... It's a compiler bug that needs workaround...

**Comment by nmoinvaz** [comment]
Where was it addressed? I did a rebase so it should have it?

**Comment by nmoinvaz** [comment]
Ah in the comments! :-)

**Comment by nmoinvaz** [comment]
I guess I'm not quite sure what to do about it.

**Comment by mtl1979** [comment]
Adding implicit cast should not break it with gcc/clang... For the two remaining errors, I can't help until I try to fetch the commit and grep the sources...

**Comment by nmoinvaz** [comment]
I fixed the last two errors. Looks like the Windows arm makefiles were out of date some what. Good thing we are adding them to CI!

**Comment by nmoinvaz** [comment]
@mtl1979 I tried your code above, it resulted in failed fuzzing and other CIs. `this fault was caused by a dereference of a high value address`. I'm going to try:
```
static inline void storechunk(unsigned char* d, inffast_chunk_t c) {
    memcpy((inffast_chunk_t *)d, &c, 1);
}
```
To see if that fixes it.

**Comment by mtl1979** [comment]
Casting a pointer should not garble the higher bits of the address... That most likely is caused by irrelevant bug.

**Comment by nmoinvaz** [comment]
The full error can be found here: https://github.com/zlib-ng/zlib-ng/runs/704073458?check_suite_focus=true. I only copied a portion of it.

**Comment by nmoinvaz** [comment]
Well that didn't work.. it compiled but a lot of other CI failed.

**Comment by mtl1979** [comment]
Most likely it's bug in the sanitizer, not our code... I tried disassembling the code using compiler explorer and the generated code is correct and output from running is expected even if I force unaligned access.

https://godbolt.org/z/L1jm0E

**Comment by nmoinvaz** [comment]
I am going to try something like this and see if it works then:
```
static inline void storechunk(unsigned char* d, inffast_chunk_t c) {
    inffast_chunk_t *dchunk = (inffast_chunk_t *)d;
    memcpy(dchunk, &c, 1);
}
```

**Comment by mtl1979** [comment]
Obviously the third parameter can't be 1, as it would copy only one byte.

**Comment by nmoinvaz** [comment]
Even still looks like a bunch of CI fail.. hmm

**Comment by mtl1979** [comment]
Memory addresses in the register dump are way off... This suggests the sanitizer has failed to intercept some memory allocation calls or it tries to read outside of stack...

**Comment by nmoinvaz** [comment]
Looks like all tests passing now.

**Comment by mtl1979** [comment]
Hopefully the next release of Visual Studio 2019 will have a fix for the optimizer bug...

**Pull request merged**
