### PR TITLE
Use standard int types in zlib-ng api

### PR DESCRIPTION
**Pull request by nmoinvaz**
See last commits.

### CODE REVIEW

**Comment by Dead2** [comment]
Are these changes compatible with the zlib-compat api on all the arches we support?

I know int is 16bit on 16bit platforms, but we don't support those anyway. But wasn't there another arch/platform with a similar issue?

**Comment by nmoinvaz** [comment]
I wouldn't know about 16bit platforms.. @mtl1979 might though.

**Comment by nmoinvaz** [comment]
And this was another instance I was unsure about what to do:

image

Should we convert to using `size_t`? I don't think it would be compatible.. we would need a shim for zlib API users..

**Comment by mtl1979** [comment]
We already have shims for some functions, so adding more isn't issue.

What comes to changing int types, only PPC is strict about them, and we already have PPC build in CI to catch those issues.

**Comment by mtl1979** [comment]
@nmoinvaz size_t is not standard. It can be 32-bit even on 64-bit targets. We use _z suffix for functions that use size_t instead on uint64_t.

**Comment by nmoinvaz** [comment]
I have changed `zng_gz_header::time` back to unsigned long.

**Comment by nmoinvaz** [comment]
I think I will wait on this until after #602.

**Comment by nmoinvaz** [comment]
Rebased

**Comment by Dead2** [comment]
CI fails

**Comment by mtl1979** [comment]
Conflicting declarations of inflateMark

**Comment by Dead2** [comment]
Lets get this out there :)

**Pull request merged**
