### PR TITLE
Added CI test for checking undefined symbols in version scripts.

### PR DESCRIPTION
**Pull request by nmoinvaz**
See #1427 and #1421.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Quick link to failure job: https://github.com/zlib-ng/zlib-ng/actions/runs/4120456027/jobs/7115205871

**Comment by mtl1979** [comment]
Do we want one for `ZLIB_COMPAT` too?

**Comment by nmoinvaz** [comment]
Good idea, I have added it.

**Comment by mtl1979** [comment]
I didn't expect the `ZLIB_COMPAT`run to fail with `/usr/bin/ld: cannot find -lzlibstatic: No such file or directory`... This kind of revealed another bug...

**Comment by nmoinvaz** [comment]
It looks like it was introduced in https://github.com/zlib-ng/zlib-ng/pull/1352/files @iii-i

**Comment by mtl1979** [comment]
> It looks like it was introduced in https://github.com/zlib-ng/zlib-ng/pull/1352/files @iii-i

Yup... It looks like `ZLIBNG_ENABLE_TESTS` is never set to `OFF` by `CMakeLists.txt` files.

**Comment by nmoinvaz** [comment]
The `gtest_zlib` doesn't support `BUILD_SHARED_LIBS=ON` because it needs access to internal zlib functions for testing.

**Comment by mtl1979** [comment]
> The `gtest_zlib` doesn't support `BUILD_SHARED_LIBS=ON` because it needs access to internal zlib functions for testing.

Some tests will be disabled if both `ZLIB_COMPAT` and `BUILD_SHARED_LIBS` are set...

**Comment by mtl1979** [comment]
There is a typo in one of the commit messages, `intenral` should be `internal`.

**Comment by mtl1979** [comment]
I had to use `-DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -Wl,--no-undefined-version"` instead of setting `CMAKE_LINKER` to get the expected failure... This also meant installing `lld` as my Ubuntu didn't have it installed.

**Comment by nmoinvaz** [comment]
It already shows expected failure.

**Comment by mtl1979** [comment]
> It already shows expected failure.

Not for the `ZLIB_COMPAT` case.

**Comment by Dead2** [comment]
> I had to use `-DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -Wl,--no-undefined-version"` instead of setting `CMAKE_LINKER` to get the expected failure... This also meant installing `lld` as my Ubuntu didn't have it installed.

I agree, this is the right way to do it, mainly due to CMake running the linker stage through the compiler instead of the linker even when you specify a linker executable..
I thought about this after I went to bed last night and regretted not re-testing and recommending this way instead (I originally tested this way first, but it failed without any good message, so I changed things before noticing the culprit; lld was not installed along with clang as I had expected)

Not sure why the compat run didn't show the expected failures, and I see nothing wrong in the CI config or the logs, so possibly this is why. CMake probably ran clang to link, and clang might have chosen to use ld instead of lld. Although that would depend on the ld used having already been patched to ignore and not error out on that parameter, because on my 1.5 year old distro it will error out. If that is not why, then I am at a loss. Hard to know when the build doesn't use a verbose makefile so it shows compiler and linker flags =/

**Comment by mtl1979** [comment]
> Not sure why the compat run didn't show the expected failures, and I see nothing wrong in the CI config or the logs, so possibly this is why. CMake probably ran clang to link, and clang might have chosen to use ld instead of lld. Although that would depend on the ld used having already been patched to ignore and not error out on that parameter, because on my 1.5 year old distro it will error out. If that is not why, then I am at a loss. Hard to know when the build doesn't use a verbose makefile so it shows compiler and linker flags =/

I think GNU linker understands the flag, but doesn't check that `local:` symbols actually exist.

**Comment by nmoinvaz** [comment]
Changed to use `-fuse-ld=lld`..

**Comment by nmoinvaz** [comment]
Looks like it is working now. It is much better, showing more errors. Whatever linker it was using before probably wasn't as thorough.

**Review by Dead2 — APPROVED** [review]
LGTM

**Review by mtl1979 — APPROVED** [review]
I see the expected result in both new CI runs.

**Pull request merged**
