### PR TITLE
Add the support for some missing cross-compile tool chains in zlib-ng

### PR DESCRIPTION
**Pull request by richael02**
Change-Id: I7b5c9acd0b3e43079e59c3da9eac161475408f83
Signed-off-by: Richael Zhuang <richael.zhuang@arm.com>

### CODE REVIEW

**Comment by Dead2** [comment]
@mtl1979 Comments?  This looks good to me, but I don't know enough about the ARM archs.

**Comment by mtl1979** [comment]
@Dead2 The problem with these kind of issues is that we would have to have the exactly same toolchains to verify that the pull request does what it is meant to do...

**Comment by richael02** [comment]
all the toolchains are available in the Linaro release index：https://releases.linaro.org/components/toolchain/binaries/5.4-2017.05/

**Comment by mtl1979** [comment]
@richael02 I only have 230 GB hard disk, so I can't install a lot of toolchains, because each is several hundred megabytes and I currently have only 47 750 606 848 bytes (44.47 GB) free disk space now... if I install too many new packages, I have no space for building applications or storing new or changed data for the current applications...

As long as all the required information is posted on the pull request, @Dead2 should be able to decide if there is good reason to include the changes or not.

**Comment by richael02** [comment]
At first we used  just AArch64 and raspberry to verify it. But later to make it work well with all arm toolchains, we set up the integrated environment in our gerrit  and verified it.

**Comment by mtl1979** [comment]
Anyone up for donating build farm for the dev team... lol... Would speed up accepting pull requests a lot ;)

**Comment by richael02** [comment]
er··· it's not what I can decide but my manager's manager··· you can discuss···

**Comment by mtl1979** [comment]
I'm not the lead developer either... @Dead2 is.... I was just making observation as individual contributor.

**Comment by richael02** [comment]
Oh··· so they can discuss~~

**Comment by Dead2** [comment]
Thanks

**Pull request merged**
