### PR TITLE
Simplify adding src files with list() cmake command

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by Dead2** [comment]
Looks good to me.
I have restarted the two errored Travis jobs.

**Comment by nmoinvaz** [comment]
Looks like the restart didn't work, might need to restart again.

**Comment by Dead2** [comment]
Travis is having serious problems with network connectivity today. A great day for testing error handling and retries, not so good for actual code testing, every commit I've done today has had multiple random failures due to this.

**Comment by mtl1979** [comment]
We might need to bitch Travis Support so they check if there is something they can do to improve... Might be overload in their network infrastructure...

**Comment by Dead2** [comment]
Their status page has been showing network outages on windows, mac and linux of varying severity for hours. IIRC, they are using Google compute for the linux VMs, so probably a complicated infrastructure (if they use a private virtual network for their VMs) to debug on.

**Comment by Dead2** [comment]
But this commit is having some other kind of problem. Restarting the failed jobs does not work, neither does restarting the whole commit. It might have exceeded its retry limit.
Could you do a force-commit?

**Comment by mtl1979** [comment]
I'm 100% sure it has exceeded the automatic retry limit as it posted a message to contact Travis Support while I was monitoring for the build status...

`Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com.`

**Comment by Dead2** [comment]
@nmoinvaz Please do a rebase, travis is behaving better today, but getting that travis-retry stuff in there should help ~if~ when something like this happens again.

**Comment by nmoinvaz** [comment]
Done

**Comment by Dead2** [comment]
Awesome :)

**Comment by Dead2** [comment]
PS: a tip about rebasing in case you (or others) don't know about it:

If you have already pulled the latest develop changes (into your local develop that is), then you can do a simple:
`git rebase develop branchXY`
That rolls back branchXY to a common point, pulls in the new commits from develop and then applies branchXY's commits on top without making a merge commit.
It does however require a force push to update github if it already has branchXY, but as long as it is a PR, nobody should really care much about the commit log when rebasing anyway.
In my opinion this makes keeping multiple branches in sync with a main branch so much easier.

Another tip I find useful for PRs is `git commit --fixup=hash`, that lets you add changes to any previous commit, not just the last one (easier to use --amend for that). You need to git add the changes first of course. This also changes the commit history, so would also need a force push. But it is great when you are working on a PR where you want to make multiple commits for ease-of-review or to separate changes, because you just know you'll need to modify those previous commits just as soon as you have made another after it. (I recommend experimenting a little with this one before using it for real, just to get a feel for how it actually works).
(It works by making a new commit at head, then rolling back, squashing it with the fixup commit, then rebasing the other commits on top of that).

**Comment by mtl1979** [comment]
"git rebase -i HEAD~&lt;n&gt;" is also useful if you want to reorder commits... &lt;n&gt; is number of latest commits you want to modify excluding the very latest commit, so it always shows n+1 commits. It does not allow replacing the very first commit of repository though and does not preserve merge or empty commits.

**Comment by nmoinvaz** [comment]
@Dead2 I'll give that a shot next time. Thanks.

**Comment by Dead2** [comment]
@nmoinvaz Ooops, I forgot part of the fixup workflow.
This is how it should be done:
```
git add <my fixed files>
git commit --fixup=OLDCOMMIT
git rebase --interactive --autosquash OLDCOMMIT^
```

**Pull request merged**
