### PR TITLE
Add one extra byte to return value of deflateBound for small lengths.

### PR DESCRIPTION
**Pull request by mtl1979**
Due to right shift by 3 in DEFLATE_QUICK_OVERHEAD() macro, the return value of deflateBound() is 1 too small for lengths smaller than 9.

See #1235.

### CODE REVIEW

**Comment by mtl1979** [comment]
```
bytes = 0, deflateBound = 23, total_out = 23
bytes = 1, deflateBound = 24, total_out = 24
bytes = 2, deflateBound = 25, total_out = 25
bytes = 3, deflateBound = 26, total_out = 26
bytes = 4, deflateBound = 27, total_out = 27
bytes = 5, deflateBound = 28, total_out = 28
bytes = 6, deflateBound = 29, total_out = 29
bytes = 7, deflateBound = 30, total_out = 30
bytes = 8, deflateBound = 31, total_out = 31
bytes = 9, deflateBound = 32, total_out = 32
bytes = 10, deflateBound = 33, total_out = 33
bytes = 11, deflateBound = 34, total_out = 34
bytes = 12, deflateBound = 35, total_out = 35
bytes = 13, deflateBound = 36, total_out = 36
bytes = 14, deflateBound = 37, total_out = 37
bytes = 15, deflateBound = 38, total_out = 38
bytes = 16, deflateBound = 39, total_out = 39
bytes = 17, deflateBound = 41, total_out = 40
bytes = 18, deflateBound = 42, total_out = 41
bytes = 19, deflateBound = 43, total_out = 42
bytes = 20, deflateBound = 44, total_out = 43
bytes = 21, deflateBound = 45, total_out = 44
bytes = 22, deflateBound = 46, total_out = 45
bytes = 23, deflateBound = 47, total_out = 46
bytes = 24, deflateBound = 48, total_out = 47
bytes = 25, deflateBound = 50, total_out = 48
bytes = 26, deflateBound = 51, total_out = 49
bytes = 27, deflateBound = 52, total_out = 50
bytes = 28, deflateBound = 53, total_out = 51
bytes = 29, deflateBound = 54, total_out = 52
bytes = 30, deflateBound = 55, total_out = 53
bytes = 31, deflateBound = 56, total_out = 54
bytes = 32, deflateBound = 57, total_out = 55
```

@Dead2 Now it returns one extra byte at lengths 17 and 25... I didn't try longer than 32 bytes input as the pattern is already clear, every 8 bytes it returns one more extra byte.

**Comment by nmoinvaz** [comment]
It would be better imo to add this to google test framework.

**Comment by mtl1979** [comment]
@nmoinvaz It's kinda work in progress... I'm not good at writing tests using google test framework...

**Comment by mtl1979** [comment]
Added test for compressBound() too, it's obvious it also would have failed with input length of 0, as I added 2 extra bytes in that case. For other lengths, there is now enough spare bytes to allow even uncompressible data. Tested with bytes filled with for loop to simulate worst case scenario.

```
bytes =  0, compressBound =  9, total_out =  8
bytes =  1, compressBound = 11, total_out =  9
bytes =  2, compressBound = 12, total_out = 10
bytes =  3, compressBound = 13, total_out = 11
bytes =  4, compressBound = 14, total_out = 12
bytes =  5, compressBound = 15, total_out = 13
bytes =  6, compressBound = 16, total_out = 14
bytes =  7, compressBound = 17, total_out = 15
bytes =  8, compressBound = 18, total_out = 16
bytes =  9, compressBound = 20, total_out = 17
bytes = 10, compressBound = 21, total_out = 18
bytes = 11, compressBound = 22, total_out = 19
bytes = 12, compressBound = 23, total_out = 20
bytes = 13, compressBound = 24, total_out = 21
bytes = 14, compressBound = 25, total_out = 22
bytes = 15, compressBound = 26, total_out = 23
bytes = 16, compressBound = 27, total_out = 24
bytes = 17, compressBound = 29, total_out = 25
bytes = 18, compressBound = 30, total_out = 26
bytes = 19, compressBound = 31, total_out = 27
bytes = 20, compressBound = 32, total_out = 28
bytes = 21, compressBound = 33, total_out = 29
bytes = 22, compressBound = 34, total_out = 30
bytes = 23, compressBound = 35, total_out = 31
bytes = 24, compressBound = 36, total_out = 32
bytes = 25, compressBound = 38, total_out = 33
bytes = 26, compressBound = 39, total_out = 34
bytes = 27, compressBound = 40, total_out = 35
bytes = 28, compressBound = 41, total_out = 36
bytes = 29, compressBound = 42, total_out = 37
bytes = 30, compressBound = 43, total_out = 38
bytes = 31, compressBound = 44, total_out = 39
bytes = 32, compressBound = 45, total_out = 40
```

**Review by Dead2 — APPROVED** [review]

**Pull request merged**
