### PR TITLE
abicheck.sh: implement --refresh-if option as documented.

### PR DESCRIPTION
**Pull request by dankegel**
Fixes a sad little typo I didn't catch when submitting abicheck.sh initially.
Keeps the misspelled option for compatibility.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
I don't think we need to keep backwards compatibility for this script so if you want to just rename it that would be good too.

**Comment by dankegel** [comment]
kudos on having a good shell checker in CI, it found a no-op assignment!

**Comment by dankegel** [comment]
Should be ready for re-review.

**Review by mtl1979 — APPROVED** [review]
LGTM

**Review by Dead2 — APPROVED** [review]

**Pull request merged**
