### PR TITLE
Add MIPS64 to GitHub workflows.

### PR DESCRIPTION
**Pull request by mtl1979**
Should fail configure during creating dependency information before #1505 is merged.

Compliments #1506.

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]
LGTM

**Review by Dead2 — APPROVED** [review]
Needs to exit draft, but looks good to me.

**Comment by mtl1979** [comment]
> Needs to exit draft, but looks good to me.

Will undraft this when previous PRs are merged to avoid conflicts due to modifying same part of the workflow files.

**Comment by mtl1979** [comment]
Rebased and undrafted.

**Pull request merged**
