### PR TITLE
[MinGW] Disable GCC warning about using MS format specifiers in ISO C conformant code

### PR DESCRIPTION
**Pull request by mtl1979**
`-Wno-pedantic-ms-format` was introduced in GCC 4.5 for MinGW, so we don't need to test if that is supported as minimum we support is GCC 4.8.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
I kind of think we should change the `printf` statements to use inttypes.h definitions instead.

**Comment by mtl1979** [comment]
> inttypes.h

`ll` format specifier isn't supported on Windows, so using `inttypes.h` doesn't fix anything.

**Comment by nmoinvaz** [comment]
Looks like we already do use inttypes.h. Here are the warnings.
```c
zlib-ng/test/infcover.c: In function ‘mem_used’:
zlib-ng/test/infcover.c:1[83](https://github.com/zlib-ng/zlib-ng/actions/runs/3289136191/jobs/5420314359#step:11:84):21: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
  183 |     fprintf(stderr, "%s: %" PRIu64 " allocated\n", prefix, (uint64_t)zone->total);
      |                     ^~~~~~~
zlib-ng/test/infcover.c:183:21: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
zlib-ng/test/infcover.c: In function ‘mem_high’:
zlib-ng/test/infcover.c:190:21: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
  190 |     fprintf(stderr, "%s: %" PRIu64 " high water mark\n", prefix, (uint64_t)zone->highwater);
      |                     ^~~~~~~
zlib-ng/test/infcover.c:190:21: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
zlib-ng/test/infcover.c: In function ‘mem_done’:
zlib-ng/test/infcover.c:214:25: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
  214 |         fprintf(stderr, "** %s: %" PRIu64 " bytes in %d blocks not freed\n",
      |                         ^~~~~~~~~~
zlib-ng/test/infcover.c:214:25: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]

zlib-ng/tools/makecrct.c: In function ‘write_table64’:
zlib-ng/tools/makecrct.c:143:16: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
  143 |         printf("%s0x%016" PRIx64 "%s", n == 0 || n % 3 ? "" : "    ",
      |                ^~~~~~~~~~
zlib-ng/tools/makecrct.c:143:16: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
zlib-ng/test/fuzz/fuzzer_example_large.c: In function ‘test_large_inflate’:
zlib-ng/test/fuzz/fuzzer_example_large.c:108:25: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
  108 |         fprintf(stderr, "bad large inflate: %" PRIu64 "\n", (uint64_t)d_stream.total_out);
      |                         ^~~~~~~~~~~~~~~~~~~~~~
zlib-ng/test/fuzz/fuzzer_example_large.c:108:25: warning: ISO C does not support the ‘I64’ ms_printf length modifier [-Wformat=]
```

**Review by nmoinvaz — APPROVED** [review]

**Comment by nmoinvaz** [comment]
Looks good. I'm not so sure we need the `-D_POSIX_C_SOURCE=200809L` on the `CFLAGS` anymore - looks like we already have it in zbuild.h. But that's a separate issue..

**Comment by mtl1979** [comment]
> Looks good. I'm not so sure we need the `-D_POSIX_C_SOURCE=200809L` on the `CFLAGS` anymore - looks like we already have it in zbuild.h. But that's a separate issue..

We should only need to specify values on command-line that are higher than the defaults we assume in headers. The most common reason is when one operating system or toolset requires higher version than others, as we need to make sure the definition is correct before including any system headers. I try to make cleanup related pull requests once in a while so we have as little warnings emitted as possible when we are preparing a new release.

My main focus has been VC++, MinGW, MSYS and Cygwin since the early days, but I will also participate in some arch-dependent issues and features.

**Pull request merged**
