### PR TITLE
2.1.4 Release

### PR DESCRIPTION
**Pull request by Dead2**
- Fix: inflateCopy() allocate window with padding #1583
- Pull zlib 1.3 changes #1563

- API
  - Deprecate ZLIBNG_VER_STATUS, use ZLIBNG_VER_STATUSH #1581

- MacOS
  - Relocatable pkg config files, @rpath/<libraryname> install name on macOS #1546

- MinGW
  - MinGW32 build fixes #1499
  - Support llvm-mingw toolchain #1570

- ARM
  - Optimize slide_hash for ARMv6 #1538
  - Handle ARM64EC #1539
  - Remove inert check for HAVE_ACLE_FLAG in check_acle_compiler_flag #1554
  - Clean up ARM detection and allow ACLE on all ARM archs #1567

- Loongarch
  - Initial loongarch port #1537

- PowerPC
  - Fix building benchmarks on 32-bit PowerPC #1588

- RVV
  - Optimize adler32 using rvv #1532
  - Optimize chunkset #1568
  - Support RVV hwcap detect at runtime #1585
 
- x86
  - Move the AVX compatibility functions into a separate file #1540
  - Clean up SSE4.2 support, fixes compile issues under docker/VM #1542

- Buildsystem
  - Improve intrinsics detection: ensure intrinsics are not optimized out #1562
  - CMake: Fix cross-compiling benchmarks and libpng #1589
  - CMake: Fix examining value of GENERATOR_IS_MULTI_CONFIG #1575
  - CMake: Fix Match CMAKE_GENERATOR_TOOLSET #1577
  - CMake: Cleanup handling of march=native #1544 #1578
  - CMake: Add CPack capability #1556 #1579
  - Configure: Remove march=native support #1555
  - Configure: use dash not bash #1561
  - Configure: Fix disabling deflate_quick and deflate_medium #1545
  - Configure: Fix distclean #1530

- Misc
  - Added symbol versioning support for having multiple versions of functions #1396
  - Simplify deflate stream/state check #1502
  - Clean up __msan_unpoison() usage #1534
  - Fix spellings, typos and etc #1549 #1550 #1551 #1552 #1553

### CODE REVIEW

**Review by KungFuJesus — APPROVED** [review]
LGTM.

**Review by iii-i — APPROVED** [review]
I did some testing and fuzzing on s390x, everything is looking good.

**Comment by mtl1979** [comment]
Does not build.... Benchmarks can't find crc32_power8()...

**Review by mtl1979 — CHANGES_REQUESTED** [review]
Missing #1588.

**Review by nmoinvaz — APPROVED** [review]

**Comment by mtl1979** [comment]
When cross-compiling for 32-bit ARM, I get:

```
CMake Error at test/benchmarks/CMakeLists.txt:75 (add_subdirectory):
  add_subdirectory called with incorrect number of arguments
```

I will try to figure out which ones of the variables are empty...

**Comment by mtl1979** [comment]
Now that the benchmark apps should compile with cross-compiler, we might consider enable building benchmarks for more CI runs to make sure no change in code can break build for older processors, especially 32-bit platforms. There is still quite many bugs in non-x86 64-bit kernels and applications that makes it more sense to run 32-bit kernel on 64-bit machine, even if it limits the available memory amount... On my test machine I have 2 GB of memory, but barely 256 MB is used.

**Pull request merged**
