### PR TITLE
Add details on how to successfully build on Apple Silicon

### PR DESCRIPTION
**Pull request by Developer-Ecosystem-Engineering**
Details on how to successfully build zlib-ng on Apple Silicon

### CODE REVIEW

**Comment by nmoinvaz** [comment]
I don't think the repository is the right place for this. I recommend adding it to the Wiki page.

**Comment by gdevenyi** [comment]
We definitely should keep an eye on github providing CI bits so we can test this build though.

**Comment by Developer-Ecosystem-Engineering** [comment]
Cool, sounds like I can just move it to the wiki?

**Comment by Developer-Ecosystem-Engineering** [comment]
I've added it to the wiki, does that look good? I can close this then!

**Comment by nmoinvaz** [comment]
Great thank you!

**Pull request closed without merging**
