### PR TITLE
Remove deflate_state dependency from crc_folding.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by Dead2** [comment]
### Baseline 834e7d83eae9ff7bfb1b9769d9f311ea7ca8e746 aarch64
```
   text    data     bss     dec     hex filename
 105194    1576      16  106786   1a122 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.746/2.764/2.780/0.011        0.965/0.993/1.015/0.013       42,618,858
 2     43.879%      2.819/2.851/2.870/0.017        0.563/0.601/0.631/0.022       20,714,938
 3     42.383%      3.713/3.758/3.780/0.020        0.565/0.580/0.592/0.008       20,008,755
 4     41.660%      2.768/2.802/2.818/0.015        0.353/0.372/0.381/0.008       13,111,391
 5     41.216%      3.014/3.031/3.051/0.012        0.365/0.375/0.383/0.005       12,971,746
 6     41.039%      3.505/3.539/3.555/0.014        0.358/0.372/0.384/0.009       12,916,025
 7     40.778%      2.239/2.270/2.284/0.011        0.168/0.175/0.181/0.004        6,416,924
 8     40.704%      2.769/2.800/2.809/0.010        0.168/0.179/0.188/0.007        6,405,244
 9     40.696%      2.983/3.016/3.029/0.013        0.160/0.172/0.180/0.007        6,404,084

 avg1  42.947%                        2.981                          0.424
 tot                                402.450                         57.285      141,567,965
```

### PR #1010 49d2dab61b0f72f9d277d6648588f08abc3168c7 aarch64
```
   text    data     bss     dec     hex filename
 105194    1576      16  106786   1a122 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.746/2.768/2.795/0.014        0.962/0.989/1.003/0.013       42,618,858
 2     43.879%      2.820/2.844/2.862/0.013        0.564/0.595/0.611/0.014       20,714,938
 3     42.383%      3.708/3.759/3.782/0.020        0.556/0.584/0.601/0.013       20,008,755
 4     41.660%      2.759/2.793/2.821/0.019        0.361/0.378/0.387/0.007       13,111,391
 5     41.216%      3.005/3.030/3.049/0.013        0.347/0.373/0.389/0.012       12,971,746
 6     41.039%      3.511/3.540/3.559/0.015        0.338/0.361/0.377/0.011       12,916,025
 7     40.778%      2.248/2.272/2.283/0.010        0.164/0.176/0.190/0.008        6,416,924
 8     40.704%      2.785/2.804/2.815/0.008        0.172/0.182/0.188/0.005        6,405,244
 9     40.696%      2.998/3.017/3.027/0.011        0.160/0.173/0.184/0.008        6,404,084

 avg1  42.947%                        2.981                          0.423
 tot                                402.405                         57.154      141,567,965
```

No measurable change with GCC 8.3 at least, it might be that it does a similar optimization locally.

**Comment by nmoinvaz** [comment]
That is good. I didn't think it would hurt performance only help in instances where maybe the compiler wasn't smart. But this PR is necessary if we ever plan to make use of these functions in `inflate`.

**Comment by nmoinvaz** [comment]
@Dead2 these changes utilize x86 not aarch64.

**Comment by Dead2** [comment]
@nmoinvaz Hah, I managed to get that crossed it seems. I'll re-do soon (TM)

**Comment by Dead2** [comment]
### Baseline 21050e06c511a67f3239d1bca444616be6853bfe x86-64
```
   text    data     bss     dec     hex filename
 115241    1416      32  116689   1c7d1 libz-ng.so.2

Activated multiple generated file mode. Source: ../silesia-small.tar
Level 1: /tmp/deflatebench-1.tmp  465.2 MiB   487,825,920 B
Level 2: /tmp/deflatebench-2.tmp  270.1 MiB   283,253,760 B
Level 3: /tmp/deflatebench-3.tmp  225.1 MiB   236,044,800 B
Level 4: /tmp/deflatebench-4.tmp  180.1 MiB   188,835,840 B
Level 5: /tmp/deflatebench-5.tmp  165.1 MiB   173,099,520 B
Level 6: /tmp/deflatebench-6.tmp  135.1 MiB   141,626,880 B
Level 7: /tmp/deflatebench-7.tmp  105.1 MiB   110,154,240 B
Level 8: /tmp/deflatebench-8.tmp   90.0 MiB    94,417,920 B
Level 9: /tmp/deflatebench-9.tmp   75.0 MiB    78,681,600 B

 Tool: minigzip   Levels: 1-9
 Runs: 40         Trim worst: 20

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.165%      2.892/2.928/2.946/0.017        1.661/1.669/1.678/0.005      264,231,515
 2     43.875%      2.974/3.002/3.015/0.010        0.984/1.002/1.017/0.010      124,277,644
 3     42.382%      3.003/3.018/3.032/0.009        0.786/0.812/0.825/0.011      100,039,412
 4     41.669%      2.718/2.737/2.743/0.007        0.622/0.634/0.645/0.006       78,685,354
 5     41.215%      2.868/2.911/2.926/0.016        0.568/0.578/0.585/0.006       71,342,944
 6     41.036%      2.763/2.776/2.785/0.007        0.441/0.469/0.478/0.009       58,118,026
 7     40.781%      2.717/2.735/2.742/0.007        0.358/0.367/0.371/0.004       44,921,649
 8     40.702%      2.996/3.009/3.017/0.007        0.297/0.313/0.321/0.007       38,429,965
 9     40.698%      2.783/2.795/2.801/0.005        0.247/0.259/0.266/0.006       32,021,745

 avg1  42.947%                        2.879                          0.678
 tot                                518.191                        122.066      812,068,254
```

### PR #1010 c0a630124308178fb74a67c165f020a2dfc31977
```
   text    data     bss     dec     hex filename
 115265    1416      32  116713   1c7e9 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.165%      2.887/2.920/2.938/0.014        1.629/1.668/1.685/0.015      264,231,515
 2     43.875%      2.940/2.980/2.996/0.015        0.974/1.005/1.015/0.011      124,277,644
 3     42.382%      2.988/3.005/3.021/0.009        0.786/0.808/0.820/0.009      100,039,412
 4     41.669%      2.730/2.748/2.760/0.010        0.616/0.636/0.645/0.008       78,685,354
 5     41.215%      2.861/2.889/2.909/0.013        0.565/0.583/0.591/0.008       71,342,944
 6     41.036%      2.769/2.783/2.793/0.007        0.448/0.472/0.481/0.008       58,118,026
 7     40.781%      2.714/2.732/2.741/0.006        0.358/0.367/0.375/0.005       44,921,649
 8     40.702%      2.996/3.015/3.021/0.006        0.304/0.316/0.321/0.005       38,429,965
 9     40.698%      2.780/2.793/2.800/0.005        0.253/0.261/0.266/0.004       32,021,745

 avg1  42.947%                        2.874                          0.680
 tot                                517.314                        122.334      812,068,254
```

Code size is a little bigger.
Compression is on average 0.17% faster, decompression is 0.22% slower. Neither of these might be accurate.

**Comment by nmoinvaz** [comment]
That's acceptable imo.

**Pull request merged**
