### PR TITLE
Fix build of optimized functions with LTO

### PR DESCRIPTION
**Pull request by viccie30**
When building zlib-ng with LTO enabled, at least GCC doesn't respect the flags of each source file and just throws all the flags together. See https://gcc.gnu.org/onlinedocs/gccint/LTO-object-file-layout.html.

Because of this, flags don't get applied correctly to the arch-specific files, leading to problems like #722.

CMake does not allow disabling LTO per source file, so in `CMakeLists.txt` I just added `-fno-lto` if the compiler is GCC-like and native mode is not enabled.
For the configure script I wrote the same logic, but using an extra variable in `arch/*/Makefile.in`.

### CODE REVIEW

**Comment by viccie30** [comment]
I tested this patch using `sbuild` on all supported Debian architectures (amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, and s390x) on stable, testing, unstable, and experimental, both with and without LTO and for static and shared builds. 

For all combinations, except mips64el and mipsel on experimental due to dependency breakage, the builds succeed and all tests pass (using `qemu-user-static` for the non-x86 architectures).

**Comment by Dead2** [comment]
I think this override should perhaps not be active if the user enables Native mode, native is obviously useless for redistribution such as in distros, but it can be useful for those who compile locally and want the (possibly) fastest end result.

When native mode is enabled, all files are compiled with the same flags, essentially enabling all instruction sets the local cpu supports, so that should allow it to work with LTO.

**Comment by viccie30** [comment]
I agree, that's why both in `configure` and `CMakeLists.txt` the no lto flag is only defined if native mode is disabled

**Comment by Dead2** [comment]
Hah, indeed it is, I didn't notice that. 👍

**Comment by viccie30** [comment]
It took me a few tries to get that right as well, but I think I did the right way round

**Review by Dead2 — APPROVED** [review]

**Pull request merged**
