### PR TITLE
Add optional support for thread local storage.

### PR DESCRIPTION
**Pull request by nmoinvaz**
It is possible to predefine `ZTHREAD` to disable thread local storage.
```
cmake . -DCMAKE_C_FLAGS=-DZTHREAD=
```

I used `ZTHREAD` to coincide with `ZEXPORT` and `ZEXTERN`.

See #570 for previous discussion.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Do we want it named `ZTHREAD` or `Z_THREAD`. I mean there are a bunch of other #define's in zlib headers that use `Z_*` - more do than don't. Perhaps on another PR we can synchronize everything.

**Comment by gdevenyi** [comment]
Should this be a cmake advanced feature rather than a explicit define?

**Comment by nmoinvaz** [comment]
I thought about that but I don't want to keep stuffing CMake with all these advanced options if they won't hardly be used. I already made that mistake with the advanced inflate options to be honest.

**Comment by mtl1979** [comment]
ZTHREAD is OK for me... I agree with @nmoinvaz That very rarely used optional features, especially ones that are enabled by default, don't warrant using cmake's advanced features... On the other hand, if we ever want to reverse so that TLS support is disabled by default, then we might want to use something like USE_TLS, so different keywords for different compilers are automatically used correctly.

**Comment by Dead2** [comment]
I'd kind of like to see this disabled by default, so if someone wants it enabled they will have to explicitly do that.
zlib/zlib-ng is not supposed to be thread safe after all, so even having this makes little sense to me.
If someone can come up with a (realistic) regression test that fails with this disabled, I'd like to see that of course.

Only legitimate use-case I can think of right now is if someone wanted to do multi-threaded hashing using zlib-ng, but is that really something we should support by default? IIRC inflate and deflate still won't be able to work multi-threaded.

Or do you disagree?

If we keep it enabled, I would have liked to have a regression test for it in CI, since we don't really have any idea whether it works or not.

**Comment by mtl1979** [comment]
Multi-threaded hashing would make sense with image manipulation... Things like Qt use libpng extensively and is multi-threaded by design...

**Comment by Dead2** [comment]
@mtl1979 Yes, but does it fail with zlib-ng without TLS? If it does, then yes, that would be a regression and we should keep it.
If it does not, then I don't see the point of introducing it.

**Comment by mtl1979** [comment]
@Dead2 It's not so much about failing, but making sure it always calls the right variation... There is small moment when it is possible that it calls non-optimized version if previous thread hasn't returned from feature detection yet.

**Comment by Dead2** [comment]
Yeah, my question is about whether that is actually our problem or should the program calling zlib/zlib-ng make sure it gets it right? Can we say we are partially thread-safe and get away with not dealing with any more of that, or does that open the door to 'we need completely-thread-safe' (explicitly or implied).

**Comment by mtl1979** [comment]
@Dead2 My personal opinion is that partially thread-safe is enough... Most likely completely thread-safe deflate/inflate is wishful thinking and not realistic...

**Comment by Dead2** [comment]
Maybe rename it to Z_TLS?
IMO I think we should move towards the Z_ prefix. And TLS makes more sense than THREAD in this case, also THREAD is bound to make someone think that we support threads 😛

**Comment by nmoinvaz** [comment]
I have renamed it to `Z_TLS`. And @Dead2 you said you want it disabled by default, so I have done that. If somebody wants it they can use:
```
cmake . -DCMAKE_C_FLAGS=-DZ_TLS=__thread
```

**Comment by Dead2** [comment]
I see no changes in output, no change to performance, but compiled code size goes down a lot, and data goes down as well.

## Baseline a19bbdeec892b1ff8210bd8c3b679cca77ad042d
```
   text    data     bss     dec     hex filename
  93151    1272      32   94455   170f7 libz-ng.so.1
```
## PR #733 44fdfcf36f6b4c03e202afc6a3647eba03b8fd79
```
   text    data     bss     dec     hex filename
  91255    1232      32   92519   16967 libz-ng.so.1
```

**Pull request merged**
