### PR TITLE
[WIP] Upgrade to clang-9 for scan build

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by gdevenyi** [comment]
Going a different direction here, going to add a proper --warn option to cmake

**Comment by Dead2** [comment]
You are doing duplicate and conflicting work here currently. You might want to hold off on this until my travis/cmake PR has been merged. (Or at least rebase it on top of that for WIP work)

**Comment by gdevenyi** [comment]
Thanks for the heads up, will take a look.

**Comment by gdevenyi** [comment]
Will definitely wait for your changes to drop before doing my updates. Thanks!

**Pull request closed without merging**
