### PR TITLE
[minigzip] Close gzFile before exiting on error.

### PR DESCRIPTION
**Pull request by mtl1979**
ASAN will complain if gzFile is not closed before program exits.

### CODE REVIEW

**Review by Dead2 — APPROVED** [review]
LGTM

**Comment by Dead2** [comment]
I think a PR for the same change on develop would be a good idea.
Not sure why it didn't already trigger the same error there though.

**Comment by mtl1979** [comment]
> I think a PR for the same change on develop would be a good idea. Not sure why it didn't already trigger the same error there though.

It took me a while to be able to reproduce the issue locally... I had to run each test individually instead of through `ctest`.

**Comment by Dead2** [comment]
I cherry-picked this since it would have otherwise needed a rebase.

**Pull request closed without merging**
