### PR TITLE
Added ARM-Neon optimized fill_window

### PR DESCRIPTION
**Pull request by JunHe77**
Use ARM neon saturating substraction to do the hash code rebase process. This eliminates the "if" branch and can process more data in one loop.

### CODE REVIEW

**Comment by JunHe77** [comment]
Got it. Already updated. Could you pls help to have a check? Thanks a lot!

**Comment by mtl1979** [comment]
We can't merge this in yet due to overlap in code. Only @Dead2 can handle the issue as I don't have adequate permissions.

**Comment by Dead2** [comment]
First of all, thank you for your work on this pull request.

However you should rebase your branch against the hacknslash7 branch, since that is currently the staging area for our current focus on Arm optimization. However it seems like some of your code is overlapping/conflicting with existing code already there, and possibly some already being prepared for merge by ARM engineers (PR #102).

The hacknslash7 branch already has a fill_window_arm.c, and your code seems to have some improved neon code, so if you could instead try to merge your improvements into the existing code, that would be great. 👍

**Comment by JunHe77** [comment]
Hi, Dead2,
I've merged code to PR #106.  Pls let me know for further actions. Thanks.

**Comment by mtl1979** [comment]
@Dead2 This can be closed, we will continue discussion on PR #106.

**Pull request closed without merging**
