### PR TITLE
Add MIPS to GitHub workflows.

### PR DESCRIPTION
**Pull request by mtl1979**
Expected to fail configure during creating dependency information before #1505 is merged.

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]
Nice work LGTM

**Comment by Dead2** [comment]
Interestingly it succeeds the build and self-tests. It does print the grep error, but continues normally it seems.

**Review by Dead2 — APPROVED** [review]

**Comment by mtl1979** [comment]
> Interestingly it succeeds the build and self-tests. It does print the grep error, but continues normally it seems.

It only fails if make is run twice, because it won't cleanup build correctly due to missing rule in `arch/generic` and bad dependency rules... I might add new test to run make twice to make sure generated Makefile is sane.

**Comment by Dead2** [comment]
> It only fails if make is run twice, because it won't cleanup build correctly due to missing rule in `arch/generic` and bad dependency rules... I might add new test to run make twice to make sure generated Makefile is sane.

Right. I don't think it is really necessary, at least not for more than 1 CI run. (Not one for each arch, I think we can live without that extra load)

**Comment by mtl1979** [comment]
> > It only fails if make is run twice, because it won't cleanup build correctly due to missing rule in `arch/generic` and bad dependency rules... I might add new test to run make twice to make sure generated Makefile is sane.
> 
> Right. I don't think it is really necessary, at least not for more than 1 CI run. (Not one for each arch, I think we can live without that extra load)

It would affect all builds using configure so would need to be in all such CI runs to catch regressions... Build times would double and that is unacceptable in my professional opinion as we are still going to phase out building with configure in near future.

**Pull request merged**
