### PR TITLE
Added prefixes to zlib functions for dual zlib/zlib-ng linking.

### PR DESCRIPTION
**Pull request by nmoinvaz**
This pull requests adds PREFIX() to certain functions to allow for dual linking both zlib & zlib-ng.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
One thing I am not so sure of is, it uses PREFIX() in zutil.h, which means everything will need to also include zbuild.h. Perhaps we should add include zbuild.h to the top of zutil.h? Or just nuke zbuild.h altogether and include its contents in zutil.h. My opinion is to do the later.

**Comment by mtl1979** [comment]
zbuild.h is supposed to be build-time private header... All external and user code is supposed to hard-code those prefixes instead of relying on checking if compatibility mode is defined. No new code is supposed to use compatibility mode, it's just to get old code working when stock zlib is not needed.

**Comment by nmoinvaz** [comment]
Hmm. Not sure what to do because PREFIX() is still needed whenever including zutil.h. What do you think? Leave as is? Another option would be to move zbuild.h into zutil.h but do this

```
#if !defined(ZNG_USERDEFINED_BUILD)
# if defined(ZLIB_COMPAT)
#  define PREFIX(x)  x
#  define PREFIX2(x) ZLIB_ ## x
#  define PREFIX3(x) z_ ## x
#  define PREFIX4(x) _ ## x
#  define PREFIX5(x) z ## x
#  define zVersion   zlibVersion
#  define z_size_t   unsigned long
# else
#  define PREFIX(x)  zng_ ## x
#  define PREFIX2(x) ZLIBNG_ ## x
#  define PREFIX3(x) zng_ ## x
#  define PREFIX4(x) zng_ ## x
#  define PREFIX5(x) zng_ ## x
#  define zVersion   zlibng_version
#  define z_size_t   size_t
# endif
#endif
```

So, if anybody wanted to they could define their own PREFIX() macros by setting #define ZNG_USERDEFINED_BUILD and PREFIX() before including zutil.h. This is just an idea.

**Comment by mtl1979** [comment]
If zutil.h is externally visible, we need to make separate version for it like we have done for other similar headers... so zutil.h and zutil-ng.h ...

**Comment by nmoinvaz** [comment]
I see what you are saying, zutil.h is not externally visible so it shouldn't matter. Ok, no need for any changes then I think. I think that makes sense why gzendian.h code is not in zutil.h also.

**Comment by mtl1979** [comment]
The idea of being able to disable or override those prefixes has been in my mind too... I just haven't had time to finish implementing the feature properly... Basically it requires having third copy of those externally visible header file pairs, because some data types are incompatible and as such we can't just reuse the header files for compatibility mode.

**Comment by nmoinvaz** [comment]
I could do another PR that would address that issue. What about something similar to this:

- Move zbuild.h contents into zutil.h
- In zutil.h include zbuild.h if ZNG_BUILD_PARAMS was set:

```
#if defined(ZNG_BUILD_PARAMS)
# include "zbuild.h"
#else
# if defined(ZLIB_COMPAT)
#  define PREFIX(x)  x
#  define PREFIX2(x) ZLIB_ ## x
#  define PREFIX3(x) z_ ## x
#  define PREFIX4(x) _ ## x
#  define PREFIX5(x) z ## x
#  define zVersion   zlibVersion
#  define z_size_t   unsigned long
# else
#  define PREFIX(x)  zng_ ## x
#  define PREFIX2(x) ZLIBNG_ ## x
#  define PREFIX3(x) zng_ ## x
#  define PREFIX4(x) zng_ ## x
#  define PREFIX5(x) zng_ ## x
#  define zVersion   zlibng_version
#  define z_size_t   size_t
# endif
#endif
```
Just throwing around ideas.

**Comment by mtl1979** [comment]
Moving things to zutil.h is bad as the macros should be defined in user code before including any zlib-ng headers...

**Comment by nmoinvaz** [comment]
But if doing that, it won't affect any source code internally that includes zutil.h correct?

**Comment by mtl1979** [comment]
For it to work correctly, zlib-ng would have to be statically linked to the binary... Otherwise it would cause linker errors. This also means that the build system for zlib-ng needs to support overriding the prefix.

**Comment by Dead2** [comment]
# Regarding custom prefixes
I think stock zlib supports compiling with a separate prefix, IIRC.
If we want to support custom prefixes, I guess that can be done relatively easily. But it only makes sense to do so in zlib-ng mode I think, and that means having only 2 different prefix-parameters, since the rest of them are identical.

I just reviewed PREFIX2, and I am thinking that might possibly be superfluous. I might be wrong but my immediate thought is that we should always use ZLIBNG_VERSION for checking shared-lib compatibility. If that holds true, then we can remove PREFIX2 and simplify our own set of prefixes to only a single variant, thus also making it easier to support custom prefixes.
Stock zlib requires you to edit zlib.h manually to add prefixes IIRC, and that is probably fine for us too. But if we had a way to generate it, that would be more elegant of course, and would also allow us to remove the two slightly different copies we have today.

**Comment by Dead2** [comment]
Now, regarding this PR. I think we might be slightly off track with this one.
Most of the functions and other symbols in this PR are internal ones, that we do not export as part of our API. This means that we can freely rename them, and there is no need to use the complicated prefix method.
So, why not just rename them and add a static 'zng_' prefix?

**Comment by nmoinvaz** [comment]
I have created a new pull request that should do exactly that.

**Pull request closed without merging**
