### PR TITLE
Obtained more ILP with VMX by breaking a data dependency

### PR DESCRIPTION
**Pull request by KungFuJesus**
By unrolling and finding the equivalent recurrence relation here, we can
do more independent sums, maximizing ILP.  For when the data size fits
into cache, we get a sizable return.  For when we don't, it's minor but
still measurable.

Testing was done on a quad Powermac G5 at 2.5Ghz.

### CODE REVIEW

**Comment by KungFuJesus** [comment]
```
Comparing adler32/vmx (from ./benchmark_zlib_old) to adler32/vmx (from ./benchmark_zlib)
Benchmark                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------
[adler32/vmx vs. adler32/vmx]/2048                          -0.3929         -0.3929           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3929         -0.3929           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3930         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3929         -0.3929           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3939         -0.3934           369           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3930         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3929         -0.3929           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3930         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3931         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048                          -0.3930         -0.3929           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/2048_mean                     -0.3931         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048_median                   -0.3930         -0.3930           368           223           368           223
[adler32/vmx vs. adler32/vmx]/2048_stddev                   -0.8987         -0.8111             0             0             0             0
[adler32/vmx vs. adler32/vmx]/2048_cv                       -0.8331         -0.6888             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4096                          -0.4280         -0.4280           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4281         -0.4280           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4279         -0.4279           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4280         -0.4280           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4278         -0.4279           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4281         -0.4280           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4277         -0.4278           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4278         -0.4278           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4275         -0.4275           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096                          -0.4280         -0.4280           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/4096_mean                     -0.4279         -0.4279           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096_median                   -0.4279         -0.4279           710           406           710           406
[adler32/vmx vs. adler32/vmx]/4096_stddev                   +0.6264         +0.9685             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4096_cv                       +1.8428         +2.4408             0             0             0             0
[adler32/vmx vs. adler32/vmx]/32768                         -0.4217         -0.4218          5526          3196          5526          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4218         -0.4218          5526          3195          5526          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4218         -0.4218          5526          3195          5526          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4221         -0.4221          5529          3195          5528          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4216         -0.4217          5526          3196          5525          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4217         -0.4217          5525          3195          5525          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4216         -0.4217          5526          3196          5526          3195
[adler32/vmx vs. adler32/vmx]/32768                         -0.4220         -0.4220          5526          3194          5526          3194
[adler32/vmx vs. adler32/vmx]/32768                         -0.4219         -0.4219          5525          3194          5525          3194
[adler32/vmx vs. adler32/vmx]/32768                         -0.4220         -0.4220          5526          3194          5526          3194
[adler32/vmx vs. adler32/vmx]/32768_pvalue                   0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/32768_mean                    -0.4218         -0.4219          5526          3195          5526          3195
[adler32/vmx vs. adler32/vmx]/32768_median                  -0.4218         -0.4218          5526          3195          5526          3195
[adler32/vmx vs. adler32/vmx]/32768_stddev                  -0.2004         -0.3855             1             1             1             1
[adler32/vmx vs. adler32/vmx]/32768_cv                      +0.3829         +0.0628             0             0             0             0
[adler32/vmx vs. adler32/vmx]/262144                        -0.4222         -0.4221         44273         25582         44267         25581
[adler32/vmx vs. adler32/vmx]/262144                        -0.4218         -0.4219         44262         25590         44260         25585
[adler32/vmx vs. adler32/vmx]/262144                        -0.4221         -0.4221         44267         25582         44266         25581
[adler32/vmx vs. adler32/vmx]/262144                        -0.4221         -0.4221         44267         25582         44266         25582
[adler32/vmx vs. adler32/vmx]/262144                        -0.4220         -0.4220         44267         25587         44266         25584
[adler32/vmx vs. adler32/vmx]/262144                        -0.4220         -0.4221         44269         25586         44268         25583
[adler32/vmx vs. adler32/vmx]/262144                        -0.4221         -0.4221         44265         25580         44264         25580
[adler32/vmx vs. adler32/vmx]/262144                        -0.4221         -0.4221         44268         25582         44267         25582
[adler32/vmx vs. adler32/vmx]/262144                        -0.4221         -0.4221         44267         25583         44266         25582
[adler32/vmx vs. adler32/vmx]/262144                        -0.4222         -0.4222         44270         25581         44269         25580
[adler32/vmx vs. adler32/vmx]/262144_pvalue                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/262144_mean                   -0.4221         -0.4221         44267         25584         44266         25582
[adler32/vmx vs. adler32/vmx]/262144_median                 -0.4221         -0.4221         44267         25582         44266         25582
[adler32/vmx vs. adler32/vmx]/262144_stddev                 +0.0802         -0.3375             3             3             2             2
[adler32/vmx vs. adler32/vmx]/262144_cv                     +0.8691         +0.1464             0             0             0             0
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0810         -0.0810        633108        581795        633077        581771
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0818         -0.0818        633562        581728        633549        581717
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0811         -0.0811        632934        581596        632920        581585
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0811         -0.0811        632777        581447        632763        581435
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0817         -0.0816        633204        581497        633122        581486
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0816         -0.0815        633289        581607        633191        581596
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0812         -0.0812        633154        581770        633142        581759
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0807         -0.0807        632900        581804        632888        581793
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0812         -0.0812        632923        581512        632910        581500
[adler32/vmx vs. adler32/vmx]/2097152                       -0.0812         -0.0814        633142        581724        633129        581610
[adler32/vmx vs. adler32/vmx]/2097152_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/2097152_mean                  -0.0813         -0.0813        633099        581648        633069        581625
[adler32/vmx vs. adler32/vmx]/2097152_median                -0.0813         -0.0813        633125        581666        633100        581603
[adler32/vmx vs. adler32/vmx]/2097152_stddev                -0.4165         -0.4113           228           133           219           129
[adler32/vmx vs. adler32/vmx]/2097152_cv                    -0.3649         -0.3592             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0840         -0.0840       1291396       1182923       1291328       1182860
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0843         -0.0843       1291998       1183085       1291944       1183032
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0840         -0.0841       1291930       1183400       1291905       1183222
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0837         -0.0837       1291900       1183791       1291872       1183768
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0841         -0.0842       1291803       1183168       1291779       1183016
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0845         -0.0845       1291875       1182754       1291850       1182731
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0840         -0.0842       1292195       1183658       1292168       1183354
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0844         -0.0843       1292177       1183078       1292007       1183055
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0845         -0.0843       1292080       1182913       1291785       1182889
[adler32/vmx vs. adler32/vmx]/4194304                       -0.0841         -0.0842       1291595       1183019       1291570       1182838
[adler32/vmx vs. adler32/vmx]/4194304_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/4194304_mean                  -0.0842         -0.0842       1291895       1183179       1291821       1183077
[adler32/vmx vs. adler32/vmx]/4194304_median                -0.0842         -0.0842       1291915       1183082       1291861       1183024
[adler32/vmx vs. adler32/vmx]/4194304_stddev                +0.3413         +0.3101           250           336           233           306
[adler32/vmx vs. adler32/vmx]/4194304_cv                    +0.4646         +0.4306             0             0             0             0
OVERALL_GEOMEAN                                             -0.3215         -0.3215             0             0             0             0
```

**Comment by KungFuJesus** [comment]
Ah just found a slightly better way by tracking 2 independent sums so that the vsum4ubs instructions are not wasted but are not stalled waiting for data.  It requires tracking even more independent sums but it's well worth it.

```
Comparing adler32/vmx (from ./benchmark_zlib_old) to adler32/vmx (from ./benchmark_zlib)
Benchmark                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------
[adler32/vmx vs. adler32/vmx]/2048                          -0.4433         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4433         -0.4432           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4432         -0.4432           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4433         -0.4432           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4434         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4433         -0.4432           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4433         -0.4432           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4435         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4434         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048                          -0.4434         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/2048_mean                     -0.4433         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048_median                   -0.4434         -0.4433           368           205           368           205
[adler32/vmx vs. adler32/vmx]/2048_stddev                   -0.4062         -0.2915             0             0             0             0
[adler32/vmx vs. adler32/vmx]/2048_cv                       +0.0667         +0.2726             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4096                          -0.4879         -0.4878           702           360           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4879         -0.4878           702           360           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4879         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4878         -0.4878           702           360           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4882         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4879         -0.4878           702           360           702           359
[adler32/vmx vs. adler32/vmx]/4096                          -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096_pvalue                    0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/4096_mean                     -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096_median                   -0.4880         -0.4879           702           359           702           359
[adler32/vmx vs. adler32/vmx]/4096_stddev                   -0.7707         -0.4352             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4096_cv                       -0.5521         +0.1029             0             0             0             0
[adler32/vmx vs. adler32/vmx]/32768                         -0.4918         -0.4917          5527          2809          5526          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4916         -0.4916          5527          2810          5526          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4916          5527          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4916          5527          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4916         -0.4916          5526          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4916         -0.4916          5526          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4917          5527          2809          5526          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4917          5527          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4917          5527          2809          5526          2809
[adler32/vmx vs. adler32/vmx]/32768                         -0.4917         -0.4917          5527          2809          5525          2808
[adler32/vmx vs. adler32/vmx]/32768_pvalue                   0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/32768_mean                    -0.4917         -0.4917          5527          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768_median                  -0.4917         -0.4917          5527          2809          5525          2809
[adler32/vmx vs. adler32/vmx]/32768_stddev                  -0.3848         +0.1385             0             0             0             0
[adler32/vmx vs. adler32/vmx]/32768_cv                      +0.2103         +1.2398             0             0             0             0
[adler32/vmx vs. adler32/vmx]/262144                        -0.4850         -0.4850         44249         22787         44242         22787
[adler32/vmx vs. adler32/vmx]/262144                        -0.4866         -0.4854         44381         22787         44278         22786
[adler32/vmx vs. adler32/vmx]/262144                        -0.4851         -0.4850         44254         22785         44242         22785
[adler32/vmx vs. adler32/vmx]/262144                        -0.4851         -0.4850         44256         22786         44244         22786
[adler32/vmx vs. adler32/vmx]/262144                        -0.4853         -0.4852         44269         22787         44259         22786
[adler32/vmx vs. adler32/vmx]/262144                        -0.4853         -0.4852         44272         22787         44260         22786
[adler32/vmx vs. adler32/vmx]/262144                        -0.4853         -0.4852         44272         22787         44261         22787
[adler32/vmx vs. adler32/vmx]/262144                        -0.4853         -0.4852         44275         22790         44262         22787
[adler32/vmx vs. adler32/vmx]/262144                        -0.4855         -0.4852         44297         22790         44261         22787
[adler32/vmx vs. adler32/vmx]/262144                        -0.4853         -0.4852         44273         22787         44260         22786
[adler32/vmx vs. adler32/vmx]/262144_pvalue                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/262144_mean                   -0.4854         -0.4851         44280         22787         44257         22786
[adler32/vmx vs. adler32/vmx]/262144_median                 -0.4853         -0.4852         44272         22787         44260         22786
[adler32/vmx vs. adler32/vmx]/262144_stddev                 -0.9591         -0.9412            38             2            11             1
[adler32/vmx vs. adler32/vmx]/262144_cv                     -0.9206         -0.8858             0             0             0             0
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1104         -0.1101        640383        569710        639997        569511
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1099         -0.1096        639887        569586        639504        569392
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1098         -0.1097        640091        569819        639711        569544
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1103         -0.1100        640002        569404        639615        569231
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1103         -0.1100        640087        569499        639680        569316
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1099         -0.1096        639933        569629        639548        569424
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1095         -0.1092        639947        569860        639532        569721
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1103         -0.1100        640152        569521        639742        569368
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1105         -0.1103        640072        569325        639732        569183
[adler32/vmx vs. adler32/vmx]/2097152                       -0.1099         -0.1097        639945        569601        639605        569430
[adler32/vmx vs. adler32/vmx]/2097152_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/2097152_mean                  -0.1101         -0.1098        640050        569595        639667        569412
[adler32/vmx vs. adler32/vmx]/2097152_median                -0.1101         -0.1098        640037        569593        639648        569408
[adler32/vmx vs. adler32/vmx]/2097152_stddev                +0.1705         +0.0872           145           170           144           156
[adler32/vmx vs. adler32/vmx]/2097152_cv                    +0.3152         +0.2214             0             0             0             0
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1483         -0.1481       1361071       1159237       1360656       1159179
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1481         -0.1478       1360858       1159359       1360430       1159306
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1478         -0.1475       1360691       1159593       1360265       1159571
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1478         -0.1476       1360498       1159420       1360094       1159395
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1486         -0.1483       1361625       1159221       1361058       1159196
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1482         -0.1480       1360790       1159113       1360359       1159087
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1488         -0.1485       1362038       1159388       1361606       1159364
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1478         -0.1476       1360374       1159302       1359942       1159278
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1472         -0.1471       1360659       1160310       1360231       1160158
[adler32/vmx vs. adler32/vmx]/4194304                       -0.1476         -0.1474       1360869       1159946       1360428       1159923
[adler32/vmx vs. adler32/vmx]/4194304_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
[adler32/vmx vs. adler32/vmx]/4194304_mean                  -0.1480         -0.1478       1360947       1159489       1360507       1159446
[adler32/vmx vs. adler32/vmx]/4194304_median                -0.1480         -0.1478       1360824       1159373       1360394       1159335
[adler32/vmx vs. adler32/vmx]/4194304_stddev                -0.2795         -0.3013           515           371           493           345
[adler32/vmx vs. adler32/vmx]/4194304_cv                    -0.1543         -0.1801             0             0             0             0
OVERALL_GEOMEAN                                             -0.3809         -0.3808             0             0             0             0
```

**Comment by nmoinvaz** [comment]
Nice work again!

**Comment by KungFuJesus** [comment]
@mtl1979 You should see a benefit on your G4, I think.

**Comment by mtl1979** [comment]
> @mtl1979 You should see a benefit on your G4, I think.

I'm seeing 2.7~4.7% gain in speed depending on data length. But I don't really trust the Google benchmark...

**Comment by KungFuJesus** [comment]
> > @mtl1979 You should see a benefit on your G4, I think.
> 
> I'm seeing 2.7~4.7% gain in speed depending on data length. But I don't really trust the Google benchmark...

Why's that?  They have seemingly correlated with the exact performance gains I've been measuring via python's interface to the zlib adler checksum.

I suspect I could apply all of these optimizations to POWER 8 as well but I don't have any hardware to test it on.

**Comment by mtl1979** [comment]
> > I'm seeing 2.7~4.7% gain in speed depending on data length. But I don't really trust the Google benchmark...
> 
> Why's that?  They have seemingly correlated with the exact performance gains I've been measuring via python's interface to the zlib adler checksum.
> 
> I suspect I could apply all of these optimizations to POWER 8 as well but I don't have any hardware to test it on.

When I did the first benchmarking, I used a lot longer data lengths so rounding wouldn't increase error margin. I don't know how much I need to stress 7400 before it runs out of memory bandwidth, but I'm seeing 100 ns error margin when the whole test takes around 2900 ns. I know how small 1 ns is as my ears have 3 ns resolution.

**Comment by KungFuJesus** [comment]
Generally you'll see a bimodal distribution at your L1 and L2 cache sizes.  For me, my L2 caches are actually shared between all 4 nodes on the G5 but probably have hella latency for it.  With this recent change, I'm actually marginally faster than my core 2 quad with sse41 right up until about 2MB, and then the Core 2 quad becomes faster.  The Core 2 Quad is about 2x faster from that point forward because it has a split L2 cache shared between I'm guessing 2 pairs of cores, but it's 6MB large (probably ~3MB of L2 per NUMA node).  

This optimization I actually could apply to the x86 code, along with the method this code is doing to force alignment (makes a big difference pre-nehalem).  It's actually quite difficult for me to time the delta now with Python for these smaller sizes that fit nicely into cache because evaluating the stack frame in Python from within a loop and getting the info from the timing functions skews things out to microseconds instead of nanoseconds.

I've seen fairly reliable timing data from the google benchmarks around the couple hundred nanosecond time.  Once you get to < 20 ns it's really tricky to get reliable and consistent timing (as is the case with the compare256 benchmarks).  I imagine you're probably fighting some limits in the higher resolution timers by that point, too.

**Comment by mtl1979** [comment]
100 MHz bus speed should mean 10 ns resolution, assuming there is only one cycle latency. Even in the best case scenario, that would equal to 160 ns waiting for data to be fetched from or stored to RAM.

**Comment by KungFuJesus** [comment]
Well the stuff that's fitting into cache definitely is in cache when this runs. Temporally and spatially, it's a sequential stride through the data and the test loop is repeated over a million times for the smaller loops until the timing becomes consistent. So even if it wasn't entirely in cache lines, it is eventually.

**Comment by mtl1979** [comment]
The gains I'm seeing are barely within error margins, so I'm thinking it doesn't get cache miss at all...

**Comment by KungFuJesus** [comment]
> The gains I'm seeing are barely within error margins, so I'm thinking it doesn't get cache miss at all...

No, and it shouldn't by the way the benchmarking library is designed.  The G4's pipeline is not a notoriously deep as the G5's, the gains on that last commit were almost entirely due to extending out the instruction level parallelism.  Apple themselves even mentioned once upon a time in their optimization guidelines that for the G5, you may need to unroll much more than you needed to for the G4:

http://mirror.informatimago.com/next/developer.apple.com/hardware/ve/g5.html
http://mirror.informatimago.com/next/developer.apple.com/technotes/tn/tn2087.html

The gains you are seeing on your CPU are likely due to a tiny bit more overlap allowed by breaking a dependency chain but it's not likely going to be like it is on the G5 that tries to schedule a couple hundred instructions in flight and does some sort of scoreboarding for it.  This of course has a latency cost to it and it's one of the reasons that deeper pipelines tend to be avoided.  That same mirror of documentation has the G5 simulator app screenshotted in there that shows the depth of the pipeline versus all of the different phases of the execution.  

But in any case, the good news is that it doesn't hurt the older CPU it just helps the PPC970 more :).

**Review by Dead2 — APPROVED** [review]

**Pull request merged**
