### PR TITLE
Improvements and fixes for cmake unit tests.

### PR DESCRIPTION
**Pull request by nmoinvaz**
I just noticed this while I was in there..

### CODE REVIEW

**Comment by Dead2** [comment]
I have noticed a couple days ago that if you run ctest with verbose, it looks like it complains about failing to decompress files. Perhaps that is just this bug.
But that raises a question about why the tests don't flag as failed, because even though it output error messages it was still showing all tests as successful.

Does minigzip fail to output error codes in some cases perhaps?

**Comment by nmoinvaz** [comment]
I have fixed some issues with the unit tests, I wasn't previously checking the exit code when calling `execute_process` in `test-compress.cmake`.

These additional commits should resolve #728.

**Comment by Dead2** [comment]
Beginning to look really good, but still fails a few tests
```
The following tests FAILED:
	615 - minigzip-detect-text-A (Failed)
	616 - minigzip-detect-binary-A (Failed)
Errors while running CTest
	628 - GH-536-segfault (Failed)
	629 - GH-536-incomplete-read (Failed)
	630 - GH-536-zero-stored-block (Failed)
```

**Comment by Dead2** [comment]
Plan is to tag our first Beta once this is merged, unless something new and important shows up before then.

**Comment by nmoinvaz** [comment]
I'm not quite sure what is causing some of these issues... maybe #763?

* Ubuntu MinGW fails on `makefixed`, `maketrees` and `makecrct` odd.

**Comment by mtl1979** [comment]
When generating files, most common cause is mismatch in line-endings... Would be easier if it would print the differing bytes in the log...

**Comment by nmoinvaz** [comment]
I agree, it is too bad cmake doesn't have anything that prints differences. There might be some python package that does it...

**Comment by nmoinvaz** [comment]
For my last commit https://github.com/zlib-ng/zlib-ng/pull/761/commits/ee1f27a91ea9ca50c892aed8b4375a0c0cc2f4ff I could move the `SET_BINARY_MODE` into `zutil.h`.

**Comment by nmoinvaz** [comment]
A lot of these issues are only found by testing the [corpora](https://github.com/nmoinvaz/corpora) repository. I'm glad I added that. Perhaps we can move the repo to zlib-ng organization..

**Comment by nmoinvaz** [comment]
Rebased

**Comment by mtl1979** [comment]
This fixes the failures with generated files... It makes sure git checks out using LF instead of CRLF...
```
diff --git a/.gitattributes b/.gitattributes
index 68ec3a17..88672d65 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,4 +1,4 @@
 * text=auto
-*.c text
-*.h text
+*.c eol=lf
+*.h eol=lf
 Makefile text
```

**Comment by nmoinvaz** [comment]
Ok @Dead2 and @mtl1979 this is ready for review.

**Comment by mtl1979** [comment]
I don't see anything obvious that should still be fixed... CI is pretty much stalled on coverity uploads...

**Comment by Dead2** [comment]
## Baseline cf14b8e255452e55b92f2e8e4b4cbd25961433ca
```
   text    data     bss     dec     hex filename
 112457    1376      32  113865   1bcc9 libz-ng.so.1

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.781%      1.291/1.314/1.323/0.007        0.857/0.883/0.893/0.009      127,296,397
 2     43.874%      1.238/1.263/1.271/0.008        0.453/0.461/0.467/0.004       48,329,132
 3     42.490%      1.310/1.326/1.333/0.006        0.375/0.386/0.392/0.006       40,118,068
 4     41.472%      1.279/1.291/1.298/0.005        0.308/0.314/0.321/0.004       32,630,864
 5     41.212%      1.383/1.404/1.410/0.006        0.293/0.310/0.316/0.005       32,425,995
 6     41.037%      1.308/1.324/1.330/0.006        0.239/0.248/0.252/0.004       25,831,160
 7     40.784%      1.282/1.292/1.298/0.005        0.170/0.183/0.187/0.004       19,253,737
 8     40.706%      1.099/1.110/1.113/0.003        0.113/0.122/0.127/0.003       12,811,166
 9     40.695%      1.223/1.230/1.234/0.003        0.110/0.121/0.127/0.005       12,807,941

 avg1  43.339%                        1.284                          0.336
 tot                                346.589                         90.791      351,504,460

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.781%      1.301/1.312/1.320/0.006        0.860/0.887/0.893/0.008      127,296,397
 2     43.874%      1.249/1.265/1.273/0.007        0.453/0.463/0.467/0.004       48,329,132
 3     42.490%      1.319/1.330/1.336/0.005        0.369/0.387/0.392/0.005       40,118,068
 4     41.472%      1.277/1.294/1.302/0.006        0.305/0.314/0.318/0.004       32,630,864
 5     41.212%      1.392/1.402/1.407/0.004        0.296/0.310/0.316/0.006       32,425,995
 6     41.037%      1.309/1.327/1.333/0.006        0.239/0.248/0.252/0.004       25,831,160
 7     40.784%      1.280/1.291/1.296/0.004        0.174/0.184/0.187/0.003       19,253,737
 8     40.706%      1.095/1.108/1.111/0.003        0.117/0.122/0.127/0.003       12,811,166
 9     40.695%      1.215/1.228/1.233/0.004        0.113/0.121/0.127/0.004       12,807,941

 avg1  43.339%                        1.284                          0.337
 tot                                346.677                         91.078      351,504,460
```

## PR #761 f7de7e6bd91863507a534e78465b8bfa995236ce
```
   text    data     bss     dec     hex filename
 112521    1376      32  113929   1bd09 libz-ng.so.1

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.781%      1.279/1.316/1.325/0.011        0.860/0.883/0.893/0.008      127,296,397
 2     43.874%      1.246/1.259/1.265/0.006        0.447/0.462/0.470/0.006       48,329,132
 3     42.490%      1.310/1.319/1.325/0.004        0.372/0.386/0.392/0.005       40,118,068
 4     41.472%      1.284/1.300/1.307/0.005        0.295/0.312/0.318/0.006       32,630,864
 5     41.212%      1.395/1.402/1.407/0.004        0.296/0.309/0.316/0.005       32,425,995
 6     41.037%      1.321/1.330/1.337/0.004        0.235/0.246/0.252/0.005       25,831,160
 7     40.784%      1.288/1.298/1.303/0.004        0.170/0.181/0.187/0.005       19,253,737
 8     40.706%      1.106/1.113/1.118/0.004        0.113/0.124/0.127/0.003       12,811,166
 9     40.695%      1.224/1.232/1.237/0.004        0.117/0.123/0.127/0.003       12,807,941

 avg1  43.339%                        1.286                          0.336
 tot                                347.092                         90.772      351,504,460

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.781%      1.287/1.312/1.321/0.008        0.870/0.887/0.896/0.008      127,296,397
 2     43.874%      1.241/1.259/1.267/0.007        0.443/0.463/0.470/0.008       48,329,132
 3     42.490%      1.301/1.323/1.331/0.007        0.376/0.387/0.395/0.005       40,118,068
 4     41.472%      1.288/1.298/1.305/0.006        0.301/0.312/0.318/0.005       32,630,864
 5     41.212%      1.399/1.411/1.416/0.005        0.296/0.309/0.316/0.006       32,425,995
 6     41.037%      1.317/1.329/1.334/0.004        0.241/0.248/0.252/0.003       25,831,160
 7     40.784%      1.288/1.296/1.301/0.003        0.170/0.183/0.190/0.004       19,253,737
 8     40.706%      1.102/1.112/1.116/0.004        0.113/0.122/0.127/0.003       12,811,166
 9     40.695%      1.223/1.230/1.235/0.003        0.113/0.121/0.123/0.003       12,807,941

 avg1  43.339%                        1.286                          0.337
 tot                                347.097                         90.946      351,504,460
```

No changes to output sizes.
Slightly bigger Text size.
Slightly slower compression, might be caused by code placement.

**Comment by nmoinvaz** [comment]
> Slightly slower compression, might be caused by code placement.

It could be due to the ASAN fix.. https://github.com/zlib-ng/zlib-ng/pull/761/commits/9c11109cf7067fbc7181e57885241a24da8443e9.

Now I am thinking this particular check should be in `quick_insert_string` and `insert_string`. It should check to make sure the value it returns is < `strstart`. I can move both ASAN commits into a separate PR..

**Comment by mtl1979** [comment]
@nmoinvaz Isn't `hash_head` only from `quick_insert_string` as `insert_string` doesn't return anything anymore...

**Comment by nmoinvaz** [comment]
Oh yes that is correct, so only needs to be fixed for `quick_insert_string`.

**Comment by nmoinvaz** [comment]
I have removed the ASAN error fixes into separate PRs, some checks may still fail due to this. This was done to isolate ctest/cmake changes from source code changes. I think this PR should be merged before ASAN error PRs.

**Comment by Dead2** [comment]
Github Actions made a path change at some point, breaking coverage data.
Please rebase this and other PRs for a fresh CI re-run.

**Comment by nmoinvaz** [comment]
Rebased

**Comment by nmoinvaz** [comment]
Very cool! Thanks for merging

**Pull request merged**
