### PR TITLE
Allow ACLE to be enabled on all ARM architecture versions

### PR DESCRIPTION
**Pull request by ccawley2011**
This allows the ACLE code to be built on the Raspberry Pi, which uses ARMv6 as a baseline.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Is there a similar line in `configure` script that needs to be updated?

**Comment by KungFuJesus** [comment]
I thought that the raspberry pi's withheld the optional ACLE instructions.  Maybe it was just the AES ones?

**Comment by mtl1979** [comment]
@nmoinvaz As far as I remember, configure has own tests for each 32-bit ARM processor version and we only allow enabling ACLE for ARMv8 and embedded.

We don't allow enabling ACLE for other processor versions as it can cause run-time crashes as we don't do run-time checks for ACLE because the hashing function will use ACLE CRC32 instruction when enabled.

**Comment by KungFuJesus** [comment]
Ahh, looks like Pi >= 3 has the CRC32 instructions, at least.

**Comment by mtl1979** [comment]
Generally, toolchain files should be used with cmake when targeting anything else than the default compiler target... The toolchain file will override various cmake variables including the default architecture and processor. With configure, we support using `CHOST` environment variable to override the default toolchain.

**Comment by Dead2** [comment]
Sounds to me like ACLE should perhaps be a compile time opt-in on ARM2-7.
And perhaps `ACLE` is the wrong define to use for this, and renaming it to `ACLE-CRC32` might be better? That would also allow ACLE code not requiring CRC32 to be added/used.

**Comment by nmoinvaz** [comment]
> And perhaps ACLE is the wrong define to use for this, and renaming it to ACLE-CRC32 might be better? That would also allow ACLE code not requiring CRC32 to be added/used.

I think if we need to turn off ACLE-CRC32 specifically, we would just add a flag for that. No reason to change all the flag names to be super specific right now.

**Comment by Dead2** [comment]
> > And perhaps ACLE is the wrong define to use for this, and renaming it to ACLE-CRC32 might be better? That would also allow ACLE code not requiring CRC32 to be added/used.
> 
> I think if we need to turn off ACLE-CRC32 specifically, we would just add a flag for that. No reason to change all the flag names to be super specific right now.

Nono, what I meant was that possibly we should have both `ACLE` and  `ACLE-CRC32`, if that could allow us to use ACLE in more situations rather than the entirety of `ACLE` being dependent on the CRC32 instruction as well.

I said rename because I do not know the `ACLE` specific code at all, and if all our `ACLE` code currently needs CRC32, then it would be misleading to have that depend on `ACLE` without any mention of CRC32 also being required for that. If we have `ACLE` code that does not need CRC32, then we should probably have both defines.

**Comment by mtl1979** [comment]
Is there any specific ACLE instructions besides CRC32 ones that would make zlib-ng better and faster? Or is this just yet another "my way is better" discussion...

**Comment by KungFuJesus** [comment]
> Is there any specific ACLE instructions besides CRC32 ones that would make zlib-ng better and faster? Or is this just yet another "my way is better" discussion...

In theory the carryless multiplications (aka polynomial) can be leveraged like they are on x86 to do wider chains. In practice it's rarely faster than the crc32 instruction on most arm implementations. It's likely m1 might be an exception to that rule. 

I know the one that once existed in the Linux kernel has since been ripped out because of that realization.

Still CRC32, but by a different means using different ACLE instructions.

**Comment by mtl1979** [comment]
I've been around since early days of zlib-ng and I've seen pull requests getting merged and then later reverted, because something else was faster and better... I know I come out as a bitch, but we've wasted a lot of time due to issues that should have taken just few hours of our time if properly done. I can however say that I've learnt a lot during the time I worked on zlib-ng.

I'm not big fan of benchmarks as those can be deceptive if not tested with real-life data instead of just pseudo-random patterns. Benchmarks also depend heavily on the processor and other hardware that runs them.

**Comment by Dead2** [comment]
In any case, what I'd like to avoid is people mistakenly enabling ACLE,  their CPU supports it after all, without being warned it also requires the CRC32 instructions that might not work on their CPU, especially if that results in hard-to-understand crashes. If the user thought they did everything right, it'll only result in support requests and a bad reputation.

As long as the naming + documentation makes it clear what is actually required without being misleading, all is good.

Therefore, to me, it seems misleading to have this under `ACLE` define if it will not run on all ACLE cpus. Documented in a place where it actually is seen by the user (in CMake/Configure parameters help for example, not just wiki or readme) would mitigate that for the most part though.

**Comment by mtl1979** [comment]
@Dead2 It's up to compiler to throw error if the targeted CPU doesn't support specific intrinsics... That is why we don't currently enable ACLE for older processors except when targeting embedded, as base target for embedded toolchain is ARMv2, but it supports a lot more modern specification versions.

For anything older than ARMv8, we would need to add specific compiler flag that enables supported ACLE instructions, so compile-time tests would work correctly.

**Comment by Dead2** [comment]
> @Dead2 It's up to compiler to throw error if the targeted CPU doesn't support specific intrinsics...

**Comment by Dead2** [comment]
Sorry, hit the wrong button. 🙄

**Comment by ccawley2011** [comment]
> We don't allow enabling ACLE for other processor versions as it can cause run-time crashes as we don't do run-time checks for ACLE because the hashing function will use ACLE CRC32 instruction when enabled.

> For anything older than ARMv8, we would need to add specific compiler flag that enables supported ACLE instructions, so compile-time tests would work correctly.

From what I can tell, zlib-ng already does both of these things. Am I missing something?

**Comment by mtl1979** [comment]
> > We don't allow enabling ACLE for other processor versions as it can cause run-time crashes as we don't do run-time checks for ACLE because the hashing function will use ACLE CRC32 instruction when enabled.
> 
> > For anything older than ARMv8, we would need to add specific compiler flag that enables supported ACLE instructions, so compile-time tests would work correctly.
> 
> From what I can tell, zlib-ng already does both of these things. Am I missing something?

Currently zlib-ng forces ARMv8 when ACLE is used, so it won't work with older processors.

**Comment by nmoinvaz** [comment]
> Is there a similar line in `configure` script that needs to be updated?

What about this?

https://github.com/zlib-ng/zlib-ng/blob/750a7a014a3e41d5663fc73fbedfb8eeab6603fe/configure#L1706-L1711

**Comment by ccawley2011** [comment]
Closing this in favour of PR #1567.

**Pull request closed without merging**
