### PR TITLE
Fixed running cmake tests on arm

### PR DESCRIPTION
**Pull request by nmoinvaz**
See #426.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Also notice the double #if define(define(..))

**Comment by Dead2** [comment]
I just fixed the double defined myself :)
Could you remove (amend) that and push again please?

**Comment by Dead2** [comment]
Oh, and do it against develop, then I'll rebase on top of that when this goes in first.

**Comment by nmoinvaz** [comment]
See #432

**Pull request closed without merging**
