### PR TITLE
Allow overridde CMAKE_CXX_* variables and fix overridde CMAKE_C_*

### PR DESCRIPTION
**Pull request by phprus**
Fix for issue #1785

Allow overridde ``CMAKE_CXX_*``.
Define ``CMAKE_C_*`` variables only if it is not defined instead of if it are ``False``.

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]
LGTM

**Review by Dead2 — APPROVED** [review]

**Comment by FantasqueX** [comment]
Hi, thanks for your work. I can build zlib-ng successfully on ArchLinux. However, I cannot build it successfully on OpenSUSE Tumbleweed. ArchLinux's gtest package contains
```
gtest /usr/lib/cmake/GTest/GTestConfig.cmake
gtest /usr/lib/cmake/GTest/GTestConfigVersion.cmake
gtest /usr/lib/cmake/GTest/GTestTargets-none.cmake
gtest /usr/lib/cmake/GTest/GTestTargets.cmake
```
while OpenSUSE Tumbleweed doesn't. On OpenSUSE, CMake finds gtest by [MODULE](https://github.com/Kitware/CMake/blob/master/Modules/FindGTest.cmake) which doesn't define `CMAKE_CXX_STANDARD`.

**Comment by mtl1979** [comment]
@FantasqueX Finding by module is deprecated, so the issue should be reported to OpenSuSE packager.

**Comment by FantasqueX** [comment]
I have issued a bug report to OpenSUSE https://bugzilla.opensuse.org/show_bug.cgi?id=1232917

**Pull request merged**
