### PR TITLE
Write generated files during tests to CMake's build directory.

### PR DESCRIPTION
**Pull request by nmoinvaz**
See #920 for background.

### CODE REVIEW

**Comment by phprus** [comment]
Writing temporary test files to CMake build directory:

```
Index: CMakeLists.txt
===================================================================
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -1146,7 +1146,7 @@
                 "-DCOMPRESS_ARGS=${compress_args}"
                 "-DDECOMPRESS_ARGS=-d;-c"
                 -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/${path}
-                -DOUTPUT=${CMAKE_CURRENT_SOURCE_DIR}/${path}-${test_id}.gz
+                -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/${path}-${test_id}.gz
                 -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)
         endif()
     endmacro()
@@ -1209,6 +1209,7 @@
         "-DTARGET=${MINIGZIP_COMMAND}"
         "-DCOMPRESS_ARGS=-c;-k;-4"
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/GH-361/test.txt
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/GH-361/test.txt
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-364
@@ -1217,6 +1218,7 @@
         "-DCOMPRESS_ARGS=1;5;9;3"
         "-DDECOMPRESS_TARGET=${MINIGZIP_COMMAND}"
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/GH-364/test.bin
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/GH-364/test.bin
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-382
@@ -1226,6 +1228,7 @@
         "-DDECOMPRESS_ARGS=-c;-d;-m;1;-w;-15"
         -DGZIP_VERIFY=OFF
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/GH-382/defneg3.dat
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/GH-382/defneg3.dat
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-536-segfault
@@ -1236,6 +1239,7 @@
         -DCOMPARE=OFF
         -DGZIP_VERIFY=OFF
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/data/lcet10.txt
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/data/lcet10.txt
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-536-incomplete-read
@@ -1246,6 +1250,7 @@
         -DCOMPARE=OFF
         -DGZIP_VERIFY=OFF
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/data/lcet10.txt
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/data/lcet10.txt
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-536-zero-stored-block
@@ -1256,6 +1261,7 @@
         -DCOMPARE=OFF
         -DGZIP_VERIFY=OFF
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/data/lcet10.txt
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/data/lcet10.txt
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_test(NAME GH-751
@@ -1262,6 +1268,7 @@
         COMMAND ${CMAKE_COMMAND}
         "-DTARGET=${MINIGZIP_COMMAND}"
         -DINPUT=${CMAKE_CURRENT_SOURCE_DIR}/test/GH-751/test.txt
+        -DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/test/GH-751/test.txt
         -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/test-compress.cmake)

     add_simple_test_executable(deflate_quick_bi_valid)
Index: cmake/test-compress.cmake
===================================================================
--- cmake/test-compress.cmake
+++ cmake/test-compress.cmake
@@ -60,6 +60,8 @@
     set(OUTPUT ${OUTPUT}-${UNIQUE_ID})
 endif()
 string(REPLACE ".gz" "" OUTPUT "${OUTPUT}")
+get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
+file(MAKE_DIRECTORY "${OUTPUT_DIR}")

 macro(cleanup)
     # Cleanup temporary mingizip files
```

**Comment by nmoinvaz** [comment]
It looks like I missed some files. I'm not sure if I want it to keep the directory structure.

**Comment by mtl1979** [comment]
@nmoinvaz Preserving the directory structure is useful if several tests have same filename for output... It also makes it easier to find any relevant temporary and output files if something goes wrong...

**Comment by nmoinvaz** [comment]
The test-compress CMake script already generates unique file names so that shouldn't be a problem.

**Comment by nmoinvaz** [comment]
I have included recent changes from @phprus by modifying `test-compress.cmake` to take a parameter called `TEST_NAME` and always build the output files in `CMAKE_CURRENT_BINARY_DIR`. It didn't make sense specifying the `OUTPUT` variable for this CMake test script since the output files always had some kind of extension added to it so the `OUTPUT` variable was not actually the output file - and the fact that there are multiple files written out during the test aided in that decision.

Files written (and later cleaned up) during test-compress tests look like this now:

image

Also `OUTPUT` script variable was never defined in the comments for `test-compress.cmake`.

**Pull request merged**
