### PR TITLE
Remove duplicated codecov parameter

### PR DESCRIPTION
**Pull request by phprus**
Remove duplicated ``codecov`` parameter.
Bug appeared in PR #1662.

### CODE REVIEW

**Comment by Dead2** [comment]
Instead, I think it should be renamed to `ubuntu_gcc_native_inst_avx`.

**Comment by phprus** [comment]
@Dead2 Renamed.

**Review by Dead2 — APPROVED** [review]

**Review by mtl1979 — APPROVED** [review]
LGTM

**Comment by nmoinvaz** [comment]
nit: Probably could use a better commit message, but otherwise LGTM.

**Pull request merged**
