### PR TITLE
Fixes for CI and UBSAN

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by Dead2** [comment]
I would love it if you could squash the three sanitizer ci commits into one.
Other than that, this looks great.

**Comment by nmoinvaz** [comment]
Rebased and squashed.

**Comment by nmoinvaz** [comment]
@iii-i any thoughts on this one for `infcover`?
```
2022-03-18T18:13:26.5447156Z 2: inflate init: 8976 allocated
2022-03-18T18:13:26.5451191Z 2: /home/actions-runner/_work/zlib-ng/zlib-ng/arch/s390/dfltcc_inflate.c:138:5: runtime error: null pointer passed as argument 1, which is declared to never be null
2022-03-18T18:13:26.5455643Z 2:     #0 0x102ffed in dfltcc_inflate_disable (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x102ffed)
2022-03-18T18:13:26.5459479Z 2:     #1 0x1014c25 in inflatePrime (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1014c25)
2022-03-18T18:13:26.5463011Z 2:     #2 0x1000d6d in main (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1000d6d)
2022-03-18T18:13:26.5466716Z 2:     #3 0x1072eb1 in __libc_start_main (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1072eb1)
2022-03-18T18:13:26.5470194Z 2:     #4 0x1001943  (/home/actions-runner/_work/zlib-ng/zlib-ng/infcover+0x1001943)
```
https://github.com/zlib-ng/zlib-ng/runs/5604807137?check_suite_focus=true

**Comment by nmoinvaz** [comment]
@KungFuJesus looks like some signed overflow issues in AVX512 code using `gtest`:
```
2022-03-18T18:25:04.3129569Z /usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:15496:3: runtime error: signed integer overflow: 1384379311 + 1074632061 cannot be represented in type 'int'
2022-03-18T18:25:04.3130273Z     #0 0x5644ceab7a22 in adler32_avx512 (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x38ca22)
2022-03-18T18:25:04.3130877Z     #1 0x5644cea745d4 in read_buf (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x3495d4)
2022-03-18T18:25:04.3131478Z     #2 0x5644cea862ca in deflate_stored (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x35b2ca)
2022-03-18T18:25:04.3132067Z     #3 0x5644cea70423 in zng_deflate (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x345423)
2022-03-18T18:25:04.3132746Z     #4 0x5644cea09250 in deflate_params_Test::TestBody() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x2de250)
2022-03-18T18:25:04.3133709Z     #5 0x5644cec5cbe3 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x531be3)
2022-03-18T18:25:04.3134670Z     #6 0x5644ceb7aa7e in testing::Test::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x44fa7e)
2022-03-18T18:25:04.3135310Z     #7 0x5644ceb7ba35 in testing::TestInfo::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x450a35)
2022-03-18T18:25:04.3135954Z     #8 0x5644ceb7d043 in testing::TestSuite::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x452043)
2022-03-18T18:25:04.3136669Z     #9 0x5644cebf386d in testing::internal::UnitTestImpl::RunAllTests() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x4c886d)
2022-03-18T18:25:04.3137815Z     #10 0x5644cec59fd3 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x52efd3)
2022-03-18T18:25:04.3138929Z     #11 0x5644ceb746ea in testing::UnitTest::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x4496ea)
2022-03-18T18:25:04.3139543Z     #12 0x5644cea61091 in RUN_ALL_TESTS() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x336091)
2022-03-18T18:25:04.3140229Z     #13 0x5644ce984720 in main (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x259720)
2022-03-18T18:25:04.3140792Z     #14 0x7fbac0d5d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2022-03-18T18:25:04.3141971Z     #15 0x5644ce98626d in _start (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x25b26d)
```

**Comment by nmoinvaz** [comment]
@Dead2 I don't think this PR should be held up by the sanitizer failures. If it gets merged then people can do their own testing based on `develop` more easily.

**Comment by KungFuJesus** [comment]
> @KungFuJesus looks like some signed overflow issues in AVX512 code using `gtest`:
> 
> ```
> 2022-03-18T18:25:04.3129569Z /usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:15496:3: runtime error: signed integer overflow: 1384379311 + 1074632061 cannot be represented in type 'int'
> 2022-03-18T18:25:04.3130273Z     #0 0x5644ceab7a22 in adler32_avx512 (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x38ca22)
> 2022-03-18T18:25:04.3130877Z     #1 0x5644cea745d4 in read_buf (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x3495d4)
> 2022-03-18T18:25:04.3131478Z     #2 0x5644cea862ca in deflate_stored (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x35b2ca)
> 2022-03-18T18:25:04.3132067Z     #3 0x5644cea70423 in zng_deflate (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x345423)
> 2022-03-18T18:25:04.3132746Z     #4 0x5644cea09250 in deflate_params_Test::TestBody() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x2de250)
> 2022-03-18T18:25:04.3133709Z     #5 0x5644cec5cbe3 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x531be3)
> 2022-03-18T18:25:04.3134670Z     #6 0x5644ceb7aa7e in testing::Test::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x44fa7e)
> 2022-03-18T18:25:04.3135310Z     #7 0x5644ceb7ba35 in testing::TestInfo::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x450a35)
> 2022-03-18T18:25:04.3135954Z     #8 0x5644ceb7d043 in testing::TestSuite::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x452043)
> 2022-03-18T18:25:04.3136669Z     #9 0x5644cebf386d in testing::internal::UnitTestImpl::RunAllTests() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x4c886d)
> 2022-03-18T18:25:04.3137815Z     #10 0x5644cec59fd3 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x52efd3)
> 2022-03-18T18:25:04.3138929Z     #11 0x5644ceb746ea in testing::UnitTest::Run() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x4496ea)
> 2022-03-18T18:25:04.3139543Z     #12 0x5644cea61091 in RUN_ALL_TESTS() (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x336091)
> 2022-03-18T18:25:04.3140229Z     #13 0x5644ce984720 in main (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x259720)
> 2022-03-18T18:25:04.3140792Z     #14 0x7fbac0d5d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
> 2022-03-18T18:25:04.3141971Z     #15 0x5644ce98626d in _start (/home/runner/work/zlib-ng/zlib-ng/test/gtest_zlib+0x25b26d)
> ```

Interesting...a line number would be helpful.  That number can and does fit into an unsigned integer - I wonder if this is a case there the load is intentionally treated as signed for the sake that apart from a few instructions that are treated differently for sign extension, the signed and unsigned operations are exactly the same in hardware.

**Comment by mtl1979** [comment]
@KungFuJesus Could be `sum2 = _mm512_reduce_add_epi32(vs2) % BASE;` as it expands to a macro, so it can't tell which line the error is.

**Comment by KungFuJesus** [comment]
> @KungFuJesus Could be `sum2 = _mm512_reduce_add_epi32(vs2) % BASE;` as it expands to a macro, so it can't tell which line the error is.

In that case a cast may fix things, since the wrapped to negative representation should still be the correct value in unsigned domain.

**Comment by KungFuJesus** [comment]
Lol, it's actually in the macro expansion GCC is doing for that intrinsic itself.  *sigh* I don't love doing this but I can basically do exactly what that intrinsic is doing in a local function.  It has one final scalar sum in GPRs and _that_'s what the UB sanitizer is finding here.  It's not net any larger code for it, I guess, it's just something I thought we wouldn't need since compilers usually supported it.  The intrinsic exists in signed formed precisely _because_ the instructions in unsigned domain are exactly the same. I'll have a PR, shortly.

**Comment by KungFuJesus** [comment]
Ok, that UB behavior is fixed in #1199

**Review by KungFuJesus — APPROVED** [review]

**Review by Dead2 — APPROVED** [review]

**Comment by iii-i** [comment]
@nmoinvaz Seems like we need to check that the window is really allocated. It doesn't hurt in practice, since `whave` is 0, but it's good to know hat `memcpy(NULL, NULL, 0)` is an UB. I'll send a patch.

**Comment by iii-i** [comment]
On the other hand, the problematic code goes away in https://github.com/zlib-ng/zlib-ng/pull/1178 (https://github.com/zlib-ng/zlib-ng/pull/1178/files#diff-74f4c840088fab89218413285e2d58d240544f8923359216d47039891151b180L134).

So maybe it's better to simply wait until it's merged?

**Comment by nmoinvaz** [comment]
Better to wait for the other PR I agree.

**Pull request merged**
