### PR TITLE
darwin ios/mac m1 cpu features detection update proposal

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mtl1979** [comment]
FYI: CI failure seems to be because of mismatch in libSystem.B.dylib version.

**Comment by devnexen** [comment]
yes seemingly as previous PR

**Comment by mtl1979** [comment]
@Dead2 will merge when he's online... I think this is simple enough patch that it doesn't require approval of 2 long-time contributors...

**Comment by Dead2** [comment]
Thanks!

**Pull request merged**
