### PR TITLE
Enable AVX2 functions to be built with BMI2 instructions

### PR DESCRIPTION
**Pull request by KungFuJesus**
While these are technically different instructions, no such CPU exists that has AVX2 that doesn't have BMI2. Enabling BMI2 allows us to eliminate several flag stalls by having flagless versions of shifts, and allows us to not clobber and move around GPRs so much in scalar code. There's usually a sizeable benefit for enabling it. Since we're building with BMI2 for AVX2 functions, let's also just make sure the CPU claims to support it (just to cover our bases).

## Summary by CodeRabbit

- **New Features**
	- Enhanced AVX2 optimizations by adding support for the BMI2 instruction set, improving performance on compatible CPUs.
	- Introduced new functions for checking compiler capabilities related to various intrinsics and optimizations, expanding support for modern architectures.
- **Bug Fixes**
	- Improved error handling and logging mechanisms in the configuration process for better troubleshooting.

### CODE REVIEW

**Comment by Dead2** [comment]
### Develop 28 Nov
```
          6,155.37 msec task-clock:u                     #    1.000 CPUs utilized               ( +-  0.01% )
                 0      context-switches:u               #    0.000 /sec
                 0      cpu-migrations:u                 #    0.000 /sec
               144      page-faults:u                    #   23.394 /sec                        ( +-  0.34% )
    21,365,062,998      cycles:u                         #    3.471 GHz                         ( +-  0.01% )  (62.48%)
    35,582,552,199      instructions:u                   #    1.67  insn per cycle              ( +-  0.02% )  (74.99%)
     3,754,368,604      branches:u                       #  609.934 M/sec                       ( +-  0.02% )  (75.01%)
       174,548,734      branch-misses:u                  #    4.65% of all branches             ( +-  0.02% )  (75.01%)
     6,678,724,547      L1-dcache-loads:u                #    1.085 G/sec                       ( +-  0.00% )  (75.02%)
       233,855,267      L1-dcache-load-misses:u          #    3.50% of all L1-dcache accesses   ( +-  0.08% )  (75.01%)
        17,771,941      LLC-loads:u                      #    2.887 M/sec                       ( +-  0.75% )  (49.98%)
                64      LLC-load-misses:u                #    0.00% of all LL-cache accesses    ( +- 43.98% )  (49.97%)

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.185%      0.106/0.110/0.111/0.001        0.036/0.039/0.042/0.002        8,526,745
 2     43.871%      0.198/0.202/0.204/0.001        0.034/0.038/0.040/0.001        6,903,702
 3     42.390%      0.247/0.250/0.253/0.002        0.032/0.038/0.040/0.002        6,670,664
 4     41.644%      0.272/0.278/0.281/0.002        0.034/0.037/0.038/0.001        6,553,205
 5     41.215%      0.303/0.311/0.315/0.003        0.034/0.037/0.039/0.001        6,485,659
 6     41.032%      0.354/0.360/0.363/0.003        0.035/0.036/0.037/0.001        6,456,912
 7     40.778%      0.494/0.501/0.506/0.003        0.030/0.035/0.037/0.002        6,416,941
 8     40.704%      0.609/0.616/0.621/0.003        0.030/0.035/0.037/0.002        6,405,249
 9     40.409%      0.904/0.911/0.917/0.004        0.030/0.035/0.037/0.002        6,358,951

 avg1  42.914%                        0.393                          0.037
 tot                                106.149                          9.901       60,778,028

   text    data     bss     dec     hex filename
 138830    1312       8  140150   22376 libz-ng.so.2
```
# PR #1816
```
          5,154.35 msec task-clock:u                     #    1.000 CPUs utilized               ( +-  0.01% )
                 0      context-switches:u               #    0.000 /sec
                 0      cpu-migrations:u                 #    0.000 /sec
               143      page-faults:u                    #   27.744 /sec                        ( +-  0.28% )
    17,778,636,206      cycles:u                         #    3.449 GHz                         ( +-  0.01% )  (62.48%)
    32,149,287,502      instructions:u                   #    1.81  insn per cycle              ( +-  0.01% )  (75.00%)
     3,756,493,111      branches:u                       #  728.801 M/sec                       ( +-  0.01% )  (75.01%)
       173,624,532      branch-misses:u                  #    4.62% of all branches             ( +-  0.02% )  (75.01%)
     6,365,551,872      L1-dcache-loads:u                #    1.235 G/sec                       ( +-  0.00% )  (75.01%)
       231,548,653      L1-dcache-load-misses:u          #    3.64% of all L1-dcache accesses   ( +-  0.03% )  (75.01%)
        17,957,764      LLC-loads:u                      #    3.484 M/sec                       ( +-  1.01% )  (49.98%)
                39      LLC-load-misses:u                #    0.00% of all LL-cache accesses    ( +- 48.35% )  (49.98%)

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.185%      0.107/0.109/0.111/0.001        0.028/0.030/0.032/0.001        8,526,745
 2     43.871%      0.196/0.201/0.203/0.002        0.028/0.031/0.033/0.001        6,903,702
 3     42.390%      0.247/0.251/0.253/0.002        0.025/0.029/0.031/0.002        6,670,664
 4     41.644%      0.274/0.279/0.282/0.002        0.023/0.029/0.031/0.002        6,553,205
 5     41.215%      0.306/0.311/0.315/0.003        0.024/0.028/0.032/0.002        6,485,659
 6     41.032%      0.352/0.359/0.363/0.003        0.025/0.029/0.030/0.002        6,456,912
 7     40.778%      0.496/0.501/0.505/0.003        0.024/0.028/0.030/0.002        6,416,941
 8     40.704%      0.610/0.617/0.621/0.003        0.023/0.028/0.031/0.002        6,405,249
 9     40.409%      0.906/0.910/0.912/0.002        0.026/0.028/0.030/0.001        6,358,951

 avg1  42.914%                        0.393                          0.029
 tot                                106.131                          7.810       60,778,028
 
   text    data     bss     dec     hex filename
 138702    1312       8  140022   222f6 libz-ng.so.2

# Retest with different unrelated code added to make sure we didn't just hit a rare golden cacheline alignment
 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.185%      0.105/0.109/0.111/0.002        0.029/0.031/0.033/0.001        8,526,745
 2     43.871%      0.198/0.202/0.204/0.002        0.028/0.031/0.033/0.001        6,903,702
 3     42.390%      0.246/0.250/0.253/0.002        0.026/0.030/0.032/0.002        6,670,664
 4     41.644%      0.276/0.279/0.282/0.002        0.025/0.029/0.031/0.002        6,553,205
 5     41.215%      0.301/0.310/0.314/0.003        0.025/0.029/0.031/0.002        6,485,659
 6     41.032%      0.353/0.358/0.361/0.002        0.024/0.028/0.030/0.002        6,456,912
 7     40.778%      0.493/0.502/0.507/0.004        0.026/0.028/0.031/0.001        6,416,941
 8     40.704%      0.609/0.616/0.620/0.003        0.023/0.028/0.031/0.002        6,405,249
 9     40.409%      0.895/0.909/0.916/0.005        0.024/0.029/0.030/0.001        6,358,951

 avg1  42.914%                        0.393                          0.029
 tot                                106.081                          7.854       60,778,028
```

Wow.. I had to retest that because it was such a big difference.
@KungFuJesus Can you do a comparison test with AVX512 disabled also? I am still a little unsure whether this is actually real or not.
In the perf test we can see that the count of instructions executed is down by 9.65%, that is pretty major, so this indicates this might actually be a real speedup.

Inflate: Perf test is 16% faster. Deflatebench is 21% faster. 😮 
(Perf and Deflatebench use different datasets)
Deflate: No difference.

**Comment by Dead2** [comment]
@KungFuJesus If this speedup is the real deal, I wonder what the AVX512 is in comparison now, it feels like the benefit must have been reduced by quite a bit.

**Comment by KungFuJesus** [comment]
> @KungFuJesus If this speedup is the real deal, I wonder what the AVX512 is in comparison now, it feels like the benefit must have been reduced by quite a bit.

When doing an initial improvement, I tend to compare against -march=native builds, which would have had this enabled.  I don't believe it will be significantly undercut, but let me check.

**Comment by KungFuJesus** [comment]
So here's this PR, as is with inflate_fast_avx512 and all its chunksetting:

```
OS: Linux 6.11.6-gentoo-x86_64 #3 SMP PREEMPT_DYNAMIC Mon Nov  4 10:41:27 EST 2024 x86_64
CPU: Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
Tool: /home/adam/scratch/zlib-ng/build_clean/minigzip Size: 154,848 B
Levels: 0-9       
Runs: 10         Trim worst: 2         

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.014/0.017/0.021/0.003        0.016/0.020/0.023/0.003      211,973,953
 1     44.409%      0.843/0.852/0.864/0.007        0.325/0.332/0.339/0.004       94,127,497
 2     35.519%      1.423/1.430/1.434/0.004        0.318/0.327/0.333/0.005       75,286,322
 3     33.844%      1.780/1.795/1.805/0.008        0.307/0.313/0.318/0.004       71,735,218
 4     33.146%      2.091/2.097/2.102/0.004        0.295/0.302/0.309/0.005       70,255,223
 5     32.642%      2.410/2.423/2.454/0.014        0.290/0.302/0.314/0.007       69,187,419
 6     32.483%      2.929/2.942/2.961/0.012        0.292/0.297/0.303/0.004       68,850,776
 7     32.255%      4.092/4.129/4.175/0.032        0.297/0.303/0.310/0.005       68,366,759
 8     32.167%      6.545/6.579/6.633/0.031        0.294/0.302/0.308/0.004       68,180,762
 9     31.887%      7.177/7.198/7.239/0.023        0.282/0.288/0.293/0.004       67,586,442

 avg1  40.836%                        2.946                          0.279
 avg2  45.373%                        3.274                          0.309
 tot                                235.701                         22.281      865,550,371

```

Here's with inflate_fast_avx512 and chunkmemset etc carved out (keeping the adler stuff in).

```
OS: Linux 6.11.6-gentoo-x86_64 #3 SMP PREEMPT_DYNAMIC Mon Nov  4 10:41:27 EST 2024 x86_64
CPU: Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
Tool: /home/adam/scratch/zlib-ng/build_noavx512/minigzip Size: 150,488 B
Levels: 0-9       
Runs: 10         Trim worst: 2         

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.012/0.016/0.021/0.003        0.017/0.020/0.023/0.002      211,973,953
 1     44.409%      0.840/0.852/0.860/0.006        0.314/0.323/0.330/0.007       94,127,497
 2     35.519%      1.432/1.440/1.445/0.004        0.314/0.323/0.331/0.005       75,286,322
 3     33.844%      1.784/1.793/1.803/0.007        0.295/0.305/0.309/0.004       71,735,218
 4     33.146%      2.098/2.109/2.128/0.010        0.290/0.296/0.303/0.005       70,255,223
 5     32.642%      2.408/2.421/2.434/0.009        0.286/0.296/0.301/0.005       69,187,419
 6     32.483%      2.918/2.929/2.935/0.007        0.285/0.296/0.301/0.005       68,850,776
 7     32.255%      4.102/4.129/4.202/0.032        0.285/0.298/0.307/0.007       68,366,759
 8     32.167%      6.548/6.602/6.668/0.034        0.285/0.294/0.299/0.005       68,180,762
 9     31.887%      7.168/7.190/7.212/0.016        0.281/0.285/0.288/0.002       67,586,442

 avg1  40.836%                        2.948                          0.274
 avg2  45.373%                        3.276                          0.304
 tot                                235.849                         21.881      865,550,371
```

So the plot thickens.  It's not a huge net loss, but it is marginally slower.  It might be hard to attribute that specifically to any one thing, though.

**Comment by Dead2** [comment]
> So here's this PR, as is with inflate_fast_avx512 and all its chunksetting:

Could you do one without this PR as well?

**Comment by KungFuJesus** [comment]
> > So here's this PR, as is with inflate_fast_avx512 and all its chunksetting:
> 
> Could you do one without this PR as well?

I can but it's going to take the avx512 path which will have BMI2 enabled as well.  I can also use this as the baseline for #1821 

```
OS: Linux 6.11.6-gentoo-x86_64 #3 SMP PREEMPT_DYNAMIC Mon Nov  4 10:41:27 EST 2024 x86_64
CPU: Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
Tool: /home/adam/scratch/zlib-ng/build_clean/minigzip Size: 154,848 B
Levels: 0-9       
Runs: 10         Trim worst: 2         

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.017/0.019/0.022/0.002        0.015/0.018/0.021/0.002      211,973,953
 1     44.409%      0.848/0.858/0.863/0.006        0.332/0.336/0.342/0.004       94,127,497
 2     35.519%      1.427/1.441/1.447/0.008        0.324/0.329/0.337/0.004       75,286,322
 3     33.844%      1.774/1.786/1.792/0.006        0.304/0.312/0.318/0.005       71,735,218
 4     33.146%      2.089/2.099/2.116/0.008        0.295/0.309/0.319/0.008       70,255,223
 5     32.642%      2.407/2.411/2.417/0.004        0.293/0.302/0.307/0.004       69,187,419
 6     32.483%      2.918/2.927/2.935/0.005        0.294/0.302/0.309/0.006       68,850,776
 7     32.255%      4.094/4.115/4.131/0.013        0.297/0.304/0.310/0.005       68,366,759
 8     32.167%      6.582/6.598/6.627/0.018        0.291/0.305/0.310/0.006       68,180,762
 9     31.887%      7.177/7.192/7.218/0.014        0.278/0.287/0.297/0.008       67,586,442

 avg1  40.836%                        2.945                          0.280
 avg2  45.373%                        3.272                          0.312
 tot                                235.577                         22.438      865,550,371
```

**Comment by Dead2** [comment]
> I can but it's going to take the avx512 path which will have BMI2 enabled as well. I can also use this as the baseline for #1821

Oh, right. I was hoping one with `-DWITH_AVX512=OFF -DWITH_AVX512VNNI=OFF`

**Comment by KungFuJesus** [comment]
> > I can but it's going to take the avx512 path which will have BMI2 enabled as well. I can also use this as the baseline for #1821
> 
> Oh, right. I was hoping one with `-DWITH_AVX512=OFF -DWITH_AVX512VNNI=OFF`

Doing that then precludes the faster checksums with it, though.  The numbers for the version with inflate_fast_avx512 and chunkmemset_safe_avx512 commented out from the function table are what I think you want.

**Comment by Dead2** [comment]
> > Oh, right. I was hoping one with `-DWITH_AVX512=OFF -DWITH_AVX512VNNI=OFF`
> 
> Doing that then precludes the faster checksums with it, though. The numbers for the version with inflate_fast_avx512 and chunkmemset_safe_avx512 commented out from the function table are what I think you want.

But that is with this PR included, or did I misunderstand?

What I want to see is before and after for the AVX2 codepath, similar to what I did, to see whether the speedup is there for others as well and how big.

**Comment by KungFuJesus** [comment]
> Reference i

Ah fair enough, let me try this on a U series Haswell CPU since that's what I'm using at the moment.

# Develop 
```
 Tool: /home/adam/zlib-ng/build-develop/minigzip Levels: 0-9       
 Runs: 10         Trim worst: 2         

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.060/0.093/0.112/0.019        0.099/0.115/0.129/0.010      211,973,953
 1     44.409%      2.808/2.838/2.859/0.016        1.279/1.301/1.312/0.012       94,127,497
 2     35.519%      5.073/5.145/5.186/0.036        1.255/1.307/1.337/0.028       75,286,322
 3     33.844%      6.666/6.701/6.744/0.023        1.214/1.237/1.265/0.019       71,735,218
 4     33.146%      7.530/7.584/7.661/0.052        1.183/1.196/1.209/0.012       70,255,223
 5     32.642%      8.303/8.392/8.555/0.085        1.155/1.191/1.232/0.025       69,187,419
 6     32.483%      9.691/9.750/9.842/0.051        1.150/1.171/1.183/0.012       68,850,776
 7     32.255%   12.765/12.837/12.900/0.042        1.153/1.170/1.190/0.015       68,366,759
 8     32.167%   19.484/19.566/19.822/0.107        1.140/1.156/1.174/0.013       68,180,762
 9     31.887%   22.513/22.583/22.632/0.039        1.168/1.181/1.203/0.012       67,586,442

 avg1  40.836%                        9.549                          1.102
 avg2  45.373%                       10.610                          1.225
 tot                                763.916                         88.199      865,550,371
```

# PR1816
```
 Tool: /home/adam/zlib-ng/build-1816/minigzip Levels: 0-9       
 Runs: 10         Trim worst: 2         

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.070/0.097/0.117/0.016        0.090/0.101/0.120/0.012      211,973,953
 1     44.409%      2.806/2.906/3.091/0.088        1.119/1.140/1.165/0.018       94,127,497
 2     35.519%      5.108/5.232/5.564/0.139        1.108/1.143/1.182/0.024       75,286,322
 3     33.844%      6.684/6.802/7.089/0.140        1.057/1.091/1.118/0.019       71,735,218
 4     33.146%      7.506/7.607/7.702/0.067        1.019/1.042/1.064/0.014       70,255,223
 5     32.642%      8.305/8.502/9.036/0.236        0.994/1.032/1.054/0.022       69,187,419
 6     32.483%     9.628/9.882/10.274/0.241        1.006/1.043/1.092/0.024       68,850,776
 7     32.255%   12.741/12.945/13.256/0.175        0.977/1.013/1.037/0.019       68,366,759
 8     32.167%   19.496/19.832/20.398/0.344        0.992/1.024/1.047/0.018       68,180,762
 9     31.887%   22.440/22.695/23.209/0.310        0.985/1.013/1.042/0.018       67,586,442

 avg1  40.836%                        9.650                          0.964
 avg2  45.373%                       10.722                          1.071
 tot                                771.992                         77.135      865,550,371
```

**Comment by Dead2** [comment]
Nice, a 12.5% speedup.

I think that confirms that it is a really good optimization.

Makes me wonder how performance compares wrt MinGW vs MSVC compilers, since MSVC does not actually let us choose whether to enable BMI2 or not, so is it used since it always exists along with AVX2 or is it never used because that might not be true in the future? I suspect the latter, meaning that MinGW might result in significantly faster inflate.

**Review by Dead2 — APPROVED** [review]
Looks awesome to me ;)

**Comment by phprus** [comment]
@Dead2 
As far as I know, ``/arch:AVX2`` in MSVC enables support for ``BMI1/2``.

**Comment by nmoinvaz** [comment]
Code rabbit makes a good suggestion:
image

**Comment by Dead2** [comment]
> Code rabbit makes a good suggestion: image

@KungFuJesus Could you add this comment, it does seem like a really good idea.

**Comment by KungFuJesus** [comment]
> @KungFuJesus Could you add this comment, it does seem like a really good idea.

Yeah, sorry had to step away for a bit.  Will add a comment now.

**Pull request merged**
