### PR TITLE
Treat arm64 as aarch64 for Apple M1.

### PR DESCRIPTION
**Pull request by mtl1979**
See #1315.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Can you add " for Apple M1" to the commit message?

**Comment by mtl1979** [comment]
> Can you add " for Apple M1" to the commit message?

Done.

**Review by nmoinvaz — APPROVED** [review]

**Comment by mtl1979** [comment]
I added `__arm64__` to the cmake detection code for completeness... Some Apple compilers use `__aarch64__` and some compilers use `__arm64__`.

**Comment by Dead2** [comment]
Should __arm64__ be added to feature checks around the code as well perhaps?

**Comment by mtl1979** [comment]
> Should **arm64** be added to feature checks around the code as well perhaps?

I don't have Apple M1 hardware, so testing where changes are really needed isn't easy and as such was best to leave as separate PR. I don't like to clutter the code with extraneous preprocessor checks just for the sake of being consistent.

**Pull request merged**
