### PR TITLE
Set binary mode for stdin and stdout in switchlevels.

### PR DESCRIPTION
**Pull request by nmoinvaz**
I have added an additional commit for formatting changes.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Codecov is messed up in GitHub comments. For the last few PRs it has shown -5% which are all based on latest develop. Then you go into view the full report and it looks ok.

**Comment by Dead2** [comment]
Is there any special reason you move the variables to the top?
We have decided that we target C99, and C99 has removed that requirement (it also allows // comments btw).

**Comment by nmoinvaz** [comment]
No special reason I just thought it looked more readable. I work on other projects that are started pre-C99 so I guess it is muscle memory. I can revert those changes if you want.

**Comment by Dead2** [comment]
I don't especially care either way. 
Could you rebase this to not depend on another PR?

**Comment by nmoinvaz** [comment]
Ok should be rebased now. I don't think this was dependent upon another PR.

**Pull request merged**
