### PR TITLE
Combine option and add_feature_info in CMake.

### PR DESCRIPTION
**Pull request by nmoinvaz**
Not sure if everybody wants this.. that is why it is a separate PR.

### CODE REVIEW

**Comment by Dead2** [comment]
This fails CI, at least pkgcheck.

**Comment by mtl1979** [comment]
`test/pkgcheck.sh: 169: test/pkgcheck.sh: diffoscope: not found`

See #773

**Comment by nmoinvaz** [comment]
Rebased

**Comment by nmoinvaz** [comment]
`diffoscope` still not found on macOS, weird.

**Comment by mtl1979** [comment]
@nmoinvaz I only fixed it for Ubuntu, someone with MacOS can figure out what the correct package name is for it...

**Comment by nmoinvaz** [comment]
https://brewinstall.org/install-diffoscope-on-mac-with-brew/
```
brew install diffoscope
```

**Comment by mtl1979** [comment]
FYI. The pkgcheck fail is due to reordering the avx files...

**Comment by mtl1979** [comment]
@nmoinvaz After I added that, I got more errors... Seems like it was never fully tested on MacOS...

**Comment by Dead2** [comment]
So, what is the status of this PR?
Does it need a fix to reorder the avx files as mentioned by @mtl1979?

**Comment by nmoinvaz** [comment]
I had forgotten about it. I have removed the second commit and rebased.

**Pull request merged**
