### PR TITLE
Make use of unaligned loads on big endian in insert_string

### PR DESCRIPTION
**Pull request by ccawley2011**
PR #1690 is required for this to take effect.

### CODE REVIEW

**Review by nmoinvaz — APPROVED** [review]

**Comment by nmoinvaz** [comment]
@Dead2 I'm not sure why there has been no activity on this one. It LGTM.

**Comment by Dead2** [comment]
@nmoinvaz The PR description says it depends on #1690, so I have not questioned that. But it does look like it would be useful on its own as well, doesn't it?

**Comment by nmoinvaz** [comment]
Yeah it does.

**Comment by ccawley2011** [comment]
The reason for needing PR #1690 is because without it, the only architectures that define UNALIGNED_OK are little endian. This can still be merged without it, it just won't get covered by tests until PR #1690 is merged.

**Pull request merged**
