### PR TITLE
Minor changes to chunk memory functions

### PR DESCRIPTION
**Pull request by nmoinvaz**
These are 3 commits from #987 that are ready.

### CODE REVIEW

**Review by Dead2 — APPROVED** [review]
LGTM

**Comment by Dead2** [comment]
### Baseline c475ec95525ac4bbf4838a6943ebd2c88c1fb5a1 x86-64
```
   text    data     bss     dec     hex filename
 111488    1296      32  112816   1b8b0 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.780%      1.889/1.905/1.911/0.006        1.275/1.285/1.292/0.005       90,924,650
 2     43.876%      2.022/2.044/2.052/0.008        0.774/0.825/0.837/0.014       41,427,218
 3     42.490%      2.092/2.109/2.117/0.008        0.669/0.679/0.686/0.005       33,432,016
 4     41.467%      2.014/2.041/2.053/0.009        0.518/0.527/0.532/0.004       26,101,482
 5     41.212%      2.178/2.196/2.206/0.007        0.513/0.525/0.531/0.005       25,940,920
 6     41.039%      1.925/1.933/1.939/0.004        0.385/0.394/0.397/0.003       19,374,021
 7     40.781%      1.662/1.669/1.674/0.004        0.255/0.260/0.263/0.003       12,834,980
 8     40.706%      2.073/2.088/2.095/0.006        0.252/0.258/0.261/0.003       12,811,166
 9     40.695%      2.265/2.281/2.288/0.007        0.252/0.258/0.262/0.003       12,807,941

 avg1  43.339%                        2.029                          0.557
 tot                                365.303                        100.206      275,654,394
```

### PR #994  gitcp ef4c0f2ab014316f382cce9ff4206b41bfc337fe x86-64
```
   text    data     bss     dec     hex filename
 111488    1296      32  112816   1b8b0 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.780%      1.833/1.898/1.909/0.016        1.264/1.278/1.287/0.008       90,924,650
 2     43.876%      2.034/2.045/2.052/0.006        0.803/0.826/0.835/0.008       41,427,218
 3     42.490%      2.095/2.107/2.117/0.006        0.669/0.679/0.684/0.004       33,432,016
 4     41.467%      1.979/2.035/2.053/0.017        0.515/0.528/0.533/0.006       26,101,482
 5     41.212%      2.178/2.196/2.213/0.012        0.517/0.524/0.529/0.003       25,940,920
 6     41.039%      1.819/1.921/1.935/0.025        0.341/0.391/0.397/0.012       19,374,021
 7     40.781%      1.645/1.664/1.671/0.007        0.254/0.259/0.262/0.002       12,834,980
 8     40.706%      2.062/2.080/2.092/0.009        0.251/0.259/0.262/0.003       12,811,166
 9     40.695%      2.263/2.275/2.286/0.008        0.253/0.259/0.262/0.002       12,807,941

 avg1  43.339%                        2.025                          0.556
 tot                                364.435                        100.067      275,654,394
```

Minor speed improvement to inflate.

**Comment by Dead2** [comment]
### Baseline c475ec95525ac4bbf4838a6943ebd2c88c1fb5a1 aarch64
```
   text    data     bss     dec     hex filename
 103138    1504      16  104658   198d2 libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.784%      3.002/3.030/3.050/0.016        0.939/0.995/1.008/0.017       45,465,419
 2     43.879%      2.775/2.805/2.832/0.018        0.583/0.616/0.637/0.015       20,714,938
 3     42.489%      3.422/3.454/3.472/0.016        0.567/0.593/0.615/0.015       20,058,827
 4     41.468%      2.732/2.757/2.773/0.011        0.366/0.380/0.388/0.008       13,050,960
 5     41.218%      2.916/2.980/3.003/0.027        0.340/0.380/0.396/0.014       12,972,368
 6     41.040%      3.453/3.479/3.495/0.013        0.361/0.382/0.393/0.009       12,916,434
 7     40.778%      2.234/2.254/2.270/0.011        0.160/0.178/0.190/0.009        6,416,924
 8     40.704%      2.759/2.782/2.798/0.013        0.155/0.176/0.191/0.012        6,405,244
 9     40.696%      2.947/3.001/3.016/0.018        0.169/0.177/0.185/0.005        6,404,084

 avg1  43.340%                        2.949                          0.431
 tot                                398.134                         58.159      144,405,198
```
### PR #994  ef4c0f2ab014316f382cce9ff4206b41bfc337fe aarch64
```
   text    data     bss     dec     hex filename
 103130    1504      16  104650   198ca libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     57.784%      2.984/3.017/3.035/0.017        0.949/0.985/1.005/0.017       45,465,419
 2     43.879%      2.741/2.777/2.807/0.023        0.588/0.620/0.630/0.011       20,714,938
 3     42.489%      3.384/3.433/3.469/0.025        0.568/0.599/0.609/0.012       20,058,827
 4     41.468%      2.737/2.764/2.773/0.009        0.365/0.379/0.389/0.006       13,050,960
 5     41.218%      2.901/2.977/2.993/0.023        0.352/0.369/0.380/0.009       12,972,368
 6     41.040%      3.433/3.477/3.503/0.021        0.351/0.369/0.385/0.011       12,916,434
 7     40.778%      2.234/2.259/2.271/0.014        0.171/0.183/0.191/0.006        6,416,924
 8     40.704%      2.756/2.783/2.799/0.013        0.159/0.178/0.190/0.008        6,405,244
 9     40.696%      2.977/3.004/3.018/0.011        0.169/0.179/0.193/0.008        6,404,084

 avg1  43.340%                        2.944                          0.429
 tot                                397.383                         57.925      144,405,198
```

Compiled code size slightly smaller.
Minor speed improvement to inflate.

**Comment by Dead2** [comment]
This is pretty simple, so should this go to Stable as well? Thoughts?

**Comment by mtl1979** [comment]
@Dead2 Clearly not controversial or complex patch, so should not break things.

**Pull request merged**
