### PR TITLE
Remove extra division operation in chunkcopy

### PR DESCRIPTION
**Pull request by nmoinvaz**
From my draft PR #987. I don't expect any significant speed gains.

### CODE REVIEW

**Comment by mtl1979** [comment]
Fails CI, will most likely get fixed by rebasing...

**Comment by nmoinvaz** [comment]
Rebased.

**Comment by Dead2** [comment]
### Baseline 21050e06c511a67f3239d1bca444616be6853bfe x86-64
```
   text    data     bss     dec     hex filename
 115241    1416      32  116689   1c7d1 libz-ng.so.2

Activated multiple generated file mode. Source: ../silesia-small.tar
Level 1: /tmp/deflatebench-1.tmp  465.2 MiB   487,825,920 B
Level 2: /tmp/deflatebench-2.tmp  270.1 MiB   283,253,760 B
Level 3: /tmp/deflatebench-3.tmp  225.1 MiB   236,044,800 B
Level 4: /tmp/deflatebench-4.tmp  180.1 MiB   188,835,840 B
Level 5: /tmp/deflatebench-5.tmp  165.1 MiB   173,099,520 B
Level 6: /tmp/deflatebench-6.tmp  135.1 MiB   141,626,880 B
Level 7: /tmp/deflatebench-7.tmp  105.1 MiB   110,154,240 B
Level 8: /tmp/deflatebench-8.tmp   90.0 MiB    94,417,920 B
Level 9: /tmp/deflatebench-9.tmp   75.0 MiB    78,681,600 B

 Tool: minigzip   Levels: 1-9
 Runs: 40         Trim worst: 20

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.165%      2.892/2.928/2.946/0.017        1.661/1.669/1.678/0.005      264,231,515
 2     43.875%      2.974/3.002/3.015/0.010        0.984/1.002/1.017/0.010      124,277,644
 3     42.382%      3.003/3.018/3.032/0.009        0.786/0.812/0.825/0.011      100,039,412
 4     41.669%      2.718/2.737/2.743/0.007        0.622/0.634/0.645/0.006       78,685,354
 5     41.215%      2.868/2.911/2.926/0.016        0.568/0.578/0.585/0.006       71,342,944
 6     41.036%      2.763/2.776/2.785/0.007        0.441/0.469/0.478/0.009       58,118,026
 7     40.781%      2.717/2.735/2.742/0.007        0.358/0.367/0.371/0.004       44,921,649
 8     40.702%      2.996/3.009/3.017/0.007        0.297/0.313/0.321/0.007       38,429,965
 9     40.698%      2.783/2.795/2.801/0.005        0.247/0.259/0.266/0.006       32,021,745

 avg1  42.947%                        2.879                          0.678
 tot                                518.191                        122.066      812,068,254
```

### PR #1011 6533d86a6c99591a3365d35983479da5155dacab
```
   text    data     bss     dec     hex filename
 114921    1416      32  116369   1c691 libz-ng.so.2


 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.165%      2.898/2.930/2.949/0.013        1.652/1.668/1.679/0.008      264,231,515
 2     43.875%      2.972/2.990/3.004/0.009        0.995/1.006/1.015/0.006      124,277,644
 3     42.382%      2.990/3.016/3.025/0.009        0.784/0.808/0.820/0.010      100,039,412
 4     41.669%      2.716/2.749/2.761/0.012        0.610/0.629/0.647/0.011       78,685,354
 5     41.215%      2.871/2.899/2.917/0.013        0.543/0.578/0.586/0.010       71,342,944
 6     41.036%      2.758/2.791/2.804/0.012        0.461/0.470/0.480/0.006       58,118,026
 7     40.781%      2.725/2.739/2.749/0.008        0.347/0.362/0.371/0.007       44,921,649
 8     40.702%      3.006/3.017/3.026/0.006        0.296/0.313/0.320/0.006       38,429,965
 9     40.698%      2.784/2.797/2.804/0.006        0.242/0.258/0.266/0.007       32,021,745

 avg1  42.947%                        2.881                          0.677
 tot                                518.562                        121.828      812,068,254
```

Quite substantial reduction in compiled code size.
Benchmark results are not significant, but inflate is almost 0.2% faster in this test.
I'll try to get a test done on ARM as well, but not tonight.

**Comment by nmoinvaz** [comment]
Reduction in code size probably due to the fact that that function is a template and there is multiple versions of it.

**Comment by Dead2** [comment]
### Baseline 21050e06c511a67f3239d1bca444616be6853bfe aarch64
```
   text    data     bss     dec     hex filename
 105234    1576      16  106826   1a14a libz-ng.so.2

Level 1: /tmp/deflatebench-1.tmp   75.0 MiB    78,681,600 B
Level 2: /tmp/deflatebench-2.tmp   45.0 MiB    47,208,960 B
Level 3: /tmp/deflatebench-3.tmp   45.0 MiB    47,208,960 B
Level 4: /tmp/deflatebench-4.tmp   30.0 MiB    31,472,640 B
Level 5: /tmp/deflatebench-5.tmp   30.0 MiB    31,472,640 B
Level 6: /tmp/deflatebench-6.tmp   30.0 MiB    31,472,640 B
Level 7: /tmp/deflatebench-7.tmp   15.0 MiB    15,736,320 B
Level 8: /tmp/deflatebench-8.tmp   15.0 MiB    15,736,320 B
Level 9: /tmp/deflatebench-9.tmp   15.0 MiB    15,736,320 B

 Tool: minigzip   Levels: 1-9
 Runs: 40         Trim worst: 20

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.729/2.769/2.790/0.019        0.974/0.998/1.014/0.014       42,618,858
 2     43.879%      2.821/2.856/2.872/0.012        0.583/0.601/0.613/0.009       20,714,938
 3     42.383%      3.722/3.745/3.766/0.016        0.568/0.588/0.600/0.010       20,008,755
 4     41.660%      2.782/2.802/2.818/0.011        0.350/0.376/0.390/0.012       13,111,391
 5     41.216%      3.001/3.035/3.052/0.014        0.339/0.371/0.388/0.013       12,971,746
 6     41.039%      3.511/3.541/3.555/0.013        0.345/0.369/0.379/0.010       12,916,025
 7     40.778%      2.260/2.273/2.286/0.009        0.170/0.181/0.187/0.004        6,416,924
 8     40.704%      2.785/2.805/2.817/0.010        0.149/0.177/0.191/0.011        6,405,244
 9     40.696%      2.997/3.021/3.034/0.009        0.165/0.180/0.190/0.008        6,404,084

 avg1  42.947%                        2.983                          0.427
 tot                                536.961                         76.853      141,567,965
```

### PR #1011 
```
   text    data     bss     dec     hex filename
 105106    1576      16  106698   1a0ca libz-ng.so.2

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      2.713/2.770/2.795/0.022        0.944/0.988/1.013/0.018       42,618,858
 2     43.879%      2.829/2.854/2.871/0.010        0.564/0.591/0.608/0.013       20,714,938
 3     42.383%      3.703/3.748/3.773/0.019        0.553/0.586/0.598/0.010       20,008,755
 4     41.660%      2.773/2.795/2.808/0.010        0.352/0.378/0.387/0.010       13,111,391
 5     41.216%      2.988/3.035/3.048/0.016        0.347/0.369/0.383/0.012       12,971,746
 6     41.039%      3.487/3.531/3.545/0.014        0.350/0.367/0.381/0.009       12,916,025
 7     40.778%      2.253/2.275/2.285/0.008        0.173/0.184/0.191/0.006        6,416,924
 8     40.704%      2.790/2.807/2.821/0.008        0.153/0.175/0.189/0.010        6,405,244
 9     40.696%      2.994/3.021/3.037/0.011        0.161/0.175/0.183/0.007        6,404,084

 avg1  42.947%                        2.982                          0.424
 tot                                536.715                         76.258      141,567,965
```

aarch64 shows a good reduction in text, and 0.77% faster inflate.

**Pull request merged**
