### PR TITLE
Enable CI options explicitly so forked repositories don't fail CI.

### PR DESCRIPTION
**Pull request by nmoinvaz**
See issue #487.

### CODE REVIEW

**Comment by Dead2** [comment]
I don't think "maintenance" is the right word here. The point is to convey that this is an option meant to be used by the maintainers. Similar to autoconf's "--enable-maintainer-mode" option for example. But "maintenance" means something slightly different and I fear the meaning gets lost.

**Comment by nmoinvaz** [comment]
Yeah I didn't really know what words to use instead so I just went with `WITH_CODE_COVERAGE` and `WITH_MAINTENANCE_WARNINGS`.

**Comment by nmoinvaz** [comment]
I could change it to something like, `WITH_ALL_WARNINGS`.

**Comment by Dead2** [comment]
WITH_MAINTAINER_WARNINGS would be ideal I think, since we don't enable _ALL_ the warnings, but we enable warnings that makes no sense for an user to care about.

**Comment by nmoinvaz** [comment]
I have renamed the option to `WITH_MAINTAINER_WARNINGS` and added it and `WITH_CODE_COVERAGE` to README.md.

**Comment by Dead2** [comment]
I think you should revert the namechange of WARNFLAGS_MAINTAINER to WARNFLAGS_MAINTENANCE too, to avoid confusion.

**Comment by nmoinvaz** [comment]
Done.

**Pull request merged**
