### PR TITLE
Use state->pending and state->pending_buf pointers to pending output.

### PR DESCRIPTION
**Pull request by nmoinvaz**
Code simplification.

### CODE REVIEW

**Comment by KungFuJesus** [comment]
Looks like msan found it being used uninitialized.

**Comment by nmoinvaz** [comment]
Should be resolved now.

**Comment by nmoinvaz** [comment]
I'm just going to put this on hold until we decide what to do with #1178.

**Comment by nmoinvaz** [comment]
Closing this in favor of #1178.

**Pull request closed without merging**
