### PR TITLE
Increase size of gzip output buffer 

### PR DESCRIPTION
**Pull request by nmoinvaz**
On the [Understanding zlib](https://www.euccas.me/zlib/) page, it shows the graph below and from it we can infer that I/O performance may be reduced by the small size of the output buffer. In the case of the *gz* family of functions, the size of the output buffer is defined by `GZBUFSIZE` which by default is 8KB.

Every time `deflate` fills the pending buffer, it needs to be called several more times to output it all to the output buffer.

We should increment the size of the `GZBUFSIZE` to be a multiple of the size of the pending buffer. And for developers who do not use the *gz* family of functions but instead call `deflate` directly, we should document the fact that zlib performs better when the output buffer size is at least as large as the pending buffer. In zlib-ng the size of the pending buffer is 64kb or twice the size of the default zlib library of 32kb.

Using *silesia.tar* you can see the number of calls to `deflate` that happen based on the value of `GZBUFSIZE`:

|GZBUFSIZE|Total # of `deflate` calls|
|-|-|
|8k|24380|
|32k|11345|
|64k|6524|
|128k|3574|
|192k|2435|
|256k|1853|

DFLTCC code that was introduced in zlib-ng is [compiled with a `GZBUFSIZE` value of ~254KB](https://github.com/zlib-ng/zlib-ng/blob/51566828e52803a1355837660ac2afd585ac05e4/CMakeLists.txt#L672). We could remove this carve out in CMake if we wanted.

## ZLIB-NG (GZBUFSIZE=8KB)

```
 Tool: minigzip-8k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.975/0.994/1.013/0.011       100,930,174
 2     35.518%      1.598/1.638/1.671/0.020        75,282,951
 3     34.198%      1.946/1.974/2.016/0.023        72,485,720
 4     32.928%      2.343/2.389/2.437/0.027        69,793,995
 5     32.662%      2.515/2.556/2.618/0.034        69,228,861
 6     32.507%      2.944/2.986/3.056/0.032        68,901,208
 7     32.255%      3.922/3.977/4.075/0.049        68,366,778
 8     32.167%      6.134/6.224/6.384/0.081        68,180,776
 9     32.156%      8.592/8.713/8.930/0.122        68,156,160

 avg1  34.668%                        3.495
 tot                                943.543       661,326,623
 ```

 ## ZLIB-NG (GZBUFSIZE=32KB)

 ```
 Tool: minigzip-32k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.897/0.911/0.933/0.012       100,930,174
 2     35.518%      1.540/1.572/1.602/0.018        75,282,951
 3     34.198%      1.863/1.903/1.941/0.023        72,485,720
 4     32.929%      2.292/2.322/2.362/0.023        69,796,345
 5     32.660%      2.435/2.486/2.544/0.033        69,224,788
 6     32.507%      2.886/2.920/2.982/0.033        68,901,926
 7     32.255%      3.872/3.916/4.000/0.043        68,366,778
 8     32.167%      6.076/6.176/6.323/0.084        68,180,776
 9     32.156%      8.498/8.648/8.857/0.116        68,156,160

 avg1  34.668%                        3.428
 tot                                925.602       661,325,618
 ```

 ## ZLIB-NG (GZBUFSIZE=64KB)

 ```
 Tool: minigzip-64k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.872/0.886/0.903/0.008       100,930,174
 2     35.518%      1.518/1.540/1.572/0.015        75,282,951
 3     34.198%      1.843/1.866/1.904/0.010        72,485,720
 4     32.929%      2.247/2.268/2.328/0.019        69,796,074
 5     32.660%      2.423/2.451/2.500/0.020        69,225,542
 6     32.507%      2.851/2.876/2.944/0.023        68,902,152
 7     32.255%      3.816/3.873/3.973/0.033        68,366,778
 8     32.167%      6.056/6.112/6.278/0.052        68,180,776
 9     32.156%      8.480/8.568/8.824/0.088        68,156,160

 avg1  34.668%                        3.382
 tot                                913.177       661,326,327
 ```

## ZLIB-NG (GZBUFSIZE=128KB)

 ```
 Tool: minigzip-128k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.861/0.874/0.879/0.004       100,930,174
 2     35.518%      1.501/1.519/1.527/0.006        75,282,951
 3     34.198%      1.831/1.846/1.855/0.006        72,485,720
 4     32.929%      2.225/2.246/2.257/0.007        69,796,024
 5     32.660%      2.391/2.423/2.438/0.012        69,225,485
 6     32.508%      2.824/2.851/2.862/0.009        68,902,220
 7     32.255%      3.815/3.841/3.857/0.011        68,366,778
 8     32.167%      6.036/6.074/6.098/0.017        68,180,776
 9     32.156%      8.454/8.508/8.540/0.024        68,156,160

 avg1  34.668%                        3.354
 tot                                905.454       661,326,288
 ```

## ZLIB-NG (GZBUFSIZE=192KB)

 ```
 Tool: minigzip-192k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.855/0.869/0.873/0.003       100,930,174
 2     35.518%      1.498/1.511/1.521/0.006        75,282,951
 3     34.198%      1.827/1.838/1.848/0.006        72,485,720
 4     32.929%      2.227/2.245/2.255/0.007        69,796,052
 5     32.660%      2.396/2.414/2.422/0.006        69,225,500
 6     32.508%      2.825/2.841/2.854/0.008        68,902,226
 7     32.255%      3.817/3.840/3.853/0.009        68,366,778
 8     32.167%      6.017/6.061/6.076/0.015        68,180,776
 9     32.156%      8.453/8.497/8.519/0.018        68,156,160

 avg1  34.668%                        3.346
 tot                                903.466       661,326,337
 ```

## ZLIB-NG (GZBUFSIZE=256KB)

 ```
 Tool: minigzip-256k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.861/0.869/0.874/0.003       100,930,174
 2     35.518%      1.501/1.515/1.524/0.005        75,282,951
 3     34.198%      1.834/1.845/1.854/0.005        72,485,720
 4     32.929%      2.229/2.250/2.266/0.009        69,796,069
 5     32.660%      2.399/2.425/2.438/0.010        69,225,624
 6     32.508%      2.837/2.856/2.869/0.009        68,902,336
 7     32.255%      3.806/3.848/3.864/0.015        68,366,778
 8     32.167%      6.042/6.080/6.101/0.016        68,180,776
 9     32.156%      8.454/8.521/8.547/0.022        68,156,160

 avg1  34.668%                        3.357
 tot                                906.271       661,326,588
 ```

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Codecov should be more forgiving +- 0.01% is too small of a margin..

**Comment by Dead2** [comment]
I was surprised that #865 had zero change to coverage, I am not sure I have ever seen that before 😆

**Comment by nmoinvaz** [comment]
I was also interested in using `128kb` instead (seems to be a sweet spot), but figured more memory usage would be opposed.

**Comment by Dead2** [comment]
I would have liked to see 96KiB in that benchmark lineup as well, and perhaps 48KiB.

Honestly, I feel like this and other memory-increase "features" should be possible to disable. Not so much because of the embedded space, since we don't really cater to them in the first place, but for the users that serve 10K+ or even 100K+ connections that each have a zlib instance. For those users, the extra ram usage can mean a lot both because of the extra ram required, but also because it makes the competition for cache even worse.

I am all for this feature as a default-on thing, but being able to go for something more memory-sparse would be good too.
That also goes for my previous change to `HASH_SIZE`, as that forces zlib-ng to always use an extra-large `s->head` buffer, regardless of what memory level was requested. I have been thinking that our Next release should make that optimization optional. It might need to be re-considered in relation to fast-zlib integration in any case.

At the very least these should be possible to disable at compile-time. At run-time can be more complex since it could mean removing optimization possibilities of using a static size (Like with `HASH_SIZE`), but if possible it could be linked to `memory_level` or we could add it to the dynamic zlib-ng configuration API (something that should probably get tests and examples too, come to think of it).

**Comment by nmoinvaz** [comment]
I can try and run those benchmarks tonight. 

Currently the `GZBUFSIZE` is configurable via `-DGZBUFSIZE=x` but I know what you are talking about as far as configuration. Perhaps if we had a `-DWITH_REDUCED_MEM=ON` option in the future that would use:

- `GZBUFSIZE` to 8kb
- `HASH_SIZE` to 32kb
- `s->pending_buf_size` to 32kb?

Basically the default *zlib* configuration. 

I'm not really in favor of changing these at compile time because it would remove optimizations.

**Comment by nmoinvaz** [comment]
> ..for the users that serve 10K+ or even 100K+ connections that each have a zlib instance..

I don't think that the web servers will be using the `gz` functions which is what `GZBUFSIZE` applies to. If I remember correctly, `inflate` is able to decode GZIP header on its own.

**Comment by Dead2** [comment]
@nmoinvaz It can be connections other than web, but yes you are likely correct about the gz functions probably not being used much in such contexts.

And yeah, the `WITH_REDUCED_MEM` settings you suggest look good.
Another name alternative is `WITH_LOW_MEM`, shorter but perhaps not as clear (I don't prefer any of them at this point though). I just remember LOW_MEM or similar being a cmake setting other places, but I cannot remember what software that would be from.

**Comment by nmoinvaz** [comment]
Updated benchmarks:

|GZBUFSIZE|Total # of `deflate` calls|
|-|-|
|8k|24380|
|32k|11345|
|48k|8216|
|64k|6524|
|96k|4658|
|128k|3574|
|192k|2435|
|256k|1853|

## ZLIB-NG (GZBUFSIZE=8KB)

```
 Tool: minigzip-8k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      1.032/1.046/1.056/0.006       100,930,174
 2     35.518%      1.667/1.693/1.710/0.010        75,282,951
 3     34.198%      2.000/2.028/2.056/0.013        72,485,720
 4     32.928%      2.416/2.441/2.471/0.015        69,793,995
 5     32.662%      2.569/2.618/2.648/0.021        69,228,861
 6     32.507%      3.001/3.054/3.087/0.026        68,901,208
 7     32.255%      4.003/4.061/4.094/0.024        68,366,778
 8     32.167%      6.209/6.331/6.381/0.044        68,180,776
 9     32.156%      8.704/8.834/8.922/0.050        68,156,160

 avg1  34.668%                        3.567
 tot                                963.162       661,326,623
```

## ZLIB-NG (GZBUFSIZE=32KB)

 ```
 Tool: minigzip-32k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.910/0.927/0.935/0.006       100,930,174
 2     35.518%      1.552/1.596/1.609/0.012        75,282,951
 3     34.198%      1.883/1.933/1.948/0.013        72,485,720
 4     32.929%      2.303/2.347/2.363/0.014        69,796,345
 5     32.660%      2.487/2.521/2.541/0.018        69,224,788
 6     32.507%      2.909/2.955/2.978/0.020        68,901,926
 7     32.255%      3.930/3.972/3.996/0.018        68,366,778
 8     32.167%      6.130/6.245/6.276/0.033        68,180,776
 9     32.156%      8.597/8.729/8.783/0.059        68,156,160

 avg1  34.668%                        3.469
 tot                                936.764       661,325,618
 ```

## ZLIB-NG (GZBUFSIZE=48KB)

 ```
 Tool: minigzip-48k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.887/0.909/0.923/0.009       100,930,174
 2     35.518%      1.537/1.578/1.606/0.016        75,282,951
 3     34.198%      1.877/1.921/1.957/0.022        72,485,720
 4     32.930%      2.286/2.328/2.379/0.026        69,797,276
 5     32.660%      2.448/2.496/2.555/0.030        69,224,913
 6     32.507%      2.877/2.938/3.007/0.034        68,901,062
 7     32.255%      3.876/3.953/4.046/0.048        68,366,778
 8     32.167%      6.102/6.228/6.370/0.062        68,180,776
 9     32.156%      8.526/8.697/8.900/0.087        68,156,160

 avg1  34.668%                        3.450
 tot                                931.445       661,325,810
 ```

## ZLIB-NG (GZBUFSIZE=64KB)

 ```
 Tool: minigzip-64k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.889/0.912/0.931/0.011       100,930,174
 2     35.518%      1.548/1.576/1.605/0.016        75,282,951
 3     34.198%      1.881/1.913/1.945/0.017        72,485,720
 4     32.929%      2.283/2.331/2.367/0.020        69,796,074
 5     32.660%      2.444/2.504/2.553/0.022        69,225,542
 6     32.507%      2.870/2.941/2.995/0.027        68,902,152
 7     32.255%      3.914/3.969/4.039/0.031        68,366,778
 8     32.167%      6.182/6.260/6.395/0.063        68,180,776
 9     32.156%      8.593/8.752/8.970/0.108        68,156,160

 avg1  34.668%                        3.462
 tot                                934.711       661,326,327
 ```

## ZLIB-NG (GZBUFSIZE=96KB)

 ```
 Tool: minigzip-96k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.885/0.903/0.916/0.008       100,930,174
 2     35.518%      1.538/1.570/1.592/0.015        75,282,951
 3     34.198%      1.882/1.908/1.937/0.014        72,485,720
 4     32.929%      2.290/2.322/2.366/0.019        69,795,885
 5     32.660%      2.465/2.503/2.552/0.024        69,225,303
 6     32.507%      2.859/2.943/2.991/0.032        68,902,142
 7     32.255%      3.866/3.956/4.024/0.032        68,366,778
 8     32.167%      6.114/6.231/6.402/0.069        68,180,776
 9     32.156%      8.524/8.734/8.976/0.108        68,156,160

 avg1  34.668%                        3.452
 tot                                932.068       661,325,889
 ```

## ZLIB-NG (GZBUFSIZE=128KB)

 ```
 Tool: minigzip-128k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.867/0.893/0.904/0.010       100,930,174
 2     35.518%      1.515/1.553/1.572/0.011        75,282,951
 3     34.198%      1.846/1.885/1.909/0.018        72,485,720
 4     32.929%      2.253/2.295/2.321/0.017        69,796,024
 5     32.660%      2.438/2.477/2.499/0.019        69,225,485
 6     32.508%      2.857/2.909/2.937/0.023        68,902,220
 7     32.255%      3.836/3.923/3.948/0.026        68,366,778
 8     32.167%      6.077/6.194/6.235/0.045        68,180,776
 9     32.156%      8.525/8.679/8.747/0.059        68,156,160

 avg1  34.668%                        3.423
 tot                                924.247       661,326,288
 ```

## ZLIB-NG (GZBUFSIZE=192KB)

 ```
 Tool: minigzip-192k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.872/0.897/0.913/0.011       100,930,174
 2     35.518%      1.509/1.566/1.594/0.020        75,282,951
 3     34.198%      1.870/1.901/1.936/0.022        72,485,720
 4     32.929%      2.264/2.313/2.359/0.030        69,796,052
 5     32.660%      2.415/2.494/2.547/0.033        69,225,500
 6     32.508%      2.858/2.932/2.998/0.042        68,902,226
 7     32.255%      3.865/3.970/4.054/0.056        68,366,778
 8     32.167%      6.080/6.253/6.404/0.098        68,180,776
 9     32.156%      8.619/8.775/8.982/0.125        68,156,160

 avg1  34.668%                        3.456
 tot                                933.025       661,326,337
 ```

## ZLIB-NG (GZBUFSIZE=256KB)

 ```
 Tool: minigzip-256k.exe Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev   Compressed size
 1     47.618%      0.860/0.886/0.901/0.011       100,930,174
 2     35.518%      1.508/1.546/1.567/0.016        75,282,951
 3     34.198%      1.851/1.883/1.908/0.018        72,485,720
 4     32.929%      2.258/2.295/2.326/0.020        69,796,069
 5     32.660%      2.434/2.477/2.511/0.023        69,225,624
 6     32.508%      2.855/2.909/2.944/0.030        68,902,336
 7     32.255%      3.847/3.927/3.971/0.037        68,366,778
 8     32.167%      6.067/6.201/6.271/0.057        68,180,776
 9     32.156%      8.523/8.665/8.751/0.069        68,156,160

 avg1  34.668%                        3.421
 tot                                923.691       661,326,588
 ```

It seems that best performance is at 128KiB multiple.

**Comment by mtl1979** [comment]
There isn't much difference between 128 kB and 256 kB, so people who favor memory usage might want to prefer 128 kB...

**Comment by nmoinvaz** [comment]
Interestingly enough I stumbled across pigz has `g.block` size of 128kb
https://github.com/madler/pigz/commit/f310c0868634a1dbacdcdcb2dbce9501a8a87868#diff-ebd288e1c5baaf5e9ec2a343c70a3b190744a4dcedb093949e056d2ed46e0f20R4291

**Pull request merged**
