### PR TITLE
Add missing symbol name mangling

### PR DESCRIPTION
**Pull request by dzenanz**
See https://github.com/InsightSoftwareConsortium/ITK/issues/3530

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Some of these might not be needed after #1305. I'm not sure.

**Comment by dzenanz** [comment]
Oh yes, a lot of duplication with #1305. Not closing yet, though. The issue I ran into is that some dependencies link to `zlib` in compat mode **with** symbol prefix, and other dependencies link to `zlib` in compat mode **without** symbol prefix.

**Comment by dzenanz** [comment]
#1305 doesn't seem to fix it:
```text
1>------ Build started: Project: tester, Configuration: Debug x64 ------
1>itkzlib-5.3.lib(inflate.obj) : error LNK2005: inflate_ensure_window already defined in zlibstaticd.lib(inflate.obj)
1>itkzlib-5.3.lib(inflate.obj) : error LNK2005: fixedtables already defined in zlibstaticd.lib(inflate.obj)
1>itkzlib-5.3.lib(inflate.obj) : error LNK2005: inflateInit2 already defined in zlibstaticd.lib(inflate.obj)
1>itkzlib-5.3.lib(crc32_braid.obj) : error LNK2005: crc32_braid already defined in zlibstaticd.lib(crc32_braid.obj)
1>itkzlib-5.3.lib(deflate.obj) : error LNK2005: fill_window already defined in zlibstaticd.lib(deflate.obj)
1>itkzlib-5.3.lib(deflate.obj) : error LNK2005: flush_pending already defined in zlibstaticd.lib(deflate.obj)
1>itkzlib-5.3.lib(deflate.obj) : error LNK2005: read_buf already defined in zlibstaticd.lib(deflate.obj)
1>itkzlib-5.3.lib(deflate.obj) : error LNK2005: deflateInit2 already defined in zlibstaticd.lib(deflate.obj)
1>itkzlib-5.3.lib(zutil.obj) : error LNK2005: z_verbose already defined in zlibstaticd.lib(zutil.obj)
1>itkzlib-5.3.lib(zutil.obj) : error LNK2005: z_error already defined in zlibstaticd.lib(zutil.obj)
1>itkzlib-5.3.lib(adler32.obj) : error LNK2005: adler32_c already defined in zlibstaticd.lib(adler32.obj)
1>   Creating library C:/Misc/Tester/Debug/tester.lib and object C:/Misc/Tester/Debug/tester.exp
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>C:\Misc\Tester\Debug\tester.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "tester.vcxproj" -- FAILED.
```
This PR gets a bit further:
```log
1>------ Build started: Project: tester, Configuration: Debug x64 ------
1>itkzlib-5.3.lib(inflate.obj) : error LNK2005: inflateInit2 already defined in zlibstaticd.lib(inflate.obj)
1>itkzlib-5.3.lib(crc32_braid.obj) : error LNK2005: crc32_braid already defined in zlibstaticd.lib(crc32_braid.obj)
1>itkzlib-5.3.lib(deflate.obj) : error LNK2005: deflateInit2 already defined in zlibstaticd.lib(deflate.obj)
1>itkzlib-5.3.lib(zutil.obj) : error LNK2005: z_verbose already defined in zlibstaticd.lib(zutil.obj)
1>itkzlib-5.3.lib(zutil.obj) : error LNK2005: z_error already defined in zlibstaticd.lib(zutil.obj)
1>   Creating library C:/Misc/Tester/Debug/tester.lib and object C:/Misc/Tester/Debug/tester.exp
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>C:\Misc\Tester\Debug\tester.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "tester.vcxproj" -- FAILED.
```

**Comment by dzenanz** [comment]
Interestingly, `inflateInit2` and `deflateInit2` are already mangled.

**Comment by dzenanz** [comment]
I don't know whether this patch introduces any new errors compared with current `develop` branch.

**Review by Dead2 — APPROVED** [review]
LGTM

**Comment by dzenanz** [comment]
The force push was a plain rebase.

**Comment by dzenanz** [comment]
Package Check fails with:
```log
+ abidiff --no-added-syms --suppressions test/abi/ignore test/abi/zlib-ng-843c16c87afd53a20bf915661012b02acdd30281-powerpc-unknown-linux-gnu.abi btmp2/zlib-ng-built.abi
Functions changes summary: 0 Removed, 2 Changed, 0 Added functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

2 functions with some indirect sub-type change:

  [C] 'function uint32_t adler32_power8(uint32_t, const unsigned char*, size_t)' at cpu_features.h:48:1 has some indirect sub-type changes:
    parameter 3 of type 'typedef size_t' changed:
      typedef name changed from size_t to uint64_t at stdint-uintn.h:27:1
      underlying type 'unsigned int' changed:
        entity changed from 'unsigned int' to compatible type 'typedef __uint64_t' at types.h:48:1
          type name changed from 'unsigned int' to 'long long unsigned int'
          type size changed from 32 to 64 (in bits)

  [C] 'function uint32_t adler32_vmx(uint32_t, const unsigned char*, size_t)' at cpu_features.h:33:1 has some indirect sub-type changes:

+ echo abicheck: FAIL
+ exit 1
abicheck: FAIL
Error: Process completed with exit code 1.
```
Is #1384 supposed to fix that?

**Comment by mtl1979** [comment]
> Package Check fails with:
> 
> ```
> + abidiff --no-added-syms --suppressions test/abi/ignore test/abi/zlib-ng-843c16c87afd53a20bf915661012b02acdd30281-powerpc-unknown-linux-gnu.abi btmp2/zlib-ng-built.abi
> Functions changes summary: 0 Removed, 2 Changed, 0 Added functions
> Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
> 
> 2 functions with some indirect sub-type change:
> 
>   [C] 'function uint32_t adler32_power8(uint32_t, const unsigned char*, size_t)' at cpu_features.h:48:1 has some indirect sub-type changes:
>     parameter 3 of type 'typedef size_t' changed:
>       typedef name changed from size_t to uint64_t at stdint-uintn.h:27:1
>       underlying type 'unsigned int' changed:
>         entity changed from 'unsigned int' to compatible type 'typedef __uint64_t' at types.h:48:1
>           type name changed from 'unsigned int' to 'long long unsigned int'
>           type size changed from 32 to 64 (in bits)
> 
>   [C] 'function uint32_t adler32_vmx(uint32_t, const unsigned char*, size_t)' at cpu_features.h:33:1 has some indirect sub-type changes:
> 
> + echo abicheck: FAIL
> + exit 1
> abicheck: FAIL
> Error: Process completed with exit code 1.
> ```
> 
> Is #1384 supposed to fix that?

Yes...

**Pull request merged**
