### PR TITLE
Clean up insert_match() in deflate_medium

### PR DESCRIPTION
**Pull request by Dead2**
Based on #1681

insert_string() is no longer slow, so there is no need to avoid it any more.
The first commit removes the check for long matches, this also makes some of the code unreachable and warrants a further cleanup commit that removes unused code and restructures things a little bit.

The end result is that deflate_medium is the same speed or very slightly faster and also compresses slightly better on average (depends on the specific test data).

For reviewing, I recommend not showing whitespace changes.

### CODE REVIEW

**Comment by Dead2** [comment]
# Develop ca0e4634e1914ecfe67e40261bbf54676f0d1c8f Feb 21
```
 Tool: minigzip   Levels: 1-9
 Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.166%      0.150/0.154/0.156/0.001        0.034/0.036/0.038/0.001        8,523,732
 2     43.871%      0.244/0.249/0.250/0.001        0.032/0.036/0.038/0.002        6,903,609
 3     42.387%      0.295/0.297/0.299/0.001        0.031/0.034/0.036/0.001        6,670,099
 4     41.647%      0.317/0.324/0.326/0.002        0.030/0.034/0.035/0.001        6,553,723
 5     41.216%      0.344/0.352/0.354/0.002        0.032/0.034/0.035/0.001        6,485,938
 6     41.037%      0.390/0.397/0.400/0.003        0.030/0.033/0.035/0.001        6,457,776
 7     40.778%      0.493/0.498/0.503/0.003        0.030/0.034/0.035/0.001        6,416,919
 8     40.704%      0.605/0.613/0.618/0.004        0.029/0.033/0.034/0.001        6,405,244
 9     40.409%      0.912/0.919/0.925/0.004        0.029/0.033/0.035/0.002        6,358,951

 avg1  42.913%                        0.423                          0.034
 tot                                114.095                          9.195       60,775,991

   text    data     bss     dec     hex filename
 138190    1352       8  139550   2211e libz-ng.so.2
```
# PR #1681 Remove update-hash/insert-string from functable
```
 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.185%      0.105/0.109/0.111/0.002        0.032/0.035/0.038/0.002        8,526,745
 2     43.871%      0.198/0.200/0.202/0.001        0.034/0.036/0.038/0.001        6,903,702
 3     42.388%      0.243/0.248/0.250/0.002        0.032/0.035/0.036/0.001        6,670,239
 4     41.647%      0.276/0.280/0.282/0.002        0.031/0.034/0.035/0.001        6,553,746
 5     41.216%      0.304/0.310/0.312/0.002        0.031/0.034/0.035/0.001        6,485,936
 6     41.038%      0.350/0.357/0.361/0.003        0.030/0.033/0.035/0.001        6,457,827
 7     40.778%      0.498/0.504/0.508/0.003        0.030/0.033/0.035/0.001        6,416,941
 8     40.704%      0.610/0.620/0.625/0.004        0.029/0.033/0.035/0.001        6,405,249
 9     40.409%      0.902/0.907/0.912/0.003        0.030/0.034/0.035/0.001        6,358,951

 avg1  42.915%                        0.393                          0.034
 tot                                106.069                          9.209       60,779,336

   text    data     bss     dec     hex filename
 137222    1312       8  138542   21d2e libz-ng.so.2
 ```
 
 # PR #1681 + #1682 Clean up insert_match()
 ```
 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     54.185%      0.105/0.109/0.111/0.001        0.033/0.036/0.038/0.002        8,526,745
 2     43.871%      0.198/0.201/0.203/0.001        0.031/0.036/0.038/0.002        6,903,702
 3     42.390%      0.245/0.249/0.251/0.002        0.031/0.035/0.036/0.001        6,670,664
 4     41.644%      0.274/0.278/0.281/0.002        0.032/0.034/0.035/0.001        6,553,205
 5     41.215%      0.303/0.308/0.311/0.002        0.030/0.033/0.035/0.001        6,485,659
 6     41.032%      0.349/0.356/0.360/0.002        0.031/0.033/0.035/0.001        6,456,912
 7     40.778%      0.492/0.501/0.505/0.003        0.030/0.033/0.036/0.002        6,416,941
 8     40.704%      0.604/0.615/0.620/0.003        0.031/0.033/0.035/0.001        6,405,249
 9     40.409%      0.899/0.906/0.911/0.004        0.030/0.033/0.035/0.001        6,358,951

 avg1  42.914%                        0.392                          0.034
 tot                                105.726                          9.191       60,778,028

   text    data     bss     dec     hex filename
 137158    1312       8  138478   21cee libz-ng.so.2
 ```
 
 Compression speed is similar.
 Library size is slightly smaller.

 Compressed size recoups most of the lost compression ratio from #1681, with the exception of level 1 that lost quite a bit. Note that the lost compression ratio in #1681 is due to a change of hashing algorithm (removal of the slower SSE4.2 one), causing different string collisions, this can improve or worsen compression ratio depending on the data.
 The improvement here in #1682 is also data dependent, but has a higher chance of causing an improvement for any data.

**Comment by mtl1979** [comment]
I would "separate" the last commit to own PR which would also cleanup the unreachable code... It would make it easier to catch any possible negative side-effects of the commit. This would also mean that the second-to-last commit could be moved to #1681 instead.

**Comment by Dead2** [comment]
@mtl1979 I considered doing that initially, but I really don't think that commit belongs in #1681, as it is not at all related to removing insert_string from functable, other than by the improved performance. And it is in itself a significant change that would only muddy #1681.

In my tests, the compressed output did not change with the last cleanup commit.

**Comment by mtl1979** [comment]
> @mtl1979 I considered doing that initially, but I really don't think that commit belongs in #1681, as it is not at all related to removing insert_string from functable, other than by the improved performance. And it is in itself a significant change that would only muddy #1681.
> 
> In my tests, the compressed output did not change with the last cleanup commit.

I didn't really see any compelling reason to split all these to three PRs either... What I thought was expanding the scope of #1681 to recoup some of the lost compression rate so it self-justifies removing the optimized hashing functions.

**Comment by nmoinvaz** [comment]
## silesia.tar
MSVC 19.38.33134.0
### DEVELOP af494fc34f01878133806af7ad52f4e14f61c460
```
OS: Windows 10 10.0.22631 AMD64
CPU: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
Tool: ../zlib-ng/build-develop/Release/minigzip.exe Size: 105,472 B
Levels: 0-9
Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.087/0.088/0.089/0.001        0.084/0.086/0.086/0.001      211,973,953
 1     44.409%      0.696/0.701/0.704/0.002        0.340/0.343/0.344/0.001       94,127,497
 2     35.519%      1.104/1.107/1.109/0.001        0.334/0.337/0.338/0.001       75,286,322
 3     33.882%      1.471/1.480/1.483/0.002        0.320/0.323/0.324/0.001       71,815,206
 4     33.175%      1.712/1.716/1.718/0.002        0.313/0.316/0.316/0.001       70,317,229
 5     32.661%      1.948/1.953/1.955/0.002        0.310/0.312/0.313/0.001       69,228,146
 6     32.507%      2.329/2.337/2.341/0.003        0.309/0.310/0.311/0.001       68,902,143
 7     32.255%      3.089/3.101/3.105/0.003        0.308/0.310/0.311/0.001       68,366,759
 8     32.167%      4.984/5.146/5.178/0.041        0.307/0.310/0.311/0.001       68,180,762
 9     31.887%      5.441/5.524/5.547/0.026        0.305/0.306/0.307/0.001       67,586,442

 avg1  40.847%                        2.315                          0.295
 avg2  45.386%                        2.572                          0.328
 tot                                694.570                         88.578      865,784,459
```
### PR #1682 rebased on DEVELOP
```
OS: Windows 10 10.0.22631 AMD64
CPU: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
Tool: ../zlib-ng/build-1682/Release/minigzip.exe Size: 105,472 B
Levels: 0-9
Runs: 70         Trim worst: 40

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.087/0.089/0.089/0.001        0.084/0.086/0.086/0.001      211,973,953
 1     44.409%      0.696/0.700/0.702/0.002        0.341/0.343/0.344/0.001       94,127,497
 2     35.519%      1.102/1.106/1.108/0.002        0.334/0.337/0.338/0.001       75,286,322
 3     33.844%      1.464/1.469/1.471/0.002        0.321/0.323/0.323/0.001       71,735,218 *
 4     33.146%      1.700/1.705/1.707/0.002        0.313/0.315/0.316/0.001       70,255,223 *
 5     32.642%      1.956/1.962/1.965/0.002        0.309/0.311/0.312/0.001       69,187,419 *
 6     32.483%      2.343/2.350/2.353/0.002        0.307/0.309/0.310/0.001       68,850,776 *
 7     32.255%      3.101/3.110/3.114/0.004        0.309/0.310/0.310/0.000       68,366,759
 8     32.167%      5.139/5.182/5.193/0.014        0.309/0.310/0.311/0.000       68,180,762
 9     31.887%      5.485/5.549/5.565/0.019        0.304/0.307/0.308/0.001       67,586,442

 avg1  40.836%                        2.322                          0.295
 avg2  45.373%                        2.580                          0.328
 tot                                696.639                         88.511      865,550,371
```
Levels 1-2 and 7-9 the compression level stays the same.
* Level 3: -79,988 bytes (PR wins)
* Level 5: -40,727 bytes (PR wins)
* Level 4: -62,006 bytes (PR wins)
* Level 6: -51,367 bytes (PR wins)

**Review by nmoinvaz — APPROVED** [review]
It looks to me like a nice little simplification. Some of the code there before looks like it was not really necessary.

**Pull request merged**
